### PR TITLE
Panel: remove inline validation

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by afbora** [comment]
Related issues to close #1514 #2270

**Comment by bastianallgeier** [comment]
I wonder if we should release this in a 3.4.x release or if it is something for 3.5. What do you think?

**Comment by distantnative** [comment]
Yea, tricky. Maybe it is a bigger change, cause a feature is leaving - could it be a breaking one where someone relies on inline validation? Probably no cause the backend validation would still prevent values from getting saved. On the other hand, it also fixes some bugs. Maybe a topic to test the waters with the community?

**Comment by bastianallgeier** [comment]
It can't really break plugins as far as I know. We haven't created a way to use the existing validators in plugins so far. That's why field plugins have no way of reusing our inline validation code. But without communicating it clearly, it could feel like we simply broke validation entirely with this change.

**Comment by distantnative** [comment]
That's true and attention will be much better for the 3.5.0 release notes than 3.4.2

**Pull request closed without merging**
