### PR TITLE
Fix deprecation warning for `$app->markdown()`

### PR DESCRIPTION
**Pull request by lukasbestle**
### Fixes

- Calling `$kirby->markdown()` or `$field->markdown()` no longer triggers a deprecation warning
- Custom `markdown` components no longer break because of `null` being passed to `$inline`

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] ~In-code documentation (wherever needed)~
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~

### CODE REVIEW

**Comment by afbora** [comment]
Since we removed the `$inline` parameter, we have a deprecation warning. But it will give an error for users who use `bool $inline = false`. Just like in [unit testing](https://github.com/getkirby/kirby/pull/4396/commits/099c9db25a5b641f92e5d08d48b6b6772ec8f69e). Do we need to make a further explanation in the release notes for this? Because of this change throws fatal error not notice.

**Review by afbora — DISMISSED** [review]

**Comment by lukasbestle** [comment]
Good point. Custom components that don't allow `null` will break. Hm, this is really difficult. We only did the two-step change with the deprecation to avoid a sudden breaking change. But now we suddenly have one. :(

What we could do: Revert to passing `false` by default. And in the core component, instead of checking for `null`, we would check for `func_num_args() < 4`. Not sure if this would break anything else though.

**Comment by afbora** [comment]
I think **func_num_args()** is genius idea 💯

**Comment by lukasbestle** [comment]
The `func_num_args()` check does not cover use cases where the dev calls any of the methods with PHP 8 named arguments and leaves out `$options` completely, but it's unlikely anyone used this feature for these methods. Also it will just lead to a false negative for the deprecation warning, so nothing serious.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
