### PR TITLE
PHP 8.2 prep: Fix dynamic properties in search component

### PR DESCRIPTION
**Pull request by distantnative**
### Refactored 
- Search core component does not impose dynamic properties (`searchScore` and `searchHits`) on search items

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Review by bastianallgeier — COMMENTED** [review]
This would be a breaking change. I'm not sure if we document it properly somewhere. But the reason for the dynamic properties is to be able to access them after running the search to get more info about the search hits and score for each item in the collection.

**Comment by distantnative** [comment]
Ok but then we need the breaking change or we have to add the properties to each and any class that could be an item here.

PHP 8.2 just starts throwing warnings everywhere because of these.

**Comment by distantnative** [comment]
And was this actually ever documented anywhere? Or have you been the only one knowing about this possibility? 😄

**Comment by distantnative** [comment]
I had a look at the code again

> add the properties to each and any class that could be an item here

This won't work as the search core component is user by `Cms\Collection::search()`. So all kinds of objects could be in a collection. I only see the way to make this a breaking change - if we want to consider it a breaking change, still think this has been internal code not exposed to anybody as functionality.

**Comment by bastianallgeier** [comment]
I think you are right. I checked again and I couldn't find it anywhere in our docs. PHP 8.2 support also seems like a much more important step than keeping those.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
