### PR TITLE
Fail silently when model queries throw exceptions

### LINKED ISSUE #2689: [3.4.0-rc.2] Error on Panel builder file select
**Describe the bug**  
I'm getting an error when i want to select an image in structured field with the builder plugin.

Error: Access to non-existing property pages/modules on array

**To Reproduce**  
**site/blueprints/pages/modules.yml**

```yaml
title: Modules

fields:
  modules:
    label: Modules
    type: builder
    columns: 1
    fieldsets:
      cards:
        label: Cards
        type: fields
        tabs:
          content:
            label: Content
            icon: edit
            fields:
              cardimage:
                label: Card Image
                type: files
                multiple: false
```

**Console output**  
```
app.js:1 GET http://kirby3-dev.test/api/kirby-builder/pages/trouwalbums/fields/modules+cards+cards+cardimage?page=0 400 (Bad Request)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 {status: "error", message: "Access to non-existing property pages/trouwalbums on array", code: 400, exception: "Kirby\Exception\BadMethodCallException", key: "error.invalidMethod", …}
rv.config.onError @ app.js:1
(anonymous) @ app.js:1
Promise.catch (async)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 POST http://kirby3-dev.test/api/site/children 400 (Bad Request)
request @ app.js:1
post @ app.js:1
submit @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
oe @ vendor.js:23
Tn.t.$emit @ vendor.js:23
submit @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 {status: "error", message: "A page draft with the URL appendix "modules" already exists", code: 400, exception: "Kirby\Exception\DuplicateException", key: "error.page.draft.duplicate", …}
rv.config.onError @ app.js:1
(anonymous) @ app.js:1
Promise.catch (async)
request @ app.js:1
post @ app.js:1
submit @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
oe @ vendor.js:23
Tn.t.$emit @ vendor.js:23
submit @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 GET http://kirby3-dev.test/api/kirby-builder/pages/modules/fields/modules+cards+cards+cardimage?page=0 400 (Bad Request)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 {status: "error", message: "Access to non-existing property pages/modules on array", code: 400, exception: "Kirby\Exception\BadMethodCallException", key: "error.invalidMethod", …}
rv.config.onError @ app.js:1
(anonymous) @ app.js:1
Promise.catch (async)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 GET http://kirby3-dev.test/api/kirby-builder/pages/modules/fields/modules+cards+cards+cardimage?page=0 400 (Bad Request)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 {status: "error", message: "Access to non-existing property pages/modules on array", code: 400, exception: "Kirby\Exception\BadMethodCallException", key: "error.invalidMethod", …}
rv.config.onError @ app.js:1
(anonymous) @ app.js:1
Promise.catch (async)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
/panel/site#settings:1 Autofocus processing was blocked because a document already has a focused element.
app.js:1 GET http://kirby3-dev.test/api/kirby-builder/pages/modules/fields/modules+cards+cards+cardimage?page=0 400 (Bad Request)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 {status: "error", message: "Access to non-existing property pages/modules on array", code: 400, exception: "Kirby\Exception\BadMethodCallException", key: "error.invalidMethod", …}
rv.config.onError @ app.js:1
(anonymous) @ app.js:1
Promise.catch (async)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 GET http://kirby3-dev.test/api/kirby-builder/pages/modules/fields/modules+cards+cards+cardimage?page=0 400 (Bad Request)
request @ app.js:1
get @ app.js:1
fetch @ app.js:1
open @ app.js:1
open @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
Ni.i._wrapper @ vendor.js:23
app.js:1 {status: "error", message: "Access to non-existing property pages/modules on array", code: 400, exception: "Kirby\Exception\BadMethodCallException", key: "error.invalidMethod", …}
```

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

- Fixes #2689 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by lukasbestle** [comment]
💡 Idea: What about only catching this particular Exception in the files field (https://github.com/getkirby/kirby/blob/fa549aae38d5555e297b1870071418c5bb4a95f1/config/fields/files.php#L50)? Then we don‘t have to silence every query Exception everywhere.

**Comment by bastianallgeier** [comment]
I think we have the same in other parts. I.e. sections with different parents.

**Comment by lukasbestle** [comment]
Hm, I see. What about only silencing the Exceptions if debug mode is disabled?

**Comment by bastianallgeier** [comment]
I like that idea!

**Comment by bastianallgeier** [comment]
@lukasbestle I've implemented the debug mode

**Comment by nilshoerrmann** [comment]
Wouldn't that technique also be interesting for #2688?

**Review by lukasbestle — APPROVED** [review]

**Comment by bastianallgeier** [comment]
@nilshoerrmann I think it's a different case there. Passing an empty value or null happens quite often and is not necessarily caused by a bug. In this case the exception is thrown when there's actually a broken query. That's why I think it's good here to have the debug option.

**Pull request merged**
