### PR TITLE
PHP 7.4 feature: arrow functions

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

- [x] Requires dropped PHP 7.3 support

Some first refactoring to use arrow functions e.g. for `array_map`

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] ~~In-code documentation (wherever needed)~~
- [x] CI checks pass

## When merging

- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~
- [x] ~~Add changes to release notes draft in Notion~~

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]
I went through it and couldn't find any issues, but it would be good if a second pair of eyes could have a look at it. cc @lukasbestle @afbora 

BTW I really love that we can get rid of the use statements with the new syntax.

**Comment by texnixe** [comment]
The only thing I noticed is that some instances of `array_map` were replaced with `A::map()` but not all. Wouldn't it make sense to replace them all for consistency?

**Comment by bastianallgeier** [comment]
@texnixe I guess it was only applied when the A class is already defined. I think it would be good to decide if we want to use it everywhere or if we stick to the native array_map method.

**Comment by distantnative** [comment]
I threw it in where it felt right to me but I didn't go through systematically to replace the native method.

**Pull request merged**
