### PR TITLE
Upgrade npm dependencies

### PR DESCRIPTION
**Pull request by distantnative**
### Breaking changes
New minimum browser requirements (browsers with dynamic `import()` support):
- Firefox 67+
- Chrome 63+,
- Opera 50+
- macOS Safari 11.1+
- Safari iOS 11+
- Android Browser 92+
- Chrome for Android 92+

```
BEFORE
dist/css/style.css   101.03kb / brotli: 14.59kb
dist/js/index.js     312.19kb / brotli: 59.71kb
dist/js/vendor.js    379.32kb / brotli: 103.77kb

AFTER
dist/css/style.css   101.03kb / brotli: 14.59kb
dist/js/index.js     307.71kb / brotli: 59.20kb
dist/js/vendor.js    383.11kb / brotli: 105.08kb
```

### CODE REVIEW

**Comment by lukasbestle** [comment]
The issue was likely caused by this change in the `vite-plugin-vue2`: https://github.com/underfin/vite-plugin-vue2/pull/87
See this issue: https://github.com/underfin/vite-plugin-vue2/issues/103

I can't reproduce the CI issue locally either, but I also didn't find a way to fix it. An option could be to downgrade `vite-plugin-vue2` again or to use a different Vite plugin implementation.

**Comment by distantnative** [comment]
Maybe rather this https://github.com/underfin/vite-plugin-vue2/commit/4de9cb8242551f1f0348e71f5acdb938c750f527 - which would mean e need to install `vue-template-compiler` ourselves?

**Comment by distantnative** [comment]
I think that one is the main vite plugin for Vue 2 - haven't seen anything else in use - Vue 3 would allow us to use the official plugin.

**Review by lukasbestle — DISMISSED** [review]
Dafuq, why was it changed to a dependency and then changed back to a peer dependency in the same release? :D

Anyway, glad we found it. Weird that it only occurred in CI.

Assuming you have already checked for breaking changes in the updated dependencies, I approve this PR.

**Comment by distantnative** [comment]
I did... I am still not happy with this. With `Vite-plugin-vue2@1.7.2` we saved quite a few more JS KB... I still want to give it a try with requiring the peer dependency directly

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
