### PR TITLE
Psalm's security analysis workflow

### PR DESCRIPTION
**Pull request by afbora**
I thought Psalm's security scan would be good. What do you thinking?

https://github.com/psalm/psalm-github-actions
https://github.com/marketplace/actions/psalm-security-scanner-for-php

I saw the information that the workflow report can be hidden (only organization members can access it), but I couldn't set it completely.

**Code scanning alerts**
https://github.com/getkirby/kirby/security/code-scanning?query=is%3Aopen+branch%3Aafbora%2Flab%2Fpsalm-security-analysis

### CODE REVIEW

**Comment by lukasbestle** [comment]
We already upload the SARIF file in line 198. Does the action do anything more?

**Comment by afbora** [comment]
@lukasbestle I've removed that step and now seems doesn't working..

**Comment by lukasbestle** [comment]
To be honest I think we are already fully covered regarding Psalm integration in CI.

**Comment by afbora** [comment]
So we already have a security check? I don't remember the workflow making a security notice like below before.

https://github.com/getkirby/kirby/security/code-scanning?query=is%3Aopen+branch%3Aafbora%2Flab%2Fpsalm-security-analysis

**Comment by lukasbestle** [comment]
Yes, we had such a report before. But because we fix them before merging, they don't end up as an active issue in the list.

**Comment by lukasbestle** [comment]
The taint reports are of limited use to us at the moment because Psalm does not understand all code paths yet. That's why we have these disabled at the moment.

**Comment by afbora** [comment]
Got it. So lets close it. Thanks for the review 👍 Maybe we'll take a look here if needed in the future.

**Pull request closed without merging**
