### PR TITLE
Finalize `Kirby\Filesystem` refactoring

### LINKED ISSUE #3329: More `Filesystem` cleanup
As discussed in https://github.com/getkirby/kirby/pull/3285:

- Move `F` and `Dir` classes into `Filesystem` namespace
- Check if `Toolkit\File` can be moved into `Filesystem` as well (conflicts with the already existing `Filesystem\File`)

### PR DESCRIPTION
**Pull request by distantnative**
#### TODO
- [ ] Fix unit tests (somehow each namespace individually passes, once we run all, weird errors are popping up)

### Fixed
- `Dir::inventory` returns now integers for `num` keys

### Refactoring
- Merged `Kirby\Toolkit\File` into `Kirby\Filesystem\File`
- Moved `F`, `Dir` and `Mime` to `Kirby\Filesystem`
- Added class aliases for all of them

### Breaking changes

_None_

## Related issues/ideas

- Fixes #3329

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
@lukasbestle could you try to help here?

Unit tests fail with unclear errors for me when running 

```
composer run-script test
```

However, all unit tests pass when I run them for each namespace individually e.g.

```
composer run-script test tests/Toolkit
```

**Comment by lukasbestle** [comment]
I will take a look once my todo list has cleared up. :)

**Comment by distantnative** [comment]
@lukasbestle would be great if we could merge this soon, so we can close that bucket of changes for 3.6

**Comment by afbora** [comment]
This is really weird. Some tests in the report were not working for me either. I fixed it but it still fails. 🤷‍♂️

**Comment by lukasbestle** [comment]
First we‘ll have the 3.5.7 RC tomorrow/on Wednesday. I‘ll take a look after that.

**Review by lukasbestle — APPROVED** [review]
@distantnative Really good job with this PR! 👍😍
Thanks a lot for cleaning up these test classes. It's all improved a lot now.

You won't believe what caused the test failures: `FileTest::$block` was unset *before* each test in `setUp()`, but not *after* each test in `tearDown()`. This means that the very last test in the class that also happens to block `file_put_contents()` sets that state forever for all following tests. Adding the unset line to `tearDown()` as well fixed that.

I debugged this by first aggressively deleting all test packages that weren't failing (so I didn't need to wait as long for each pass). Then I deleted each test class in `Filesystem` one by one to see which file causes it (with `FileTest` deleted it worked). Then I disabled all test methods in `FileTest` and reenabled them in groups to track it down to `testWriteFail()`. A pretty manual process, but it worked quite well. 😅 

Besides that I committed some improvements and fixes. Please review them to double check. Then I think we can merge this already for 3.6.0-alpha.

PS: I also rebased against `develop` because of a merge conflict in `Toolkit\Mime`. The rebase went through smoothly.

**Comment by distantnative** [comment]
Oh wow, thanks for finding the test error.

The additional changes look fine to me!

**Pull request merged**
