### PR TITLE
Revert autoresize scroll restore

### LINKED ISSUE #5868: [v4] Textarea doesn't scroll to the new line
## Description

Related PR: https://github.com/getkirby/kirby/pull/5846

## To reproduce

1. Go to textarea field
2. Enter long long text
3. Enter multiple new lines
4. See issue that you won't see last line (browser should scroll to end of text)

## Your setup
**Kirby Version**  
Beta.3 (v4/develop)

### LINKED ISSUE #5871: [v4] Textarea: doesn't restore size after revert changes
## To reproduce

1. Go to textarea field
2. Enter long long text
3. Revert page changes 
4. See issue that textarea size still long (should be restore initial size)

## Your setup
**Kirby Version**  
Beta.3 (v4/develop)

### LINKED ISSUE #5906: [v4] Textarea toolbar button click makes scroll position jump
## Description
When editing content in a textarea field, the toolbar creates unexpected Markdown for block elements. Think of this existing content, the pipe being the cursor:

```md
# An example |headline
```

If I select headline 3 in the toolbar, the following will be created:

```md
# An example ### |headline
```

Same example as before, if I click headline 1 again to unselect it and make the current line a paragraph again, the following will be created:

```md
# An example # |headline
```
 
**Expected behavior**  
The block level elements should alter the Markdown blocks and not thus change the marks at the very beginning of the line.

## To reproduce

```yml
title: Markdown Test
fields:
  text:
    label: Text
    type: textarea
```

## Your setup
**Kirby Version**  
Kirby 4 Beta 3 on Firefox 119 (macOS Sonoma)

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- https://github.com/getkirby/kirby/issues/5906
- https://github.com/getkirby/kirby/issues/5871
- https://github.com/getkirby/kirby/issues/5868

### Known issue
- Need to reopen #5251

### CODE REVIEW

**Comment by afbora** [comment]
Before the reviewing the PR; Sorry for the curiosity. I just wonder that why [we removed](https://github.com/getkirby/v4/pull/33/files) the `autosize` dependency? What was the reason? Maybe we can avoid potential issues if we switch back to this dependency.

**Comment by distantnative** [comment]
@afbora the discussion in https://github.com/getkirby/kirby/issues/5251 says it already exists in v3.x where we still used that library. That's why so far I have assumed that the library has the same issue.

**Comment by afbora** [comment]
Hmm, actually I can't reproduce the scroll jump issue in 3.9.5 or 3.9.7 🤷‍♂️ This issue looks like only valid in v4 for me.

**Comment by distantnative** [comment]
I'll set up a v4 branch with the old library for testing

**Comment by distantnative** [comment]
Here is the branch https://github.com/getkirby/kirby/tree/v4/fix/autosize

However, I can reproduce the issue both, on this branch as well as on 3.9.5.

**Comment by afbora** [comment]
@distantnative I think It's not exactly the same issue. In 3.9.7 the scroll jumps up a bit and I can still see the paragraph, but in beta.2 the scroll goes to the top.

### 3.9.7

https://github.com/getkirby/kirby/assets/3393422/eae47dd5-a62c-44f2-9122-19957da175de


### Beta.2

https://github.com/getkirby/kirby/assets/3393422/dae2a96f-ed51-4b73-8e20-f2dc879b20b2

**Comment by afbora** [comment]
Also I think this is intended behavior that scrolling to start of new paragraph (not top of the field) in 3.9.x. Also you can test in https://www.jacklmoore.com/autosize (you'll see the same behavior)

The only problem is that our sticky toolbar closes/covers the first paragraph (when scroll to the start of new paragraph). If we fix it, there is no problem.

**Comment by distantnative** [comment]
Ok then maybe using  https://github.com/getkirby/kirby/tree/v4/fix/autosize would be better. But I don't have a good idea how to fix that the scroll is set to behind our toolbar.

**Comment by afbora** [comment]
OK. I've tested your new branch but doesn't behave exactly like 3.9.x. The beginning of the paragraph goes up a little more than usual. Because we have new sticky page header. If you test it after deleting page header (`<header class="k-header k-page-view-header"></header>`) from browser console. You'll understand the issue.

Also I think we should remove old `<k-autosize>` tag from new branch.

**Comment by distantnative** [comment]
What do you mean with that last comment? We do remove the k-autosize: https://github.com/getkirby/kirby/commit/2c3850c335742bc54d9bfe61b8f3dea37f7eaab9#diff-08c8cb2c84dd92020daa4b0d4349c224e528cb5f3b8912c7ddbcf17c6d2f3fdfL33

And yes, v4 has more "overlapping" due to the header. But how can we solve this as the scroll restoration by the autosize library is magic/obscure?

**Comment by afbora** [comment]
@distantnative I mean this line https://github.com/getkirby/kirby/blob/v4/fix/autosize/panel/src/components/Forms/Input/TextareaInput.vue#L13

**Comment by distantnative** [comment]
Ohhh right!

**Comment by afbora** [comment]
@distantnative If you create new PR for the branch, lets discuss about the solution in it.

**Comment by distantnative** [comment]
👉 https://github.com/getkirby/kirby/pull/5914

**Pull request closed without merging**
