### PR TITLE
Fix cardlets layout in Safari

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- #5391

### CODE REVIEW

**Comment by bastianallgeier** [comment]
This changes the cardlets pretty drastically and they no longer extend to the full width. Is this intended?

**Comment by distantnative** [comment]
Really? No they seemed to work fine for me - then something went wrong

**Comment by bastianallgeier** [comment]
auto-fit and auto-fill do very different things. But after trying around with it in Safari, it seems like it really hates auto-fit and I can't find a way so far to use it.

**Comment by distantnative** [comment]
Exactly what I encountered

**Comment by distantnative** [comment]
@bastianallgeier can you exactly describe where `auto-fit` and `auto-fill` differ in your use cases? Cause I am trying both with Chrome and get 100% the same results for my tests.

**Comment by bastianallgeier** [comment]
It's especially noticeable on bigger screens. 

auto-fit:

Screenshot 2023-08-02 at 10 05 14

auto-fill:

Screenshot 2023-08-02 at 10 05 03

**Comment by distantnative** [comment]
Don't you think in this case auto-fill looks actually even better?

**Comment by bastianallgeier** [comment]
I think it feels better on a large screen if the cardlets expand, but there's not really a good way to fix this right now, so auto-fill is obviously the more straight forward solution. I went for a slightly bigger cardlet size once the space is available.

**Pull request merged**
