### PR TITLE
Improve collection unset

### LINKED ISSUE #1232: Programmatically deleting drafts in hook throws error
**Describe the bug**
Trying to programmatically delete subpage `drafts` within a `page.changeStatus:after` hook, throws the following error: `SyntaxError: Unexpected token T in JSON at position 0`

3/5 pages get deleted, 2/5 (identical) don’t.

Here is the `config.php`

```
'page.changeStatus:after' => function ($newPage, $oldPage) {
            if($newPage->intendedTemplate() == 'project' && $newPage->status() == 'unlisted') {
                foreach($newPage->drafts() as $phase) {
                    try {
                        $phase->delete();
                        echo 'The page has been deleted';
                    } catch(Exception $e) {
                        echo $e->getMessage();
                    }
                }   
            }
        }
```

**To Reproduce**
1. Add subpages to parent page
2. Change status from `listed` to `unlisted` for parent page through the panel
3. See error

**Expected behavior**
All pages should be deleted.

**Kirby Version**
3.0.0-beta-6.22

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 70

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Let me introduce you to the method I saw for the first time: [ArrayIterator::offsetUnset](https://www.php.net/manual/en/arrayiterator.offsetunset.php) 🎉 

It is doing exactly what we need. Very simple but effective. 
I solved it so simple, and i tested it over and over again to make sure 😅 

## Related issues

- Fixes #1232 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Fixed code style issues with CS fixer and `composer fix`
- [ ] Added in-code documentation (if neeed)

### CODE REVIEW

**Comment by distantnative** [comment]
Mindblown if that really is the solution!
I think we should add unit tests for the reported bug and see if it works.

**Comment by bastianallgeier** [comment]
OMG, it would be sooooo cool to finally fix this. @afbora you are my hero at the moment! I thought this is unsolvable tbh.

**Comment by afbora** [comment]
😊 Thank you so much @bastianallgeier
I found it while researching with `ArrayIterator`
Please add 3 points there for me 🤣 

I couldn't write unit tests because I wasn't good at  btw 🙏

**Comment by bastianallgeier** [comment]
@afbora I will add a unit test now

**Comment by bastianallgeier** [comment]
@afbora unfortunately it doesn't work for me :(

Consider the following test case in PHPUnit in the Kirby\Toolkit\CollectionTest class: 

```php
    public function testRemoveMultiple()
    {

        $collection = new Collection();

        $collection->set('a', 'A');
        $collection->set('b', 'B');
        $collection->set('c', 'C');

        $this->assertCount(3, $collection);

        foreach ($collection as $key => $item) {
            $collection->remove($key);
        }

        $this->assertCount(0, $collection);
    }
```

This fails because the collection still contains 1 item after the loop when it should actually be empty afterwards. Do you have any idea? Can you replicate this? It seems to be a bug in PHP: https://stackoverflow.com/questions/38527123/php-always-losing-item-1-in-arrayiterator-with-using-arrayiteratoroffsetunse

**Comment by afbora** [comment]
@bastianallgeier Actually, I've done so many tries about page deletion, I was wrong sorry..
But there are working examples that i know and I'll research them 👀 

Now I'm a bad hero 😢

**Comment by afbora** [comment]
@bastianallgeier Now finally fixed the issue 🎉

**Comment by afbora** [comment]
CS Fixer gives error on different classes after the test (100%), I couldn't fix it btw

**Comment by bastianallgeier** [comment]
Holy shit! It really works 😳I have to google now what's the difference between Iterator and IteratorAggregate :)

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
It's a bit of black magic to me because I don't really understand the IteratorAggregate concept, but all our tests pass fine and there don't seem to be any issues with the switch. I'm really excited about this!

**Comment by afbora** [comment]
> I have to google now what's the difference between Iterator and IteratorAggregate :)

To be honest, I didn't know either. 
I researched the working samples (especially Laravel) and carried them to our system. 
It was a great pleasure to see it work ☺️

**Pull request merged**
