### PR TITLE
Add custom panel CSS and JS (Fix #597)

### LINKED ISSUE #597: [Panel] Simple custom css/js
> Is there a current best practice to add some quick custom CSS to the panel?

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I wouldn't load them from the assets folder but use an option instead

```
return [
  'panel' => [
    'css' => 'some/relative/path.css',
   'js' => 'some/relative/path.js'
  ]
];
```

Then we also don't have to check if the file exists. When the option is set, the file is being loaded.

**Comment by distantnative** [comment]
More like this, @bastianallgeier?

**Comment by jenstornell** [comment]
@bastianallgeier Can we keep the english here as well? Would help us up north to understand what is going on. ☺

**Comment by bastianallgeier** [comment]
@jenstornell sorry! That was totally by accident. I just fixed it.

**Comment by jenstornell** [comment]
I think it would be nice to add multiple css files. Maybe one css is for a bar and another is for the footer. If they are taken from different repos that are updated independently, we want to keep them separated.

Also, not sure what you think of the possibility to add custom css and js from plugins?

**Comment by bastianallgeier** [comment]
I wrapped them in the URL::to method instead. The only issue is that we can't load them this way in dev mode, but I think that's fine.

**Pull request merged**
