### PR TITLE
Add placholder for tags field

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
```
tags:
  type: tags
  placeholder: you, me, her
```
Screenshot 2019-04-16 at 20 21 31
Screenshot 2019-04-16 at 20 26 56

## Related issues
- Adds https://github.com/getkirby/ideas/issues/37

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Hm, I wonder if we should either have a design that looks more like a placeholder or if we use only a placeholder for the input. 

@neildaniels you had the original request. What do you think?

**Comment by neildaniels** [comment]
Actually, this `tags` thing wasn't mine. Looks like its @wottpal request?

**Comment by neildaniels** [comment]
But, I am curious to know what @wottpal had in mind.

I personally wouldn't have expected `placeholder` to look like this. Something as simple as a grayed-out text string in an empty field would have done it for me.

> Screenshot 2019-04-16 at 20 21 31

However, assuming these "placeholders" were clickable to enable/disable, this seems compelling as something that compliments the `options` property, as if these were "topOptions" (surely there's a better name).

From a functionality standpoint, this is almost exactly what I wanted from a "checkboxes field with write-ins allowed" field https://github.com/getkirby/kirby/issues/1670#issuecomment-483368212

**Comment by distantnative** [comment]
My thought here was mainly that I wouldn't expect a placeholder to look like actual content would never look like in this field (simple grey string... actual values in a tags field will never be a full black string).

**Comment by texnixe** [comment]
@distantnative However, how does a user not familiar with how the field should look like know that the grey buttons are not content? If placeholders in general can be a usability issue, such button-style placeholders would be even worse, I think.

**Pull request closed without merging**
