### PR TITLE
Return type declarations Cms folder

### PR DESCRIPTION
**Pull request by modufolio**
## Describe the PR

Added Return type declarations to the functions in the Cms folder

### CODE REVIEW

**Comment by modufolio** [comment]
This only works in 8.0 because of union types and static type

**Comment by distantnative** [comment]
We have stayed away from declaring specific classes as return types as this has been causing problems with how PHP handles these type requirements when working with class inheritance etc.

I think PHP handles this better in more recent releases (not sure if it was PHP 8 but likely) but as long as we support older PHP versions, I don't think this would be an option.

@lukasbestle will know more

**Comment by modufolio** [comment]
Indeed I think we should wait with this when we won't support php7.* anymore.

**Comment by lukasbestle** [comment]
Full covariance and contravariance support was added in PHP 7.4. Security support for PHP 7.3 will end on 6 Dec 2021, so the return type hints would actually be viable soon. But `static` and union types will indeed have to wait for another year.

**Comment by distantnative** [comment]
That's great.

@modufolio definitely thank you for the effort!

I think then it makes sense to split this PR:
- normal return types for end of this year
- union types and `static` for end of 2022

**Comment by modufolio** [comment]
@distantnative Understood! I will create PR's for each src folder with normal return types.

**Comment by afbora** [comment]
@modufolio So can we close this since you'll create a separate PR?

**Pull request closed without merging**
