### PR TITLE
Fix blocks options bar on nested blocks preview

### PR DESCRIPTION
**Pull request by afbora**
### Currently

screen-capture-1252-Default - Restoran-localhost

### This PR

Now it only shows the currently selected block options bar.

screen-capture-1253-Default - Restoran-localhost

### Fixed
- Now only shows the currently selected block options bar on nested blocks preview

## Breaking changes

None

## Related issues/ideas

None

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
Opened as a draft so that it would not affect 3.6.0 milestone.  The PR is ready to review.

**Comment by distantnative** [comment]
@afbora could you post the blueprint snippet for this? Was wondering if the final result should only show 1 bar, still showing 2.

**Comment by afbora** [comment]
@distantnative Showing like that?

screen-capture-1253-Default - Restoran-localhost

**Comment by afbora** [comment]
@distantnative You can test with following blueprint and [Kirby fields block preview plugin](https://github.com/jongacnik/kirby-fields-block).

````yaml
fields:    
  blocks:
    type: blocks
    fieldsets:
      test:
        name: Test
        preview: fields
        fields:
          blocks:
            type: blocks
````

**Review by distantnative — APPROVED** [review]

**Pull request merged**
