### PR TITLE
Fix failed database query with fetch closure

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- #5615

## Ready?

- [ ] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by distantnative** [comment]
@adamkiss does it work for your case when you add this check https://github.com/getkirby/kirby/pull/5639/files#diff-269fc35a258fbfc31c559ec9e4bbda254659f9007d4af68474f5663bbd9eda11R389 ?

**Comment by lukasbestle** [comment]
Doesn't this change completely disable the fetch closure if there is just one result? I think we either need to manually call the closure with the single result (if there is one) or force the `fetchAll()` mode if a fetch closure was passed as Adam suggested.

**Comment by adamkiss** [comment]
Let me test it, Nico

**Comment by adamkiss** [comment]
No, it doesn't, and it breaks in different ways (expecting array of rows, array of row data from `first()` iterates over the columns and sends wrong data to the closure)

**Comment by adamkiss** [comment]
@distantnative I thought of something more along these lines:

```php
// apply the fetch closure to all results if given
if ($options['fetch'] instanceof Closure) {
	// ↓
	// wrap a singular result in an array
	if ($options['method'] === 'fetch') {
		$results = ($results === false) ? [] : [$results];
	}
	// ↑

	foreach ($results as $key => $result) {
		$results[$key] = $options['fetch']($result, $key);
	}
}
``` 

But that doesn't respect `iterator` and always returns an array. I can't think of a more elegant code right now.

**Comment by lukasbestle** [comment]
What about something like:

```php
if ($options['fetch'] instanceof Closure) {
	if (is_iterable($results) === true) {
		foreach ($results as $key => $result) {
			$results[$key] = $options['fetch']($result, $key);
		}
	} else {
		$results = $options['fetch']($results, null);
	}
}
```

**Comment by distantnative** [comment]
Closing in favor of https://github.com/getkirby/kirby/pull/5640

**Pull request closed without merging**
