### PR TITLE
Clean up `Http` package

### PR DESCRIPTION
**Pull request by distantnative**
### Refactored
- Improvements for `Http` classes code quality

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Review by lukasbestle — DISMISSED** [review]

**Comment by bastianallgeier** [comment]
Should we still add this to 3.9?

**Comment by lukasbestle** [comment]
The new code is equivalent (only formatting changes).

**Review by afbora — DISMISSED** [review]

**Review by bastianallgeier — COMMENTED** [review]
To be honest, I'm not sure if it is a good idea to hit our search in unit tests

**Comment by afbora** [comment]
It came to my mind as a place where I can use query strings and parameters 🙈

**Comment by bastianallgeier** [comment]
The idea is good in general, but I really feel like it adds a lot of potential problems to the CI workflow.

**Review by afbora — APPROVED** [review]

**Review by lukasbestle — APPROVED** [review]

**Comment by distantnative** [comment]
I mean I won't object to include it in 3.9.0, but it's also just fine in 3.9.1

**Comment by lukasbestle** [comment]
Let's do 3.9.1 for additional safety.

**Pull request merged**
