### PR TITLE
Add edit button for structure field 

### LINKED ISSUE #5172: Structure field: sort/move items via keyboard
## Description
Hi there, great job, we love Kirby quite a lot.
We have following structure table:
```
      answerOptions:
        label: Antwortmöglichkeiten
        type: structure
        columns:
          optionImage:
            width: 1/4
          optionLabel:
            width: 1/4
          optionValue:
            width: 1/4
```
and we would like to be able to edit (and change the order of) the items without the need of using a pointer device like a mouse.

**Expected behavior**  
Either the list items should be in tab-order and the edit-dialog should open on keypress, or the 3-dot-menu should additionally to "Duplicate" and "Remove" contain the actions "Edit", "Move Up", and "Move down".

**Screenshots**  

## To reproduce

1. Login to the panel at https://trykirby.com
2. Go to panel/pages/restaurant
3. Try to edit an entry at "Starter" without using the touchpad or mouse.

## Your setup
**Kirby Version**  
3.8.2 (https://trykirby.com: 3.9.4)

**Your system (please complete the following information)**
Should be platform independent

We absolutely appreciate your efforts in maintaining Kirby as an accessible CMS-solution and therefore this hint to fix even the last problems. Thanks a lot.

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

screen-capture-1577-Test - Mægazine-localhost

What do you think also for move up and move down buttons?

### Enhancements

- Add edit button for structure field to more accessibility #5172

### Breaking changes
None

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I like it a lot and I think it would be great to also offer the sorting button options.

**Comment by afbora** [comment]
@bastianallgeier There is a small problem. `options` dropdown is row(structure)-independent and common. I cannot disable the `move-up` button for the first row and the `move-down` button for the last row. I cannot access the `rowIndex` information without clicking inside the `options` method.

https://github.com/getkirby/kirby/blob/fix/5172-edit-button-structure-field/panel/src/components/Forms/Field/StructureField.vue#L279-L308

Do you have an idea about that?

Would a non-functional move button for the first and last row be silly?

**Comment by bastianallgeier** [comment]
That's an issue I discovered in the k-table component recently as well. I didn't dare to change it in order to avoid a breaking change, but I think we really need to fix it. The event is pretty useless without the index.

**Comment by afbora** [comment]
Sorry @bastianallgeier I tried a lot but I couldn't figure out how to make the `options` prop dynamic in `k-table`. It requires advanced Vue knowledge for me 🙈 

If you want, we can make it (just move up/down feature) the subject of another PR while you're working hard on v4

**Comment by distantnative** [comment]
Yes let's not hold up the PR, this is already a nice first step

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
