### PR TITLE
File preview: fix thumb placement

### LINKED ISSUE #5603: [v4] Panel Single File View: Image preview is not centred
## Description
The preview image is not centred inside the preview area. This is happening on Safari 16.6 (latest at the moment of writing). The bug happens when the window is > 1300px and also on mobile size < 640px

**Screenshots**  
Screenshot 2023-09-09 at 3 35 08 PM

## Your setup
Kirby 4 Beta 1

**Your system (please complete the following information)**
 - OS: macOS 13.5.1
 - Browser: Safari 16.6

### LINKED ISSUE #5604: [v4] Panel Single File View: Image preview stretched
## Description
When the window is between 1065px and 1155px wide, the preview image is stretched out horizontally.

**Screenshots**  
Screenshot 2023-09-09 at 3 42 56 PM

## Your setup
Kirby 4 Beta 1

**Your system (please complete the following information)**
- OS: macOS 13.5.1
- Browser: Safari 16.6

### LINKED ISSUE #5605: [v4] Panel Single File View: file info box is cut off on mobile
## Description
The box containing the file information seems to be cut off when the panel is using the mobile view (so single column)

**Screenshots**  
Screenshot 2023-09-09 at 3 47 16 PM

## Your setup
Kirby 4 Beta 1

**Your system (please complete the following information)**
- OS: macOS 13.5.1
- Browser: Safari 16.6

### LINKED ISSUE #5606: [v4] FileView: menu glitches after resizing window (Safari)
## Description
If the window is resized horizontally and then sized up again the menu seems to reappear with an extra dark overlay. From what I can see this is only happening in the file view and not in other parts of the panel.

**Screenshots**  
https://github.com/getkirby/kirby/assets/1738077/9cbc1b37-76a4-435b-a3e4-a44da7c2c554

## Your setup
Kirby 4 Beta 1

**Your system (please complete the following information)**
- OS: macOS 13.5.1
- Browser: Safari 16.6

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

For me this fixes the following, but please double check

### Fixes
- File preview: fixed thumb placement and sizing in Safari
https://github.com/getkirby/kirby/issues/5605
https://github.com/getkirby/kirby/issues/5604
https://github.com/getkirby/kirby/issues/5603

- File view: fixed issues with the Panel menu when resizing in Safari
https://github.com/getkirby/kirby/issues/5606

### CODE REVIEW

**Comment by bastianallgeier** [comment]
The issues all seem fixed in Safari, but this PR also removes the padding around the image. Was that intended?

**Comment by distantnative** [comment]
Not that I noticed 🤔

**Comment by distantnative** [comment]
Ok seems like Chrome and Safari are fine (can't spot a difference there) - but now Firefox is acting up.

**Comment by distantnative** [comment]
@bastianallgeier I had to add another div, but now it seems to work for me in all 3 browsers.

**Comment by bastianallgeier** [comment]
It still didn't work in Safari for me until I moved the max-width and max-height to the coords. My current solution that works in all three browsers for me is this: 

```css
.k-file-preview .k-coords {
	--opacity-disabled: 1;
	cursor: crosshair;
	max-width: 100cqw;
	max-height: 100cqh;
}
.k-file-preview-thumb img {
	max-width: 100%;
	max-height: 100%;
	width: auto;
	height: auto;
}
```

**Comment by distantnative** [comment]
@bastianallgeier please add screenshots/screencasts where it doesn't work for you - otherwise it's hard to work on this when it works for me but you say it doesn't work for you without being specific what/how.

Your solution causes issues like this on my end in Safari, Chrome:

Screenshot 2023-09-13 at 20 44 34

Screenshot 2023-09-13 at 20 46 42

(differently depending on what code of my changes was included along yours or not)

**Comment by distantnative** [comment]
@bastianallgeier ping

**Comment by bastianallgeier** [comment]
Sorry for the delay. As a first step, I've rebased it after the latest changes with the new k-coords-input and the dropdown refactoring. 

I get the following result in Safari. It works fine in Firefox and Chrome though. 
Screenshot 2023-09-25 at 12 52 54

**Comment by distantnative** [comment]
Rebased with https://github.com/getkirby/kirby/pull/5700 - but I think the PR now needs a fresh rub.

**Comment by distantnative** [comment]
@bastianallgeier still can't reproduce your Safari screenshot. What version are you on?

For me in Safari:
Screenshot 2023-09-26 at 19 31 48
Screenshot 2023-09-26 at 19 31 35
Screenshot 2023-09-26 at 19 31 28
Screenshot 2023-09-26 at 19 31 18

**Comment by bastianallgeier** [comment]
I'm on Safari 16.5.2.

**Comment by bastianallgeier** [comment]
I still have the same issue, which must be related to the Safari version on Monterey. But I wonder if we should just ignore it for older Safari versions. It is after all not a terrible problem. Just a missing padding. 

Screenshot 2023-09-27 at 10 23 52

**Comment by bastianallgeier** [comment]
I'd say we merge this and then apply another fix in a different PR if we find something reliable that is not just taking care of old Safari versions.

**Pull request merged**
