### PR TITLE
Fix `plugins.js` regression

### LINKED ISSUE #1062: [Panel] Error when loading sections data (this.load is not a function)
Following the docs, calling `this.load` on `created` in a section component throws an error.

```javascript
created() {

  // Doesn't work
  // throws: this.load is not a function
  this.load().then(response => {
      this.test = response.test
  })

  // Hackish way that works
  this.$api
        .get(this.parent + "/sections/" + this.name)
        .then(response => {
            this.test = response.test
        })

}

### PR DESCRIPTION
**Pull request by distantnative**
Would be really good to get some others testing this as well

### CODE REVIEW

**Comment by MaluNoPeleke** [comment]
Any way to implement this manually on a Kirby 3.6.1 environment? The file doesn't exist there.

**Comment by distantnative** [comment]
@MaluNoPeleke It needs more testing, but if you'd be up to help with testing, you can replace the `panel/dist` files with this: 
[dist.zip](https://github.com/getkirby/kirby/files/7676436/dist.zip)

**Comment by MaluNoPeleke** [comment]
Thanks, I just did and the this.load error still exists so it doesn't seem to solve the issue yet.

**Comment by distantnative** [comment]
@MaluNoPeleke have you made sure to clear the media folder?

**Comment by MaluNoPeleke** [comment]
Thanks, I didn't think about that. After doing that it works again. Any way to do this automatically with the update from 3.6.1 to 3.6.1.1 to avoid further confusion?

**Comment by distantnative** [comment]
I think between versions it works mostly automatically, as Kirby requests Panel assets from the media folder with a hash of the version included. New version, new hash. However, we do advise to delete the media folder for updates: https://getkirby.com/docs/guide/quickstart#updates

**Comment by MaluNoPeleke** [comment]
Thanks, I will try to find out how to do this with the general composer update command (which could update other packages as well) automatically.

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Works great!

**Pull request merged**
