### PR TITLE
Replace md5/crc32 hashes

### PR DESCRIPTION
**Pull request by distantnative**
Fixes https://github.com/getkirby/backlog/issues/26

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I don't think we can solve it by just using sha256 everywhere. 

I think the hashes in file urls and paths should still be short. crc32 still seems like a good option. We just need to double-check if the hashed content could be less verbose 

The hased version should be replaced by sha256 for now but also deprecated. We need to replace our own media folder logic for the panel with hashes from vite. 

 The hashed form field signatures should be removed entirely IMHO.

**Comment by distantnative** [comment]
Ok, URLs still looked pretty ok length to me.

**Comment by lukasbestle** [comment]
We could truncate the SHA256 hashes and use e.g. the first 32 or 16 characters. The SHA spec explicitly allows this with the caveat that collision resistance is reduced. But for things that aren't security-critical like the media hashes the truncated SHA256 hash is still much more secure than CRC32.

**Comment by lukasbestle** [comment]
On the other hand changing it would be a breaking change. Given that CRC32 does exactly what we want it to in this use case, do we really need to change it? I wouldn't do it just to make automated tools happy.

**Comment by bastianallgeier** [comment]
I agree that we shouldn't do it for the machines. I think the only thing that's really worth changing/removing is the version hash.

**Pull request closed without merging**
