### PR TITLE
Fix the help text position in block and layout fields

### PR DESCRIPTION
**Pull request by bastianallgeier**
## This PR …

The most sensibel fix is to move the button over to the right if there's help text – at least in my opinion :)

Screenshot 2024-01-17 at 16 22 55

### Fixes

- https://github.com/getkirby/kirby/issues/6041

### For review team

- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
Hmmm really not sure. I don't think we'll make a lot of friends with shoving the button all to the right from being in the center.

**Comment by distantnative** [comment]
I'm gonna that the current version is probably the better one, in my opinion.

**Comment by bastianallgeier** [comment]
Yeah, you might be right. It's one of those situations were both solutions kind of suck.

**Comment by distantnative** [comment]
After all it was just me raising the question/issue about the current situation. Haven't heard much complaints from the community

**Comment by bastianallgeier** [comment]
Ok, lets close the PR and issue and if it ever comes up again, we can think about it again.

**Pull request closed without merging**
