### PR TITLE
Privacy friendly Video.vue

### PR DESCRIPTION
**Pull request by doriansimeha**
A proposition to be more GDPR compatible

### CODE REVIEW

**Comment by texnixe** [comment]
Good idea. Note that you would have to change related tests, otherwise they would fail.

**Comment by lukasbestle** [comment]
To be honest I wonder why the URLs are constructed manually in the `Video` block component since we have our very flexible embed helpers.

Idea: We could extend the [embed helpers](https://github.com/getkirby/kirby/blob/develop/panel/src/helpers/embed.js) with a new flag like `dnt` that will always enforce an embed URL without tracking when set to `true` (default would be auto-detection based on the provided URL like in the current implementation). Then the embed helper can be used in the block component without additional logic.

**Comment by texnixe** [comment]
Why not make `dnt` the default?

**Comment by lukasbestle** [comment]
The idea with the embed helpers is to auto-generate a matching embed URL for the provided video URL. We already support DNT there by using the `youtube-nocookie` domain in the video URL. So if we do it by default, users can no longer choose which behavior they want.

The disadvantage of the DNT versions is that you cannot add videos to a playlist (like the watch later playlist). This can be useful sometimes.

So while I fully agree that the blocks preview should use DNT embeds all the time, the actual embeds should be customizable IMO.

**Comment by bastianallgeier** [comment]
Thanks for your PR! I've implemented it in the way @lukasbestle suggested: https://github.com/getkirby/kirby/pull/3673

**Pull request closed without merging**
