### PR TITLE
headers option with wildcard function

### PR DESCRIPTION
**Pull request by jbeyerstedt**
As discussed in this <http://forum.getkirby.com/t/add-headers-to-the-http-response/1825> forum thread, I have added some wildcard function to the headers option of kirby.
I needed this to add some http response header to all of my pages, but I don´t want to duplicate the code for each template, eventually missing template recently added.

### CODE REVIEW

**Comment by jbeyerstedt** [comment]
There is an corresponding docs update as well: getkirby/getkirby.com#131

**Comment by bastianallgeier** [comment]
It took a while, but I rethought this and in my own projects I just add global headers to the config, which works great. You can even put it in a different config file called headers.php and require it in the main config to keep it cleaner. I think it's better to leave it this way and keep the headers option page based.

**Comment by mlbrgl** [comment]
For those following @bastianallgeier suggestion, bear in mind that your global headers will be sent on all of your site pages (including panel) which in my case was not desirable.
If you want to only send those global headers to your front-office pages (i.e. not panel):

```
if(!class_exists('Panel')){
  header(YOUR_HEADER);
}
```
Tested on Kirby 2.3.2.

(from https://forum.getkirby.com/t/check-if-it-is-panel/4435)

**Comment by janexner** [comment]
If you want to implement CSP Strict, you need to generate a nonce on each page load, then pass that both in the HTTP Content-Security-Policy header as well as a bunch of tags in the page itself. The solution suggested by @bastianallgeier does not cover that use case, I believe. (See https://csp.withgoogle.com/docs/adopting-csp.html for more)

It would be awesome to have something that calculates the nonce, puts it into the HTTP header, and makes it available in the template.

**Comment by lukasbestle** [comment]
@janexner You can generate the nonce in your `config.php` file and send the header there. You can then store the nonce as a config variable like this:

```php
c::set('csp.nonce', $nonce);
```

This variable is then automatically available to your templates.

**Pull request closed without merging**
