### PR TITLE
Enhancement: Update `ergebnis/composer-normalize`

### PR DESCRIPTION
**Pull request by localheinz**
## Describe the PR

This pull request

- [x] updates `ergebnis/composer-normalize`
- [x] runs `composer normalize`

💁‍♂️ For reference, see https://github.com/ergebnis/composer-normalize/compare/2.15.0...2.18.0.

## Release notes

n/a

## Breaking changes

n/a

## Related issues/ideas

Related to #4066.
Related to https://github.com/ergebnis/composer-normalize/issues/832.

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
I've already updated the version, please check out: https://github.com/getkirby/kirby/pull/4066

**Comment by afbora** [comment]
@localheinz I can't see `allow-plugins` in your PR. Will it still pass the test when you add it?

````json
"config": {
  "optimize-autoloader": true,
  "platform-check": false,
  "allow-plugins": {
    "getkirby/composer-installer": true
  }
},
````

**Comment by localheinz** [comment]
@afbora 

I do not think that this change is required for this pull request to pass. 

Can someone approve the workflow runs?

**Comment by afbora** [comment]
Thanks for PR 👍 We've already PR on this: https://github.com/getkirby/kirby/pull/4066

**Pull request closed without merging**
