### PR TITLE
Clean up pickers classes

### PR DESCRIPTION
**Pull request by distantnative**
## TODO
- [ ] Named parameters 

### Deprecated
- `Kirby\Cms\Picker` has been renamed to `Kirby\Panel\ModelsPicker`
- `Kirby\Cms\FilePicker` has been renamed to `Kirby\Panel\FilesPicker`
- `Kirby\Cms\PagePicker` has been renamed to `Kirby\Panel\PagesPicker`
- `Kirby\Cms\UserPicker` has been renamed to `Kirby\Panel\UsersPicker`

### Breaking changes
- `pagepicker`, `filepicker` and `userpicker` field mixins have been removed

### CODE REVIEW

**Comment by bastianallgeier** [comment]
If we break a few things here anyway, wouldn't it be a great chance to switch to named parameters instead of the array?

**Comment by distantnative** [comment]
@bastianallgeier thoughts breaking it a little is still better than breaking a lot

**Comment by distantnative** [comment]
@bastianallgeier how about we merge this as a first step (if all looks fine) and if we find the time before v4 release, we can refactor also with named props?

**Comment by distantnative** [comment]
Closing this for later

**Pull request closed without merging**
