### PR TITLE
More PHP arrow functions

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

Use more PHP arrow functions where it makes sense.

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] ~~In-code documentation (wherever needed)~~
- [x] CI checks pass

## When merging

- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~
- [x] ~~Add changes to release notes draft in Notion~~

### CODE REVIEW

**Comment by afbora** [comment]
I've seen places where many more arrow functions can be done. Especially fields. Is the reason why you didn't enter the fields something to do with automatic documentation?

**Comment by distantnative** [comment]
There are surely more, I went for the ones that made sense to me. I think it gets weird in parts where, e.g. half props would be arrow function, half props would be normal callbacks (as they do more than a simple return).

**Comment by afbora** [comment]
So let's continue with that for now.  
Btw about code formatting, my phpstorm ide suggest without space like that `fn() =>` not like yours `fn () =>`.

**Comment by bastianallgeier** [comment]
@afbora I like that `fn ()` matches `function ()` so I'd keep it this way tbh.

**Review by bastianallgeier — APPROVED** [review]
Couldn't find anything weird. I love that the test coverage increases :)

**Pull request merged**
