### PR TITLE
Refactor `k-breadcrumb`

### PR DESCRIPTION
**Pull request by distantnative**
### Deprecated
- `<k-breadcrumb>`: `view` prop will be removed in a future version. Use `root` prop instead.

## Ready?

- [x]Tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I was thinking about this as well, but do we actually really need a separate root prop? What's the advantage compared to just using crumbs for everything?

**Comment by distantnative** [comment]
guess only makes our own lives easier in Topbar.vue where we have to do the addition then. But in spirit of keeping the components more universal, I think you're right.

**Comment by bastianallgeier** [comment]
Shit. I managed to refactor the breadcrumb component some more, but now I'm stuck with the docs json breaking everything 🙈

**Comment by distantnative** [comment]
@bastianallgeier that' the pain I was talking about. You'll have to merge `v4/develop` into this branch and when the conflicts appear choose the Topbar.json version from your branch. Also best to make sure npm run dev isn't running at that time.

**Pull request merged**
