### PR TITLE
Fix disabling links in picker dialogs #3983

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

Since we currently still pass full data objects between picker dialogs and picker fields (cough, refactoring, cough), it was a bad idea to set the `link` prop to `false` for each item to disable the linking on items in the picker dialogs. The result of was that the linking was also disabled for the item in the field - as long as its data still came from the content store which received it from the picker field.

To fix it for now, this PR adds a new `link` property on `k-items` to disable linking for all items. The picker dialogs then use this prop to disable linking while preserving the `link` value for each item in their data objects.

### Fixes
- Enabling `link` in pages, files and users fields works correctly again

## Breaking changes

_None_

## Related issues/ideas

- Fixes https://github.com/getkirby/kirby/issues/3983

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] ~~In-code documentation (wherever needed)~~
- [x] CI checks pass

## When merging

- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]
That's a great addition!

**Comment by afbora** [comment]
@distantnative I don't understand what exactly this PR fixes. Has the `link` feature been removed now?

**Comment by distantnative** [comment]
No, just the broken https://github.com/getkirby/kirby/issues/3983 was fixed

**Comment by afbora** [comment]
OK this issue fixed well. So Is it an expected behavior that `link: false` is not working?

**Comment by distantnative** [comment]
I think you might be referring to a different issue I wasn't aware of. Maybe you could open an issue describing what still doesn't work? Thanks!

**Comment by afbora** [comment]
@distantnative I've created https://github.com/getkirby/kirby/issues/4062

**Pull request merged**
