### PR TITLE
Inertia: Automatic Panel dev mode

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

Allows setting the `panel.dev` option permanently to `true`. The actual dev mode will only be triggered if Vite is currently running.

If `panel.dev` is not set at all, Kirby will not check for the Vite status for best production performance.

## Release notes

None (internal change to the Inertia PR)

## Breaking changes

None

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] In-code documentation (wherever needed)
- [x] ~CI checks pass~ (Inertia not ready)

## When merging

- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~
- [x] ~Add changes to release notes draft in Notion~

### CODE REVIEW

**Comment by distantnative** [comment]
Does the file also get deleted when vite crashes/exits due to an error?

**Comment by lukasbestle** [comment]
Good point, now fixed.
I also made a change so that `npm run build` doesn't create the file.

**Comment by distantnative** [comment]
I think we need to adapt the if-statement on line 89 of `Panel.php` as well.
Currently, if I am not running dev but trying to access the Panel with just the build-files, I get the error

```
GET http://sandbox.test/media/panel/e87f0cefd7af496385034f7c7a96884d/src/index.js net::ERR_ABORTED 404 (Not Found)
GET http://sandbox.test/media/panel/e87f0cefd7af496385034f7c7a96884d/@vite/client net::ERR_ABORTED 404 (Not Found)
```

And maybe we should add some inline comments. Hasn't been very self-explanatory so far and with the additional changes, I think we should help our future self to understand all of this :)

**Comment by lukasbestle** [comment]
👍✅

**Comment by distantnative** [comment]
Does it work for you not running `npm run dev` but with build files? I always get redirects to `sandbox.test/login` (not even `/panel/login`)

**Comment by lukasbestle** [comment]
That's because the current dist files are not compatible with the Inertia backend changes. I get the same on the `feature/inertia` branch.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
