### PR TITLE
Writer toolbar: hide when no buttons

### LINKED ISSUE #6804: Writer Fields Non-inline toolbar should not show when no marks or nodes are available
## Description

**Expected behavior**  

**Screenshots**  

## Your setup
**Kirby Version**  

**Console output**  

**Your system (please complete the following information)**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Writer field: inline toolbar is hidden when no nodes and marks are available #6804

## Ready?

- [x] In-code documentation (wherever needed)
- [x] ~~Unit tests for fixed bug/feature~~
- [x] Tests and CI checks all pass

### For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Review by afbora — APPROVED** [review]
Shouldn't the target branch be `develop-minor` for 4.6.0?

**Comment by distantnative** [comment]
@afbora not necessarily. We put everything that could be released in a patch release on `develop-patch` - in that case that we would want to release a 4.5.1, we could do that right away with the necessary changes already on `develop-patch`. Since we continuously merge `develop-patch` into `develop-minor`, if we decide against any patch release, they're automatically included in the next minor release.

**Comment by bastianallgeier** [comment]
I'm totally fine to include it in the patch release, but I think we should remove the :has change in that case, right?

**Comment by distantnative** [comment]
You're right, we only started adding `:has()` back with v5.... mm but without that change it's still broken/needs additional changes in other components.

**Comment by distantnative** [comment]
@bastianallgeier I'd suggest then to move it to v5. I think it's rather complicated to fix this without `:has()` as the style is applied to `.k-writer` not the toolbar itself. I though about introducing another data attribute, but then we would have to duplicate the whole `buttons` logic from `k-writer-toolbar` in `k-writer` to make it consistent.

**Comment by bastianallgeier** [comment]
@distantnative can you fix the conflicts?

**Comment by distantnative** [comment]
@bastianallgeier done

**Pull request merged**
