### PR TITLE
Blocks: fix multi select once more

### LINKED ISSUE #5795: [v4] Color field in Blocks Fields preview doesn't work
## Description
CleanShot 2023-10-13 at 21 15 22@2x

It's not possible to click the color field in this setup. It works fine when opening the block in a drawer.
In addition to that, setting it in the drawer, and closing it, will also reset the value in the fields preview to the value it was before.

## Your setup
**Kirby Version**  4.0-beta.2
Chrome  118.0.5993.70

### LINKED ISSUE #5874: [v4] Blocks field: multiple selecting doesn't work correctly when wysiwyg enabled
I realized that multiple selecting still doesn't work correctly like before. Can't select when wysiwyg enabled. Selects works only clicking corners of the block (non-wysiwyg areas).

### Steps
1. Add multiple list blocks and fill it
2. Try to select all list blocks (clicking to editable areas that center of the list block)
3. You'll see that can't be selected

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/5858#issuecomment-1777902479_

### LINKED ISSUE #5880: [v4] Blocks field: links can't be clicked in help text with preview and wysiwyg option
## Description

````yaml
name: Test block
preview: fields
wysiwyg: true
fields:
  text:
    type: text
    help: >
        Try to <a href='https://getkirby.com/' target="_blank">Click here</a>.
````

## To reproduce

1. Create custom block with sample above blueprint
2. Add this block type to the field
3. Try to click to link in help text
4. See nothing happened

## Your setup
**Kirby Version**  
Beta.2

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- #5874
- https://github.com/getkirby/kirby/issues/5880
- https://github.com/getkirby/kirby/issues/5795

### CODE REVIEW

**Comment by distantnative** [comment]
Switching to draft again to investigate regression in regard to https://github.com/getkirby/kirby/issues/5626

**Comment by distantnative** [comment]
@afbora @bastianallgeier maybe you have an idea

https://github.com/getkirby/kirby/pull/5884/files#diff-a24a39c5335fa8b571b63d5f9c73d2a6cc66e103be4834849bd50a6f4d57934eR724

We have the issue that with nested blocks the correct CSS code to fix e.g. https://github.com/getkirby/kirby/issues/5874 will also prevent proper clicks on nested blocks as `data-multi-select-key` attribute will be applied to the blocks list on all levels, also the top-level.

**Comment by distantnative** [comment]
Might've find a solution.

@afbora would love help with extensive testing before we merge something that yet produces more regressions.

**Comment by bastianallgeier** [comment]
It works really well for me and fixes the issues. But I agree that it would be good to have another pair of eyes from @afbora :)

**Comment by afbora** [comment]
I've tested and great works for all issues 🎉 But I've found a new bug that I can't multiple select in blocks fields preview. (nested blocks with `preview: fields` and `wysiwyg: true`)

````yaml
fields:
  blocks:
    type: blocks
    fieldsets:
      test:
        name: Test
        preview: fields
        wysiwyg: true
        fields:
          blocks:
            type: blocks
````

**Comment by distantnative** [comment]
@afbora are you doing anything else than me here (as it works for me)?

https://github.com/getkirby/kirby/assets/3788865/1eaca506-0cdc-44ed-a3d4-b9900166c110

**Comment by afbora** [comment]
Could you test it with list block, please?

**Comment by distantnative** [comment]
https://github.com/getkirby/kirby/assets/3788865/542a25f7-71ab-4482-b2ff-7c2e2f73014f

**Comment by afbora** [comment]
@distantnative I've a clue. Focus parent block and try to select multiple blocks in focused block:

https://github.com/getkirby/kirby/assets/3393422/26430c8f-159a-4ed8-90df-51f7865a5d4d

**Comment by afbora** [comment]
Also different level blocks can be selectable, is this expected?

https://github.com/getkirby/kirby/assets/3393422/34cda49b-147c-4a7e-b70c-828ad9366e6d

**Comment by distantnative** [comment]
I'll look at the list one tonight.

The different level one is expected. Each blocks field has its own selection. So while the top-level one has the 2nd block selected, the nested one in the first one has its own selection. It's not one selection of the first three nested and the second top-level.

**Comment by afbora** [comment]
Also multiple block selection action button is only available for last block. If I want to select blocks randomly and have many blocks, not useful to click copy/delete button (need to be always find last selected block)

https://github.com/getkirby/kirby/assets/3393422/c2cebf4e-9f02-41ba-8a84-bcd4960c40d8

We can separate this one as enhancement if you agree.

**Comment by distantnative** [comment]
Yea that's really not related to this PR/issue.

**Comment by bastianallgeier** [comment]
Ok, I would merge this. It will be a lot easier to go from here and look at more potential issues. I also think that the multi-level selection looks good on first sight.

**Pull request merged**
