### PR TITLE
Moving pages

### PR DESCRIPTION
**Pull request by distantnative**
WIP

Would be great to tap your mind, @bastianallgeier 

https://github.com/getkirby/ideas/issues/134

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I will have a look at it later today! Thanks for starting this.

**Comment by distantnative** [comment]
I thought I'd just get your opinion, @bastianallgeier XD But looks like I triggered you to jump right in :D

**Comment by bastianallgeier** [comment]
When moving pages around the store somehow messed up and the ids contain an old id which does no longer have a matching model.

**Comment by bastianallgeier** [comment]
I'm currently working on an idea for the modal. I think I need a few more hours this morning and then we could have something that works.

**Pull request closed without merging**
