### PR TITLE
Upgrade `claviska/simpleimage`

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

Upgrading SimpleImage for PHP 8.1 compatibility.

Manual upgrade so far. We should wait for the following to be solved:
- https://github.com/claviska/SimpleImage/issues/291

### Refactoring
- Upgraded `claviska/simpleimage` dependency

## Breaking changes

None

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] ~~In-code documentation (wherever needed)~~
- [x] CI checks pass

## When merging

- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]

**Comment by lukasbestle** [comment]
@bastianallgeier We (you) need to be careful when you run `composer update` during the release preparations. The changes will probably be reverted by Composer and need to be discarded manually so that they match what has been merged with this PR.

@distantnative We also have the issue that users who use Composer to install Kirby will get the released version of the library, not our modified version. There's not really anything we can do about this I think. We could add a note in the release notes that Kirby 3.6.1 installed via Composer is not fully compatible with PHP 8.1.

**Comment by distantnative** [comment]
I'd hope that they fix the release very quickly. They responded very quickly to the initial PHP 8.1 issue.

**Comment by lukasbestle** [comment]
🤞

**Comment by bastianallgeier** [comment]
Sorry about messing it up. I got conflicts when rebasing and thought that composer update would be the best way to fix it. I have to say that I still don't fully understand lock files and all the composer dependency stuff 100%. There's still a lot of guesswork involved on my end.

**Comment by lukasbestle** [comment]
You didn't mess anything up yet. It's just something to keep in mind during the release.

**Comment by bastianallgeier** [comment]
What's the best way to work with merge conflicts in lock files then? I really don't know how they can be handled manually.

**Comment by lukasbestle** [comment]
For the lock files it's fine to run composer update and commit whatever it generates. We only need to be careful that the changes in the vendor dir don't get overwritten.

**Pull request merged**
