### PR TITLE
Fix file models #1954

### LINKED ISSUE #1954: File models are not working as expected.
File models have the same problem that user models had:  https://github.com/getkirby/kirby/issues/1892

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
File models should work now

@texnixe and @afbora could you please check if this one-liner solves your issues? Thanks

## Related issues
- Fixes #1954

## Todos
- [x] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [x] Fix code style issues with CS fixer and `composer fix`

### CODE REVIEW

**Comment by texnixe** [comment]
@distantnative Hm, I still can't get it to work. Maybe I'm not using it the right way, but my file is still a Kirby\Cms\File and my model method is still treated as a field and returns nothing.

**Comment by afbora** [comment]
@distantnative I missed your request yesterday, sorry for that. 

I have tested fix branch now and didnt work for me too. 
I'm trying to figure out where the issue comes from.

**Comment by afbora** [comment]
@distantnative I guess issue with `template` data not set yet.

`$props['model'] = $props['model'] ?? $props['template'] ?? null;`

**abba.jpg.txt**

```
Caption: 

----

Alt: A colorful fish

----

Photographer: Pietro Jeng

----

License: Unsplash

----

Link: https://unsplash.com/photos/0Sd2qqU5soQ

----

Template: image

----

Sort: 4
```

Image have template data but not seen `template` index in `$props` data.

I have tested with manual set to `image` instead of `$props['template']` and works:

`$props['model'] = $props['model'] ?? "image" ?? null;`

**Comment by distantnative** [comment]
Nargh, I thought his was an easy one to do, I was wrong.

@bastianallgeier and @lukasbestle:
I think to actually make this work `Dir::inventory()` would need to open each file content file and check for the template. This could have quite some performance implications. What are your thoughts?

We already read the user file for the user model, but I felt that for users the performance implication might be alright. For files I have my doubts.

**Comment by lukasbestle** [comment]
Not sure about that either. Maybe we could lazy-load the model object in place of the generic file object once the content file is opened anyway, but that's probably too unpredictable and would lead to all sorts of unexpected bugs.

**Comment by bastianallgeier** [comment]
We have a similar issue with Page models. Loading them also means sacrificing a bit of performance. I think with files the issue is even worse though. Maybe we need to roll this feature back for now until we can implement it properly.

**Comment by texnixe** [comment]
I'll make a note to remove it from the docs for the time being.

**Comment by distantnative** [comment]
Yes, might be best to remove file models again. I think for users it's feasible or what do you think?

**Comment by bastianallgeier** [comment]
Yes, I think so too.

**Pull request closed without merging**
