### PR TITLE
`Structure` to extend `Item` classes

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

- Align the structure classes to be built on top of `Cms\Item`, same as blocks, layouts etc.
- I think this will help to have consistent support for UUIDs for blocks and structure objects

### Feature
- Custom methods for structure and structure object

### Refactored
- `Kirby\Cms\Structure` extends `Kirby\Cms\Items` and `Kirby\Cms\StructureObject` extends `Kirby\Cms\Item`

### Breaking changes
- `new Structure()`/`new StructureObject()` don't work anymore as before. Use `Structure::factory()`/`StructureObject::factory()` instead
- Structure object IDs aren't simply their collection index numbers anymore but receive a `Str::uuid()` as blocks do
- `Items::factory()` and all inheriting classes throw an exception now if malformed data is passed

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]
I like this a lot. Do we want to put this in alpha 4?

**Comment by iskrisis** [comment]
Not sure this is intended or in development. But @distantnative it seems that the ids are not persisted.

**Comment by nilshoerrmann** [comment]
> Kirby\Cms\Structure extends Kirby\Cms\Items and Kirby\Cms\StructureObject extends Kirby\Cms\Item

Would it make sense to rename `StructureObject` to `StructureItem`?

**Comment by distantnative** [comment]
@nilshoerrmann we were trying to stay away from those kind of breaking changes for now

**Comment by nilshoerrmann** [comment]
Totally understandable. I just wanted to ask because `StructureObject` always sounded strange in context of other names within Kirby (page/pages, file/files, user/users, but not structures/structure). But never mind :)

**Comment by iskrisis** [comment]
Sorry to interrupt the conversation but coming back to the initial question... should i file issue about structures not persisting ids like blocks do? or is it something you all know about.

**Comment by distantnative** [comment]
I'm rather undecided. It's already in the breaking changes section and structure objects also didn't have a persistent id before, did they?

**Comment by iskrisis** [comment]
In v3 the ids are indexOf and thus kinda persistent. I found out about this by helping user on Discord who was updating his site to v4. 
I have not tested this but i think he was using structureObject->id() in v3 as value in select fields. Since id() was index before it was working but now it was confusing for him because the id() was changing all the time.

I understand this is something thats moving so maybe its OK.

**Comment by distantnative** [comment]
Hmmm I see. Could you maybe open an issue (I'm on my phone) so we don't forget? Wasn't a persistent issue either when being moved but I can see the use case where it's at least persistent as long as touched.

**Pull request merged**
