### PR TITLE
Simplify some null assignments

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Review by bastianallgeier — COMMENTED** [review]
LGTM but wouldn't it be better to do this in 3.9.x and merge it from there?

**Comment by distantnative** [comment]
I can try if I can cherry-pick this. I started from our `v4/main` branch (or rather the lab branch a while ago)

**Comment by distantnative** [comment]
Done

**Review by afbora — APPROVED** [review]
LGTM 👍

**Pull request merged**
