### PR TITLE
Panel: more shortcuts for search

### PR DESCRIPTION
**Pull request by distantnative**
### Enhancements
- Panel search now also opens on `Cmd+K` and `Cmd+/` in addition to `Cmd+Shift+F` (`Ctrl` on Windows)
https://kirby.nolt.io/511

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by afbora** [comment]
- ✅ CTRL + /  
- ✅ CTRL + Shift + F  
- ✅ CTRL + K  

Working great on windows but a little issue happening. When using `CTRL + K`, also browser search enabling and conflicts, here screencast:

https://user-images.githubusercontent.com/3393422/221522681-05a4cf2a-9390-4b5d-b982-8ce87c1e2ada.mp4

**Comment by bastianallgeier** [comment]
@afbora I think we should leave it like that. It wouldn't feel right to me to block the default behaviour. What do you think? /cc @distantnative

**Comment by afbora** [comment]
Yes, I agree with Bastian. Our use of browsers default shortcuts doesn't sound very functional and correct. If no browser is using `CTRL/CMD + /` can stay.

**Comment by distantnative** [comment]
The thing is Cmd+k was the one actually requested. So we would need to split it up, support only that one on Mac while not adding ctrl+k on windows?

**Comment by afbora** [comment]
It doesn't make sense not to apply it to one and apply it to the other. There are two options:
- Assign the same key in Windows and MacOS
- Assigning different keys in Windows and MacOS

If possible, I would be in favor of the first option.

**Comment by distantnative** [comment]
I would also say that we should have the same between both OS.... but then we cannot do `Cmd+K` at all :/

**Comment by afbora** [comment]
@distantnative I've tested `CTRL + K` on notion web app, works great without conflicting. I think, notion overwrite/prevent browser shortcut. You should take a look.

**Comment by afbora** [comment]
I've tested following changes and seems works great, what do you think?

```diff
- open() {
+ open(e) {
+  e.preventDefault();
   this.$refs.overlay.open();
},
````
https://github.com/getkirby/kirby/blob/fix/panel-search-keyshortcut/panel/src/components/Navigation/Search.vue#L166-L168

**Comment by distantnative** [comment]
@afbora does this work for you?

**Review by afbora — APPROVED** [review]

**Comment by distantnative** [comment]
I think this one would be safe enough to still include in 3.9.2

**Review by lukasbestle — COMMENTED** [review]
I haven't been able to test it myself, but if it works I think it's a great addition.
👍 on 3.9.2.

**Pull request merged**
