### PR TITLE
Bundle lightweight inertia

### PR DESCRIPTION
**Pull request by distantnative**
- Bundles a super-reduced Inertia library clone (instead using `node_modules`)
- Fixes the back button issue

## Benchmark

**`develop` branch**
```
dist/css/index.css   93.94kb / brotli: 13.85kb
dist/js/index.js     360.09kb / brotli: 65.87kb
dist/js/vendor.js    407.78kb / brotli: 110.02kb
```

**`intertia` PR**
```
dist/css/style.css   94.01kb / brotli: 13.89kb
dist/js/index.js     344.08kb / brotli: 62.65kb
dist/js/vendor.js    478.65kb / brotli: 129.84kb
```

**this PR**
```
dist/css/style.css   94.01kb / brotli: 13.89kb
dist/js/index.js     347.12kb / brotli: 63.48kb
dist/js/vendor.js    407.46kb / brotli: 111.32kb
```

### CODE REVIEW

**Comment by afbora** [comment]
`lock` requests still throw error like in other inertia branch:

````
code: 400
details: []
exception: "Kirby\\Exception\\InvalidArgumentException"
file: "/test/kirby/mini-inertia/kirby/src/Cms/Api.php"
key: "error.invalidArgument"
line: 142
message: "Invalid model type: kirby/mini-inertia/panel/pages"
route: "(.*)/lock"
status: "error"
__proto__: Object
````

**Comment by afbora** [comment]
- lock issues still continue even if i disabled the `content.locking` option
- account view opens white screen
- back button working great now 🎉

**Comment by distantnative** [comment]
Just fixed the account view on the main Inertia branch.
Will also work on content locking on the main Inertia branch.

**Comment by distantnative** [comment]
Merged manually

**Pull request closed without merging**
