### PR TITLE
Add `k-options-dropdown`

### PR DESCRIPTION
**Pull request by distantnative**
## Status: ready for review 👀

- If only one option is passed, show simple button
- If multiple options are passed show button with dropdown

In preparation to #3397 

### Features
- Added `k-options-dropdown` component

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
Tbh, looking this morning at it, I think this can be cleaned up a bit more to make it easier to understand.

**Comment by bastianallgeier** [comment]
@distantnative what would you do to simplify it? Maybe break it down into sub-components?

**Comment by distantnative** [comment]
Like this?

**Comment by distantnative** [comment]
Arg sorry, broke the files field logic (missing if check). Will fix later.

**Review by bastianallgeier — APPROVED** [review]
LGTM!

**Pull request merged**
