### PR TITLE
Fix `$collection->group()` for case-sensitive

### LINKED ISSUE #5628: Collection->group() throws error with $i set to false
## Description
When grouping a collection, the key is by default lower-cases. This is not always useful. Theoretically, I should be able to pass a $i = false as second argument  to prevent lowercasing, but then the method breaks, because then $value is not a string. So 

```
// ignore upper/lowercase for group names

$value = $i ? Str::lower($value) : $value->value();
```
would fix this.

**Expected behavior**  
Method should work with $i set to false

## To reproduce
Try to group a collection by a key, passing `false` as a second argument:

```
$grouped = $page->children()->groupBy('category', false);
```

Error: Illegal offset type in isset or empty in Kirby\Cms\Collection #174

## Your setup
**Kirby Version**  
Kirby 3.9.6.1

https://forum.getkirby.com/t/groupby-kills-the-spelling-of-the-grouped-by-field/29439/2?u=texnixe

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Fix `$collection->group()` for case-sensitive
#5628

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by afbora** [comment]
Why is the parameter name `$i`?. I spent a while trying to figure out what `$i` is for. How about a better variable name?

**Comment by lukasbestle** [comment]
What about `$ignoreCase`? It would be a breaking change with PHP named params, but I agree it would be very worth it.

**Comment by afbora** [comment]
Or may be `bool $caseSensitive = false`

**Comment by distantnative** [comment]
@afbora But then it wouldn't be just a breaking change of the parameter name but all existing calls would do exactly the opposite of what they did before

**Comment by distantnative** [comment]
It gets even messier. `Collection` has a `$caseSensitive` class prop.  Though this seems to be only used in one test. I am wondering if we should deprecate that to get a bit more clarity.

On the parameter name, I'd go with `$caseInsensitive` as that's used throughout the `Str` class.

**Comment by distantnative** [comment]
Ok, revert... if we rename this parameter, this fix can't be in 3.9.7.

I suggest we merge the fix without the renamed parameter and rename the parameter for v4: https://github.com/getkirby/kirby/pull/5634

**Review by lukasbestle — APPROVED** [review]

**Comment by lukasbestle** [comment]
> `Collection` has a `$caseSensitive` class prop. Though this seems to be only used in one test. I am wondering if we should deprecate that to get a bit more clarity.

We introduced that not too long ago, I use that in the Versions plugin.

**Pull request merged**
