### PR TITLE
Page/file sort dialog

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

Adds a "change position" dialog to the options dropdown of pages and files sections (not page/file view though). The dialog reuses the select from the existing PageStatusDialog.

Screen Shot 2020-10-16 at 19 17 22

Screen Shot 2020-10-16 at 19 17 31

Screen Shot 2020-10-16 at 19 26 48

Screen Shot 2020-10-16 at 19 26 53

## Related issues

- Implements #1663

### CODE REVIEW

**Comment by distantnative** [comment]
Though I just had the idea, if a move page/file dialog could solve this too:
The move dialog would be a pages field (to select the parent page) + position select (if sortable/if sorted by num).
It would open with the current parent and position preselected.

So if one would just want to resort it, they would only change the position and leave the parent unchanged.
But maybe this PR is a first step and this new idea could extend/replace it in 3.6, 3.7 ...

**Review by afbora — COMMENTED** [review]
When set `sortable: false` from section, `Change position` disabled as expected in three dots menu. But position dropdown is still appears and works in `Select a new status` dialog. Is this bug or related with this PR?

**Comment by distantnative** [comment]
@afbora that sounds like it could be a bug already in Kirby, not new with this PR.

**Comment by afbora** [comment]
Yes I tested it now, this issue already existed (https://github.com/getkirby/kirby/issues/2901). So PR looks great 👍

**Review by bastianallgeier — APPROVED** [review]

**Comment by nilshoerrmann** [comment]
This looks great and will be very helpful. Thanks 👍

**Comment by johannahoerrmann** [comment]
Fantastic! This will help a lot.

**Pull request merged**
