### PR TITLE
Support for returning Response obj from API route

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

It is now possible to return a completely custom `Response` object from custom API routes. This enables custom HTTP status codes, headers and response bodies.

## Related issues

Implements #2076.

## Todos

- [x] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [x] Fix code style issues with CS fixer and `composer fix`
- [x] If needed, in-code documentation (DocBlocks etc.)

### CODE REVIEW

**Review by bastianallgeier — CHANGES_REQUESTED** [review]
I think this will clash in the Api::render() method. We don't handle Response objects there.

**Comment by distantnative** [comment]
@bastianallgeier Would have thought that `Api::render` does with these lines: https://github.com/getkirby/kirby/blob/0e682d5045e91ddbea109d0fb1a64416c566d973/src/Api/Api.php#L554-L556

**Comment by lukasbestle** [comment]
Yep, I have tested it and it works perfectly. :)

**Comment by bastianallgeier** [comment]
@distantnative ha, I completely missed that line. Of course it should work. Awesome!

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
