### PR TITLE
New date comparison validator, new date collection filters, alias `..` for the `between` filter

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

There are now date-specific collection filters that can be used like this:

```php
$collection->filterBy('date', 'date >=', 'today');
```

The advantage of these filters is that all date formats that can be parsed by PHP are supported (both in the fields and in the test string).

The added filters are:

- `date ==`
- `date !=`
- `date >`
- `date >=`
- `date <`
- `date <=`
- `date between` (or `date ..`)

## Related issues

- Implements https://github.com/getkirby/ideas/issues/563

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
I love this feature ❤️ 

I just wonder that do we need to check the string? For ex:

````php
$date1 = strtotime('today');
$date2 = strtotime('wrong_string'); // return false, so it's zero

var_dump($date1 >= $date2); // return true
````

**Comment by lukasbestle** [comment]
@afbora Thanks, you are completely right! Fixed. 👍

**Comment by distantnative** [comment]
Wondering whether we could DRY the code a bit and maybe move that part to the `V` class.

**Comment by nilshoerrmann** [comment]
May I suggest an additional range filter which checks if a date is within an given range?

    $pages->filterBy("date", "date ..", ["-1 month", "tomorrow"])

**Comment by nilshoerrmann** [comment]
Could also be interesting for numeric fields as ".." (without the `date` prefix).

**Comment by distantnative** [comment]
@nilshoerrmann For numeric fields this already exists with the keyword `between` instead of `..` - but I would like this as an alias.

I have added a PR to this PR which moves some of the logic to the `V` class to have it consistent with other collection filters. And it also adds a `date between`/`date ..` filter.

https://github.com/getkirby/kirby/pull/2650

**Comment by nilshoerrmann** [comment]
@lukasbestle & @distantnative Thanks for all these quick additions!

**Comment by bastianallgeier** [comment]
@lukasbestle I'm a bit confused. What is the difference between this and the other PR?

**Comment by lukasbestle** [comment]
This was the original PR and @distantnative made improvements to it in the other one, which merged back to this PR.

**Review by bastianallgeier — APPROVED** [review]

**Comment by nilshoerrmann** [comment]
Thanks everyone for this quick enhancement!

**Pull request merged**
