### PR TITLE
primaryKey for pages, files, users picker fields

### PR DESCRIPTION
**Pull request by afbora**
### WIP PR

I have implemented dynamic primary key option as `primaryKey` for pickers (pages, files and users field). Please can you share your thoughts? @getkirby/kirby-staff 

### Sample Usage

**Pages field**

````yaml
fields:
  related:
    type: pages
    primaryKey: autoId
````

**Users field**

````yaml
fields:
  author:
    type: users
    primaryKey: username
````

**Files field**

````yaml
fields:
  cover:
    type: files
    primaryKey: hashNumber
````

## Related issues

- Closes https://github.com/getkirby/ideas/issues/193

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
As the first attempt, the `Panel UI` part was successful, but in the next step, I couldn't complete the PR because the `Kirby\Cms\Field` class didn't hold `primaryKey` field data like other field options except `value` (to use for `toPages()`, `toUsers()`, `toFiles()` methods). 

The `Kirby\Cms\Field` class is unaware of the field options. Perhaps we can solve this feature at the blueprint level of collections not with field options.

Something like that `pages/note.yml`:

````yaml
title: Note
num: date
primaryKey: autoId
````

**Comment by dev-ofty** [comment]
Is this feature implemented in the latest Kirby version?

**Comment by afbora** [comment]
Unfortunately not yet.

**Comment by dev-ofty** [comment]
Thanks for the quick reply. I will try to work with the hook and hidden field for that then. Hopefully it will be implemented within the next release. Fingers crossed!

**Pull request closed without merging**
