### PR TITLE
Fixes tabs badge position

### LINKED ISSUE #3822: Tab in front of k-tabs-badge
**Describe the bug**  
If tab A has a badge and tab B is clicked, tab B will be in front of the badge.

**To Reproduce**  
1. Click on a page with tabs
2. Edit some text so the unsaved badge appears
3. Click on a different tab

**Expected behavior**  
The badge shouldn't be blocked by the other tab.

**Screenshots**  
image

**Kirby Version**  
3.6.0-rc.1

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Designed by measuring every pixel for @medienbaecker 😅 

Top/Right/Padding values have been adjusted for cases with long tab labels.

screen-capture-1214-Test - Mægazine-localhost

### Fixes regressions from 3.6.0-rc.1

- Fixed tabs badge position #3822

## Breaking changes

None

## Related issues/ideas

- Fixes #3822

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
I find this a bit too tight compared to all other visual elements. I think the padding could remain `.325rem` and the offset to the right should be still `.5rem`

**Comment by afbora** [comment]
@distantnative Preview of `inset-inline-end: .5rem;`

screen-capture-1215-Test - Mægazine-localhost

**Comment by distantnative** [comment]
Ok but that's an issue we would need to deal with the other version too, right? I'd think the PR faces the same problem if you change the label to end with `webs` not `web`?

**Comment by afbora** [comment]
No, I already adjusted this PR for the edges cases:

screen-capture-1217-Test - Mægazine-localhost

**Comment by afbora** [comment]
I know it's very tight, but I think we have two options. Narrowing the text area a little more or placing the badge in the narrow area.

**Comment by afbora** [comment]
I have a third idea but I'm not sure: `tab icon area`; If there is a change, the badge will appear instead of the tab icon. What do you think?

screen-capture-1218-Test - Mægazine-localhost

**Comment by bastianallgeier** [comment]
Uhh, I love the third idea!! I think that's a great solution and looks much better than the rest.

**Comment by nilshoerrmann** [comment]
Have you thought about just adding a small colored dot to the icon, like an app notification (not sure if it actually needs a distinct count)? Hiding the icon might be confusing to clients who need these visual clues to find the right tab.

**Comment by bastianallgeier** [comment]
That would work well too if all tabs had icons 🙈

**Comment by nilshoerrmann** [comment]
Ah, damn, I totally missed that fact!

**Comment by afbora** [comment]
@bastianallgeier Could it be confusing to hide icons (replace with counter) on changes like @nilshoerrmann said? How will we proceed?

**Comment by bastianallgeier** [comment]
This is turning into a quite complex task for a rather simple UI elements 🙈🤣

I start to wonder if we should go back to simple numbers and make sure they stay in line with the text and break accordingly.

**Comment by distantnative** [comment]
I would love if tab badges still could have a count, also for custom implementations of the tabs component.

**Comment by afbora** [comment]
## Last shots 😅 

I think both seems cool.

### Alternative 1
screen-capture-1221-Test - Mægazine-localhost

### Alternative 2
screen-capture-1220-Test - Mægazine-localhost

**Comment by bastianallgeier** [comment]
@afbora I like alternative 2

**Comment by afbora** [comment]
@bastianallgeier Done for alt 2

screen-capture-1224-Test - Mægazine-localhost

**Comment by distantnative** [comment]
Mmm to me it looks odd that it's slightly lifted from the normal text line

**Comment by bastianallgeier** [comment]
I think the position is really good now. I just made the badges a tiny bit smaller and went for 10px as font size. That's super small, but after all it's just a very tiny visual hint for changes. I also moved the badge a tiny bit closer into the corner. This does no longer mess with the visual alignment of the text. I reduced the border radius a tiny bit as well to make it fit better into the corner and also added a subtle shadow to make the orange stand out a bit better against the background. 

Screenshot 2021-10-27 at 10 03 24

I'm pretty happy with it now. What do you think?

**Comment by bastianallgeier** [comment]
I just saw small glitch in the form bar. I fixed it here to avoid yet another PR for such a small change.

**Comment by distantnative** [comment]
I think it looks super squeezed and odd but that's personal taste. We can go with it. Maybe the drop shadow on it doesn't make sense with this positioning?

**Comment by bastianallgeier** [comment]
I think the main prio for rc.2 is to fix the bug. I personally like the position now and don't think it looks too squeezed. The drop shadow also makes it more badgy in my eyes. But I'm super happy about more suggestions later. It's definitely not my most favourite UI element in the Panel :)

**Pull request merged**
