### PR TITLE
Upgrade `phpmailer`

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Review by lukasbestle — APPROVED** [review]

**Comment by lukasbestle** [comment]
Have you checked that all of our dependencies officially support PHP 8.1?

**Comment by afbora** [comment]
Unmaintained repos technically work and support PHP 8.1. 

- michelf/php-smartypants
- mustangostang/spyc

Others seem to have official PHP 8.1 support.

**Comment by distantnative** [comment]
What about whooops? According to packagist it might only support 8.0 officially: https://packagist.org/packages/filp/whoops

**Comment by afbora** [comment]
@distantnative Check out 2.14.3
https://github.com/filp/whoops/blob/master/CHANGELOG.md

**Comment by afbora** [comment]
Also `^8.0` mean `8.x`?

**Comment by distantnative** [comment]
ah right, composer version syntax still confuses me again and again. but makes sense, I thought I had seen that whoops supports it.

**Pull request merged**
