### PR TITLE
Add undefined class properties

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by afbora** [comment]
Can you take a look following classes?
 - src/Form/Field/BlocksField.php `$this->pretty, $this->group`
 -  src/Cms/Fieldset.php `$this->kirby`

**Comment by distantnative** [comment]
@afbora I only took care of the classes I understood quickly. I think there's even more out there. But let's take them one at a time :D

**Comment by afbora** [comment]
I got it, I can push a few if you want 👍

**Comment by distantnative** [comment]
Sure feel free!

**Review by bastianallgeier — DISMISSED** [review]

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
