### PR TITLE
Translatable range tooltip

### PR DESCRIPTION
**Pull request by afbora**
### Enhancements
- Translatable range tooltip #6221

### Breaking changes
None

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and checks all pass

### For review team

- [x] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]
Nice!

**Comment by distantnative** [comment]
@afboa @bastianallgeier I am wondering if such changes shouldn't rather go into `develop-minor`. I think we should treat patches really more like patching regressions and almost anything that could have side effects is better in a minor version because that has at least a RC period. What do you think?

**Comment by bastianallgeier** [comment]
I thought about that as well and I think I agree

**Comment by bastianallgeier** [comment]
Yikes, I merged it into the wrong branch. Damn it.

**Comment by bastianallgeier** [comment]
Ok, I fixed it manually and cherry picked the commit on develop-minor

**Pull request merged**
