### PR TITLE
Toolbar: fix btn not clickable in Safari

### LINKED ISSUE #5399: [v4] Blocks options not clickable when multiple selected in Safari
## Description
While testing the v4 I noticed in Safari the block merge feature doesn't seem to work. Block splitting does work but merging doesn't. Tested Brave as well and it work as expected there.

**Expected behavior**  
The expectation was that it would join two text blocks shown in the video.

**Video**  
https://share.cleanshot.com/GLP1LCxw7V4Bnctphff1

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: MacOS 13.3.1
 - Browser: Safari
 - Version: 16.4

### LINKED ISSUE #5442: [v4] nodes in writer field not accessible in Safari
## Description
The writer fields inline toolbar disappears when clicking on the node dropdown.

**Expected behavior**  
The node dropdown options should open instead of closing the toolbar.

**Screenshots**  
Bildschirmaufnahme-2023-08-02-um-10 19 31

## To reproduce
1. Open Safari
2. Open a page containing a writer field with inline toolbar in panel
3. Select a text
4. Try to change the node type

## Setup
 - Kirby: 4.0.0-alpha.5 and 4.0.0-alpha.6
 - Device: MacBook Pro (13-inch, 2017)
 - OS: macOS 13.5 (22G74)
 - Browser: Safari
 - Version: 16.6 (18615.3.12.11.2)

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- https://github.com/getkirby/kirby/issues/5442
- https://github.com/getkirby/kirby/issues/5399

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Unfortunately, this does not solve the problems for me in Safari 16.5.2

**Comment by distantnative** [comment]
In Safari 17.2 it does so might be still worth not discarding this fix as it partially then help at least. I'd have to hand over fixing for Safari 16.x to you as I can't test it.

**Comment by bastianallgeier** [comment]
This stuff is so weird. If I add a mousedown.stop to the toolbar buttons, it works for me partially. It seems like the event order is somehow messed up on Safari and the mousedown does already trigger something further up to close the toolbar again. But that still does not solve the dropdowns then. I wonder if we should fix this at all for older Safaris or just rely on updates. It's obviously a rather nasty Safari issue after all.

**Comment by distantnative** [comment]
I mean the problem is a bit that there's probably still quite a bunch of Safari 16 out there and it really affects the usability for them :/

**Comment by bastianallgeier** [comment]
Yes, definitely. I also cannot upgrade at the moment because I'm still on an older OS version.

**Comment by bastianallgeier** [comment]
Ok, I think I solved it in a way that should work for all browsers. But it would be good to have a few more tests.

**Comment by distantnative** [comment]
@bastianallgeier seeing that your changes only concern the Writer field, does https://github.com/getkirby/kirby/pull/5887/files#diff-9cc2332bf188c695fcdd8b8e50633fe6e232322b020babd71492536e2038d662R14 fix the toolbar issue for you in Safari for e.g. block options dropdown already?

**Comment by bastianallgeier** [comment]
No it doesn't. I need to look at that one as well.

**Comment by bastianallgeier** [comment]
Ok, preventing the mousedown event in the block option toolbar does the trick.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
