### PR TITLE
Nested dialogs

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by distantnative** [comment]
@bastianallgeier on second thoughts, should we move this to 4.1 or 4.2?

**Comment by bastianallgeier** [comment]
@distantnative it seems like a pretty big change for the beta. Do you think we can still offer this without a breaking change later though?

**Comment by distantnative** [comment]
@bastianallgeier looking at the code, I don't see a breaking change. So 4.1, 4.2 would be fine IMO

**Comment by distantnative** [comment]
Will open this again when the time is right

**Pull request closed without merging**
