### PR TITLE
Remaining PHP CS fixes

### PR DESCRIPTION
**Pull request by lukasbestle**
I have again verified that the changes are correct and applied manual fixes where necessarily.

For better overview, this PR has two commits where one CS fixer option was enabled each.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Sorry! I saw this too late. Let's add it in 3.3.0

**Comment by lukasbestle** [comment]
@bastianallgeier No problem. Could you please update the `develop` branch with the changes from 3.2.5 and then merge this PR right away? It‘s best to get this into `develop` as soon as possible to avoid merge conflicts.

**Comment by bastianallgeier** [comment]
Urgh, I just updated develop. Did I do something wrong again? Why are all the other commits listed here?

**Comment by lukasbestle** [comment]
Now they are gone again. Maybe GitHub needed some time to catch up.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
