### PR TITLE
CSS logical properties fort RTL support

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

While https://caniuse.com/css-logical-props and https://caniuse.com/css-dir-pseudo aren't fully supported widespread, I think it would be good that we start using CSS Logical Properties. They are the way forward and already help to keep our code shorter and easier to overlook. Two posts plugins can help us supporting older browsers for the time being. The impact on CSS size is minimal and mainly due to still keeping the logical definition around in our diet file, alongside the compiled fallbacks.

**Before PR**
Screen Shot 2021-05-08 at 11 07 50

**After PR**
Screen Shot 2021-05-08 at 11 17 44

## Breaking changes

None

## Related issues/ideas

- Closes #https://github.com/getkirby/kirby/issues/3195

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] ~~In-code documentation (wherever needed)~~
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Oh wow, the syntax for this is sooooo nice!

**Comment by distantnative** [comment]
Shall we do it, @bastianallgeier ?

**Comment by lukasbestle** [comment]
I agree that these properties are definitely the way forward, so it makes a lot of sense to start using them. The impact on the CSS file size is really negligible at 150 bytes compressed.

**Comment by bastianallgeier** [comment]
Yes, let's move forward with this!

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
