### PR TITLE
Add border property to QrCode

### PR DESCRIPTION
**Pull request by rasteiner**
## This PR …

Adds an option to the QrCode class which allows a user to specify the size of the quiet zone (aka "border", aka "padding") around the code. This makes it easier to visually align an embedded code when its container (and sibling elements) already have sufficient padding. 

### Breaking changes
None

## Docs

```html+php

<div class="p-4">
    <h2><?= $name ?></h2>
    <?php
        $vCard = <<<VCARD
        BEGIN:VCARD
        VERSION:4.0
        FN:$name
        EMAIL;TYPE=work:$email
        TEL;TYPE=work:$tel
        END:VCARD
        VCARD;
        
        $qr = new QrCode($vCard);
        $qr->border(0);
        echo $qr->toSvg();
    ?>
</div>
```

## Ready?

- [x] In-code documentation (wherever needed)
- [ ] Unit tests for fixed bug/feature
- [ ] Tests and checks all pass

### For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [ ] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
I'm not too happy with a separate method for this. All other customizations (size and colors) are arguments to the output methods. With named arguments, I think it isn't too bad to add more arguments there.

@distantnative What do you think?

**Comment by distantnative** [comment]
Was thinking along the same lines: should be more consistent with the other arguments. But I can change it over the weekend.

**Comment by distantnative** [comment]
https://github.com/getkirby/kirby/pull/6445

**Comment by rasteiner** [comment]
Thanks :) 

My goal was to make this PR as non-intrusive as possible (i.e. not changing any existing function signatures).

**Pull request closed without merging**
