### PR TITLE
Consistent use of `k-collection`, new `k-models-section`

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

In preparation of table layout, it's important to make the usage of `k-collection` more consistent as well as to unify pages and files sections with a new `k-models-section` that these extend.

### Enhancements
- `k-collection` supports empty state via `empty` props (passing text and icon keys)

### Refactoring
- New internal `k-models-section`
- Refactor `k-pages-section` and `k-files-section` to use (extend) `k-models-section`

### Breaking changes
- `k-pages-section` and `k-files-section` have been modified extensively

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Review by bastianallgeier — COMMENTED** [review]
For some reason the pickers are broken for me but I cannot really figure out why.

**Comment by distantnative** [comment]
I'll have a look later

**Comment by distantnative** [comment]
@bastianallgeier can you tell how the pickers are broken for you? Randomly using them but not running into issues myself

**Comment by bastianallgeier** [comment]
@distantnative I think I found all the issues.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
