### PR TITLE
Set API locale using a new key in the translation file #2233

### LINKED ISSUE #2185: toDate in blueprints using strftime breaks panel requests
**Describe the bug**  
Using toDate in blueprints with `date.handler` option set to `strftime` breaks requests response in the Panel, it throws `The JSON response from the API could not be parsed. Please check your API connection.`

**To Reproduce**  
- Set the Kirby option `data.handler` to `strftime`
- Create a `blog` blueprint using toDate, for example:
```yaml
title: Blog

sections:
  published:
    headline: Published articles
    type: pages
    status: listed
    templates: article
    sortBy: date desc
    info: "{{ page.date.toDate('%d %B %G') }}"
```
- Create an `article` blueprint:
```yaml
title: Article
preset: page

fields:
  date:
    icon: calendar
    label:
      en: Date
      fr: Date
    type: date
    placeholder: Select a date…
    default: today
    required: true
    width: 1/3
    translate: false
```
- In the panel create a page of type `blog` and at least one published `article` page
- Go to the `blog` page
- The page throws `The JSON response from the API could not be parsed. Please check your API connection.` under the `published` section

**Expected behavior**  
The panel page should properly list the published articles with the date displayed in the `info` field

**Kirby Version**  
3.2.5

**Desktop:**  
 - OS: macOS
 - Browser: Firefox
 - Version: 69.0.2

**Additional context**  
The fetch request to grab the articles in the Panel returns an empty response with code 200. I don't have any error in my logs.

The problem doesn't occur in my local setup but does on the remote server. Could it be a difference in the server configuration? Both are using Apache and PHP 7.3

This is similar to https://forum.getkirby.com/t/i-dont-see-my-blogposts-via-the-panel/12968/20?u=leben but in my case using the `date` format just outputs `Y.m.d` as is; it does prevent the error though. Could it be caused by the `%` in the strftime format?

### LINKED ISSUE #2233: Setting API locale does not work for many locales
This https://github.com/getkirby/kirby/blob/master/src/Api/Api.php#L178-L199 does not work for locales without `_` where the first and second part are not equal, e.g. `en_US` from `en`.

Maybe we should add something like:
https://github.com/peterkahl/country-to-locale

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

The API locale was generated dynamically, which failed for some languages. The locale is now set in the translation file, so it can be customized for each translation.

## Related issues

- Fixes #2233
- Fixes #2185 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if neeed)

### CODE REVIEW

**Review by afbora — COMMENTED** [review]
Perfect and simple solution, I love it ❤️ 

But the issue #2185 continues. I tracked down and found that the reason was the locale orders in lines:

https://github.com/getkirby/kirby/blob/fix/2233-api-locales/src/Api/Api.php#L185-L192

**My locale output:**
````php
var_dump(setlocale(LC_ALL, 0));
````

> LC_COLLATE=en_US.utf-8;LC_CTYPE=en_US.utf-8;LC_MONETARY=tr_TR;LC_NUMERIC=tr_TR;LC_TIME=tr_TR

Should be like that `tr_TR.utf-8`, instead of `tr_TR`.

I changed the order like following (utf8 take to the top) and working but i'm sure you'll find a better solution.

````php
$locales = [
    $locale . '.UTF-8',
    $locale . '.UTF8',
    $locale . '.ISO8859-1',
    $locale,
    $language,
    setlocale(LC_ALL, 0)
];
````

**Now locale output is**:

> LC_COLLATE=en_US.utf-8;LC_CTYPE=en_US.utf-8;LC_MONETARY=tr_TR.UTF-8;LC_NUMERIC=tr_TR.UTF-8;LC_TIME=tr_TR.UTF-8

**Comment by lukasbestle** [comment]
One fix for two issues, awesome! You are of course completely right about the fallback order – fixed now.

**Comment by afbora** [comment]
@lukasbestle I think we're facing another problem 😭 What if the server does not support UTF8 or can't find it (utf8 encoding) like following example? Unfortunately, it didn't work on my other pc localhost (Windows):

I'm getting always without utf8 encoding:

> LC_COLLATE=en_US.utf-8;LC_CTYPE=C;LC_MONETARY=tr;LC_NUMERIC=tr;LC_TIME=tr

I tried to change in translation file but didn't work too:

    "translation.locale": "tr_TR.utf-8",

I don't quite understand why the problem comes from, but is this Kirby's or user's problem? 🤔

**Comment by lukasbestle** [comment]
As your locales are set to the language code without full country locale, it looks like that PC doesn‘t have a Turkish locale at all. It could also be that it‘s because it‘s a Windows machine, so it may need a different locale syntax.

We can‘t really do anything about those edge-cases though. 🤷‍♂️

**Comment by afbora** [comment]
I understand. I think it would be useful to add this to the requirements and troubleshooting section of the documents 👍 What do you think? @texnixe

**Review by afbora — APPROVED** [review]

**Comment by lukasbestle** [comment]
We have already:

> The server OS must be POSIX compatible.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
