### PR TITLE
Mock usleep() function for faster PHPUnit tests

### PR DESCRIPTION
**Pull request by lukasbestle**
With the new additions to the `Auth` class in #2923, the `usleep()` function gets called a lot in tests.

This PR makes the tests run significantly faster as the sleep times are skipped during tests. This saves around 20 seconds, which is about 40 % of the entire PHPUnit run time.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Don't we use usleep in some tests to actually sleep to test file modification differences?

**Comment by lukasbestle** [comment]
I did a global file search on `sleep(` and didn't find other occurrences. I think we replaced that test logic a while ago as it was unreliable.

**Comment by lukasbestle** [comment]
Ah, yes, I remember now: The tests now use `touch()` with a timestamp in the past to fake passing time. As the tests all still pass, I think it's safe to merge this PR.

**Comment by bastianallgeier** [comment]
@lukasbestle ok, perfect!

**Pull request merged**
