### PR TITLE
Add `Panel\Model::pickerData()`

### LINKED ISSUE #3340: [3.6.0] Panel namespace: Check if additional abstract methods in the `Panel\Model` class are needed
See the discussion in https://github.com/getkirby/kirby/pull/3334/files#r632973618.

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

Since we call `->pickerData()` on any model, adding it to the abstract class is safer and also makes the code a bit more DRY.

## Release notes

None

## Breaking changes

None

## Related issues/ideas

- Fixes #3340

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] ~~In-code documentation (wherever needed)~~
- [x] CI checks pass

## When merging

- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~
- [x] ~~Add changes to release notes draft in Notion~~

### CODE REVIEW

**Comment by distantnative** [comment]
@lukasbestle can you produce the unit test error locally? For me it passes all tests locally but not in the CI

**Comment by lukasbestle** [comment]
@distantnative Have you seen the CI only fails for PHP 7.3? I can reproduce the issue with PHP 7.3 locally.

**Comment by distantnative** [comment]
I think I just broke my whole local setup by trying to switch to 7.3 🤬

**Comment by distantnative** [comment]
Ok could restore my setup. It seems like PHP 7.3 isn't working with Apple Silicon (on brew) so far.

**Comment by distantnative** [comment]
✅

**Review by bastianallgeier — APPROVED** [review]
Nice! This is a lot cleaner.

**Pull request merged**
