### PR TITLE
Add hooks before and after the plugins have been loaded

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

New `system.loadPlugins:before` and `system.loadPlugins:after` hooks are now triggered right before and after the plugins have been loaded. This makes it possible to hook into other plugins e.g. to extend them with further functionality.

**Open issue:** The tests currently don't pass because a `system.loadPlugins:after` hook defined in a plugin (which is the most important functionality of this feature) won't be triggered. The reason for this is that the `$app->extensionsFromPlugins()` method is called long after the plugins have been loaded – but before the hook would be triggered in `$app->plugins()` – so the hook is not already defined when it's triggered. Unfortunately I haven't found a good solution that doesn't require changing the system loading order. I'm very open for ideas!

## Related issues

- Closes https://github.com/getkirby/ideas/issues/23

## Todos

- [x] Add unit tests for fixed bug/feature
- [ ] Pass all unit tests
- [x] Fix code style issues with CS fixer and `composer fix`
- [x] If needeed, in-code documentation (DocBlocks etc.)

### CODE REVIEW

**Comment by lukasbestle** [comment]
@bastianallgeier Do you have an idea how to solve this?

**Comment by bastianallgeier** [comment]
I had a look at it and I don't have a good solution for it :(

**Comment by lukasbestle** [comment]
I played around with a few ideas in my head. What about this:

We could trigger the `after` hook in the `AppPlugins::extensionsFromPlugins()` method right after the extensions have been loaded instead of in the `AppPlugins::plugins()` method.

Advantage: The plugins are fully loaded in this moment, which means that the hooks are available. It also makes the hook more useful as other plugins can then check which extensions are already registered by other plugins.

Disadvantage: A lot of other stuff happens between the `before` and `after` hook, which may make the hooks less useful for measuring plugin loading times for example.

But as this is probably the only solution we can find, I'd say it's fine. What do you think @bastianallgeier?

**Comment by bastianallgeier** [comment]
To be honest, I would massively simplify this and trigger the after hook in the App.php on line 123 after `$this->extensionsFromFolders()`

I would not provide a before hook at all.

**Comment by lukasbestle** [comment]
That's a great idea! I have implemented a `system.loadExtensions:after` hook there and it works great. I kept the `system.loadPlugins` hooks additionally as they are already implemented and are not harmful. They are still useful when defined in the config.

**Comment by bastianallgeier** [comment]
I'm not a fan of keeping the loadPlugins hooks around tbh. Additional hooks also mean additional checks and we shouldn't just throw them in there if not really needed. I don't see a massive benefit of having them at all. I'd rename the `system.loadExtensions:after` to `system.plugins:after` and keep only that.

**Comment by lukasbestle** [comment]
Alright. Regarding the naming: I think that `system.plugins` doesn't really fit. The hook isn't fired after the plugins have been loaded and also the name doesn't tell what the hook is for (Hook after plugins? After what exactly?).

**Comment by bastianallgeier** [comment]
Ok, then let's use `system.loadPlugins:after` The word `Extensions` is only used internally.

**Comment by lukasbestle** [comment]
OK, done!

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
