### PR TITLE
Language: Export locale constants as strings #2426

### LINKED ISSUE #2426: Panel Creates Languages with Odd Locale Array
**Describe the bug**  
I'm testing out multi-language features of Kirby, but noticed that the Panel creates odd locale arrays in the language files it generates. For example:
```php
<?php

return [
    'code' => 'en',
    'default' => true,
    'direction' => 'ltr',
    'locale' => [
        6 => 'en'
    ],
    'name' => 'English (United States)',
    'translations' => [

    ],
    'url' => NULL
];
```

**To Reproduce**  
1. Enable `'languages' => true` in `config.php`
2. Create one or more languages in the Panel
3. Inspect the languages files in `site/languages`

**Expected behavior**  
The `locale` value should either be a simple string
```php
  'locale' => 'en',
```

or an array such as
```php
  'locale'  => [
    LC_ALL => 'en',
  ],
```
Source: https://getkirby.com/docs/guide/languages/introduction

**Kirby Version**  
`3.3.3`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.5 (15608.5.11)

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

The locale constants inside the language files are now stored as strings, not as their numeric values. This ensures compatibility between multiple PHP installations (between which the constant values may differ).

The old way of storing locales is still supported. The keys in the locale arrays will be automatically converted the next time the language file is saved.

## Related issues

- Fixes #2426

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
FireShot Capture 021 - Settings - localhost

> Use of undefined constant LC_MESSAGES - assumed 'LC_MESSAGES' (this will throw an Error in a future version of PHP)

I know this error. It is a bug in Windows, and I was using the `LC_MESSAGES` constant as a comment line when I was local. By the way `php_intl` extension is also installed.

https://www.php.net/manual/en/function.setlocale.php

> LC_MESSAGES for system responses (available if PHP was compiled with libintl)

FireShot Capture 023 - phpinfo() - localhost

**Comment by afbora** [comment]
Saving empty locale issue as a second problem steps to reproduce:

1. Add a language
2. Edit language
3. Leave blank locale input
4. Save language
5. See issue as language config like:

````php
'locale' => [
    'LC_ALL' => ''
]
````

You can also enter a space from panel and config saving like that:

````php
'locale' => [
    'LC_ALL' => '    '
]
````

**Comment by lukasbestle** [comment]
Thanks, I will take a look.

**Comment by lukasbestle** [comment]
@afbora I've fixed the issue with the error message about `LC_MESSAGES`.

The issue with the empty locale value is independent from this fix. I've created an issue here: https://github.com/getkirby/kirby/issues/2455

**Review by afbora — APPROVED** [review]
Done! 👍

**Pull request merged**
