### PR TITLE
Gender neutral language in german translation file

### PR DESCRIPTION
**Pull request by trych**
Hi!

(the entire following post will be in German, as it only concerns the German translation)

Bei den Kirby-Seiten, die ich bislang erstellt haben waren (durch Zufall) ca. 90% der Benutzer*innen weiblich. Im Panel spiegelt sich dieser Umstand bislang nicht wider, da hier ausschließlich von "Benutzern" die Rede ist.

Inzwischen ändern immer mehr (auch große) Seiten (z.B. Spotify, Behördenseiten etc.) ihren Sprachgebrauch dahingehend, dass zum Beispiel von Künstler*innen die Rede ist und nicht mehr nur von Künstlern, damit auch eindeutig weibliche und Non-Binary-Personen in den Bezeichnungen mit eingeschlossen sind und nicht – wie in der Software-Welt leider oft noch üblich – der Eindruck entsteht, dass sich die jeweilige Software/Website an ein rein männliches Publikum richtet.

Ich fände es daher einen schönen Schritt, wenn sich auch Kirby dieser Entwicklung anschließen würde und die deutsche Übersetzungdatei entsprechend angepasst wird. Nach meinem bisherigen Eindruck von Kirby wäre das auch gut im Einklang mit den sonstigen Werten, die die Entwickler*innen von Kirby vertreten.

Ich habe `kirby/i18n/translations/de.json` dahingehend angepasst und würde mich über Merge oder alternativ Verbesserungsvorschläge freuen.

### CODE REVIEW

**Comment by texnixe** [comment]
(Panel) translations are handled via Transifex: https://www.transifex.com/

**Comment by trych** [comment]
Ok, I signed up at Transifex now and have now a pending request to joint the German translation team of the kirby panel.

**Comment by trych** [comment]
Quick question about how this works. Do I just select a text, then edit its translation and click on "Save Changes"?

I guess there will be some review process initiated, before a translation gets approved and goes live?

20200325-160435_Screenshot_Firefox

**Comment by afbora** [comment]
@trych It comes to approval first. If approved, it comes to prod in the next Kirby version.

**Comment by trych** [comment]
Ok. Can I "collect" all changes somehow so they will all be approved in one batch? Similarly to one PR consisting of many small commits on git. Or does that not matter and devs will approve many little changes separately?

**Comment by afbora** [comment]
You can download to CSV and upload in bulk. But I guess it doesn't work like PR.

**Comment by trych** [comment]
Ok, damn, I did it now by hand already. The UI is super confusing.
What should I do about this PR? Should it be closed?

**Comment by afbora** [comment]
Yes, you can continue from transifex.

**Comment by bastianallgeier** [comment]
I really like the idea! Let me know if I can help you somehow. Sorry for the confusion with Transifex.

**Comment by trych** [comment]
> Let me know if I can help you somehow.

@bastianallgeier I think I made a "suggestion" now for each occurence of "Benutzer" or "Administrator" in Transifex. In my understanding someone needs to review and approve these suggestions now to include them in the next update.

Maybe you could be so kind to have a quick look if you can see the suggestions and can approve them, because I am somewhat lost in the Transifex UI and cannot be sure, if the suggestions are visible for the others there. Thanks!

**Comment by distantnative** [comment]
@bastianallgeier @trych I really like this idea! I would just love if we could avoid a specific syntax (_,*,...) as many of them are very loaded and there is little consensus what to use. I would rather try whether we actually can find gender neutral terms instead of typographic suffixes that aim to render a term gender neutral. I know this can be challenging, but I would prefer this way. What do you think?

**Comment by trych** [comment]
While I agree that it is somehow difficult to agree on a specific one, it seems that the `*` is currently somewhat "winning out" over the other ones, which I think is great as it has been a mess for the years before that. So in my opinion it is great news that people seem to slowly agree on a "standard".

Also, unlike with other ones, with the `*` I have never read strong arguments against it (I might miss some stuff though) as it includes non-binary, female and male gender alike. But if you have sources with strong arguments against `*`, I am happy to read them and correct myself.

What lastly led me to decide in favor of `*` is the fact that for example Spotify introduced it recently and I have seen only positive reactions from the feminist circles that I am in contact with, so I don't think Kirby would go wrong with it.

**Comment by distantnative** [comment]
> But if you have sources with strong arguments against `*`
It's being constantly debated still, in the context at my work in the communications department for a German university.

Don't get me wrong, personally I prefer the `*` over all other variants. But I wouldn't agree with the observation that everyone is settling for this one. Which is why I remain a supporter of trying to use actual gender neutral terms.

A good source for actual gender neutral terms:
https://geschicktgendern.de

We shouldn't overlook one big criticism about the `*` on the web - screenreaders seem to still have a lot of issues with this syntax.

**Comment by trych** [comment]
> trying to use actual gender neutral terms

The whole point of the `*` is that it turns the generic masculinum into gender neutral terms that also include non-binary people.

> one big criticism about the * on the web - screenreaders seem to still have a lot of issues with this syntax

That's the only criticism I ever hear about the `*`. I think it is

A) not relevant for the case at hand
B) even more reason to fully establish the `*` to eventually force screen reader manufacturers to allow for it – there is no technical reason to not allow it

Also, in the same train of thought, people then often say that for this very reason they prefer the `:` which I would argue is actually more problematic, since it is not even allowed in file names.

Having said all that, I am open for better alternatives that avoid the use of `*`. However, in the case of `Benutzer*innen`, the main alternative I see are `Nutzende`. This

A) seems to me like too much of a made up word that does not really describe its original function anymore
B) (more importantly), if you switch back to singular you end up with `Nutzender` again, which is the masculinum again, so you would have to switch to something like `Nutzende*r` again.

But once again, if you have good alternatives for `Benutzer*in` and `Administrator*in`, that still let the users easily understand what they describe, I am all ears.

**Comment by distantnative** [comment]
I'm saying "actual gender neutral terms" to make a differentiation between terms that don't inherit a gender in themselves and terms that you render gender-neutral through syntactic modification (*, Binnen-I, Slash...).

But how is `*` creating problems with screenreader not a problem here? If we change the terms around the Panel then we create problems for people that rely on screenreader, that it an issue at hand. I think we should do some actual research how big of a problem that is for screenreader - we can't just ignore people who rely on these.

And it's `der*die Nutzende` not `Nutzender`, Plural is `Nutzenden`.  To be honest it doesn't appear to me a much more made up word as `Benutzer*innen` – both are non-traditional and created to fill a position that existing words haven't been able to do so.

My personal opinion, I think yours is clear as well. As so often with this topic it comes down to emphasis on different aspects and taste. Nothing wrong with either or per se. Best would be to hear from other German-speaking people, @lukasbestle @texnixe @bastianallgeier

**Comment by trych** [comment]
> But how is `*` creating problems with screenreader not a problem here?

My apologies, I was under the impression that screenreaders just refers to audio books (and therefore would be irrelevant for the panel interface). Not sure, where I got this idea from, but I stand corrected.

> I think we should do some actual research how big of a problem that is for screenreader

I would agree to that. If it becomes plain unusable for users with screenreaders, we should avoid the `*`. If however, only the pronounciation becomes slightly funny, then I think the advantages outweigh the (current) disadvantages.

> And it's der*die Nutzende not Nutzender, Plural is Nutzenden.

Yes, but in some sentences, this would still require the `*`, e.g. having a sentence like:

"Ein Benutzer mit der E-Mailadresse \"{email}\" besteht bereits"

would turn into

"Ein\*e Nutzende\*r mit der Emailadresse ..." which renders the switch from "Benutzer\*in" to "Nutzende\*r" pretty useless. Also still requiring the `*` in `die*der` gets only rid of the `*` halfway, so I don't understand the need to switch to a term that – at least to me – sound much stranger.

> To be honest it doesn't appear to me a much more made up word as Benutzer*innen

I still think Benutzer\*innen is not a made up word, it uses a new made up grammatical syntax on already existing words. Switching to "Nutzende" shifts the whole word and emphasises a different aspect of "being-a-user". To me "Nutzende" sounds like someone that is constantly in the process of using something, as opposed to "Benutzer*in" as someone who holds an account on a website.

> Best would be to hear from other German-speaking people

👍

**Comment by texnixe** [comment]
> "Ein Benutzer mit der E-Mailadresse "{email}" besteht bereits"

That could be turned into "Ein Konto/Account mit dieser Email-Adresse besteht bereits", thus completely eliminating the need for gendering. Maybe "Konto" can be used in other places as well.

**Comment by lukasbestle** [comment]
I agree that it would be best to reword the translations to use gender-neutral terms wherever possible exactly like in @texnixe's suggestion. Sentences full of asterisks (or any delimiting character really) are quite hard to read, so the more we can avoid them while still using gender-neutral language, the better.

@trych What is the current status of your Transifex contribution? If there are some strings where good alternatives are missing, we can work on those together. Unfortunately Transifex is not very good for collaborative editing, so we might need to do to this here or for example on Notion.

**Comment by trych** [comment]
> What is the current status of your Transifex contribution?

I made these so called "suggestions" for all strings in questions, i.e. whenever there was a string containing "Benutzer" I made a suggestion for an improvement. I am not sure where those suggestions are visible for the other translators (if they get it into some inbox or something).

> Unfortunately Transifex is not very good for collaborative editing

That was my impression as well. So my suggestion would be to actually handle this via a github PR (as I initially did), but just to all agree on a version and once there is an agreement here, not to merge it, but to have someone put it into Transifex. Just to be able to handle it better.

**Comment by lukasbestle** [comment]
> I made these so called "suggestions" for all strings in questions, i.e. whenever there was a string containing "Benutzer" I made a suggestion for an improvement. I am not sure where those suggestions are visible for the other translators (if they get it into some inbox or something).

I see some unreviewed translations and also the suggestions, but those are very much hidden in the UI.

> That was my impression as well. So my suggestion would be to actually handle this via a github PR (as I initially did), but just to all agree on a version and once there is an agreement here, not to merge it, but to have someone put it into Transifex. Just to be able to handle it better.

That's a nice idea.

I think we have the agreement that we should first try to rephrase the relevant translations. After that we can see what's left and then decide which syntax to use (if necessary). :)

**Comment by distantnative** [comment]
Trying to move the debate forward again...

Since Transifex is in maintenance mode, let me add my suggestions here, so we discuss them before changing them on Transifex:

```json
"dialog.users.empty": "Kein verfügbarer Account",
"error.user.changeEmail.permission":
     "Du kannst die E-Mailadresse für den Account \"{name}\" nicht ändern",
"error.user.changeLanguage.permission":
     "Du kannst die Sprache für den Account \"{name}\" nicht ändern",
"error.user.changeName.permission":
     "Du kannst den Namen für den Account \"{name}\" nicht ändern",
"error.user.changePassword.permission":
     "Du kannst das Passwort für den Account \"{name}\" nicht ändern",
"error.user.changeRole.lastAdmin":
     "Die Rolle kann nicht geändert werden. Der Account ist der letzte mit Administrationsrechten.",
"error.user.changeRole.permission":
     "Du kannst die Rolle für den Account \"{name}\" nicht ändern",
"error.user.changeRole.toAdmin":
    "Du darfst die Admin-Rolle nicht für andere Accounts vergeben",
 "error.user.create.permission": "Du darfst diesen Account nicht anlegen",
 "error.user.delete": "Account \"{name}\" konnte nicht gelöscht werden",
 "error.user.delete.lastAdmin": "Du kannst den Account als letzter mit Administrationsrechten nicht löschen.",
 "error.user.delete.lastUser": "Der letzte Account kann nicht gelöscht werden",
"error.user.delete.permission":
  "Du darfst den Account \"{name}\" nicht löschen",
"error.user.duplicate":
     "Ein Account mit der E-Mailadresse \"{email}\" besteht bereits",
"error.user.notFound": "Der Account \"{name}\" wurde nicht gefunden",
 "error.user.password.undefined": "Der Account hat kein Passwort",
"error.user.update.permission":
     "Du darfst den Account \"{name}\" nicht bearbeiten",
"field.users.empty": "Keine Accounts ausgewählt",
"lock.isUnlocked": "Deine ungespeicherten Änderungen wurden von einem anderen Account überschrieben. Du kannst sie herunterladen, um sie manuell einzufügen. ",
"page.status.draft.description":
     "Die Seite ist im Entwurfsmodus und ist nur für angemeldete Accounts sichtbar",
"role.admin.description": "Admins haben alle Rechte",
"role.admin.title": "Admin"
"role.empty": "Keine Accounts mit dieser Rolle",
"user": "Account",
"user.blueprint":
     "Du kannst zusätzliche Felder und Bereiche für diese Rolle in <strong>/site/blueprints/users/{role}.yml</strong> anlegen",
"user.changeName": "Account umbenennen",
"user.create": "Neuen Account anlegen",
"user.delete": "Account löschen",
"user.delete.confirm":
     "Willst du den Account <br><strong>{email}</strong> wirklich löschen?",
"users": "Accounts",
"view.users": "Accounts",
```

**Comment by nilshoerrmann** [comment]
Randnotiz, weil mit der Begriff gerade ins Auge springt: Wir haben immer wieder feststellen müssen, dass deutsche Nutzer kirbyunabhängig Schwierigkeiten mit dem Wort „Account“ haben.

**Comment by distantnative** [comment]
Fand "Account" griffiger als "Konto". Aber gern mehr Meinungen! Oder auch Vorschläge!

**Comment by nilshoerrmann** [comment]
Leider habe ich nichts Griffigeres. Ich war nur schon oft mit der Frage konfrontiert, was der Account genau sei. Ist grundsätzlich ein Problem, egal ob in Kirby oder woanders.

Benutzerkonto funktioniert meist, ist aber so ein Wortungetüm.

**Comment by distantnative** [comment]
Und löst leider auch nicht das Problem von Benutzer als nicht gendergerecht 😆

**Comment by lukasbestle** [comment]
Account finde ich gut! Auf der deutschen Wikipedia-Seite für "Benutzerkonto" ist Account auch als Alternativbezeichnung genannt.

**Comment by bastianallgeier** [comment]
Mir fällt als Alternative für Account nur Profil ein. Richtig eindeutig ist das aber auch nicht.

**Comment by nilshoerrmann** [comment]
Ja, mir fallen auch nur Konto und Profil ein. Ich persönlich habe kein Problem mit Account, da ich den Begriff aus dem Englischen gewöhnt bin. Ich bin nur selbst immer wieder überrascht, wie oft ich Nachfragen zu den Wort bekomme. À la: „Account? Was war das jetzt nochmal?“.

Aber Nico sagt ja zu Recht, dass es hier erstmal um neutrale, inklusive Sprache geht. Kann man sich also auch später nochmal Gedanken zu machen.

**Comment by bastianallgeier** [comment]
Ich finde die Änderungen ansonsten gut, da es das Problem auf elegante Weise umschifft und wesentlich neutraler wirkt. "Benutzer" ist auch an sich einfach ein furchtbares Wort.

**Comment by distantnative** [comment]
Bin auch gerne bei Konto oder Profil dabei - persönlich finde ich die alle ähnlich gut.
Wenn es zwischen diesen dreien geht, wofür sollten wir uns entscheiden?

Auch nochmal ping
@trych @lukasbestle @texnixe

**Comment by trych** [comment]
> Ich bin nur selbst immer wieder überrascht, wie oft ich Nachfragen zu den Wort bekomme. À la: „Account? Was war das jetzt nochmal?“.

Ich glaube solche Nachfragen drehen sich aber eher um das Konzept des Accounts als um das Wort. Ich bin mir sicher, dass genau solche Nachfragen auch bei den beiden anderen Bezeichnungen kommen würden.

Von den drei Begriffen finde ich Account am besten (und auch völlig unproblematisch im Deutschen), bin aber auch mit den anderen einverstanden.

**Comment by nilshoerrmann** [comment]
@distantnative: Wenn es ein Entscheidung zwischen den Begriffen Account, Konto und Profil fallen soll, würde ich für Konto stimmen. Meiner Erfahrung nach ist es eben kein Problem mit dem Konzept des Accounts im allgemeinen, sondern ein sprachliches Problem, dass das Wort Account unbekannt und inhaltlich unbesetzt ist. Zumindest hat bisher der Hinweis "Das ist das Benutzerkonto" immer als Erklärung geholfen.

**Comment by lukasbestle** [comment]
Es hängt am Ende vermutlich auch davon ab, wen man fragt. Ein Buchhalter wird bei Konto wiederum verwirrt sein.

Ich schwanke zwischen Account und Konto. Profil finde ich zu unspezifisch, da würde ich eher die Personenbeschreibung auf der Teamseite etc. drunter verstehen.

**Comment by bastianallgeier** [comment]
Lasst uns doch jetzt einfach mal mit Account starten. Das behebt das grundsätzliche Problem. Wenn das dann doch für zu viel Verwirrung sorgt, dann können wir immer noch Alternativen durchprobieren.

**Comment by distantnative** [comment]
✅ Habe es entsprechend bei Transifex aktualisiert.

**Pull request closed without merging**
