### PR TITLE
Conditional fields: when/then

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

@afbora's draft of the when/then implementation. Depends on https://github.com/getkirby/kirby/pull/2522; this PR branch needs to be rebased after that PR is merged.

## Related issues

- Implements https://github.com/getkirby/ideas/issues/257

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Fixed code style issues with CS fixer and `composer fix`
- [ ] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
@lukasbestle Thank you very much especially for taking care of it ❤️ 

After #2522 has been merged, I will revise this PR according to your regulations in that PR. 

If PR is still acceptable after revised, i will ask support from @bastianallgeier and @distantnative for the Vue part for second round 🙏

**Comment by pReya** [comment]
I know you're all doing what you can – not trying to be a pain in the ass. But it seems like the required PR #2522 has been merged. So maybe the "status: blocked" tag can be removed so this can proceed on its path to become a full PR?

**Comment by afbora** [comment]
@pReya Do not be behind your eyes. I'm working on the feature. I will probably create new fresh PR. I hope it is at 3.5.x or 3.6.

**Comment by distantnative** [comment]
@afbora @lukasbestle what can we do to get this polished/ready for 3.6.0? 

Would be great to also include more explanation on the feature in the initial comment here. I tried to hunt it down but there are even so many versions/changes/ideas on the other previous PR. Would be great o have a fresh, full summary :)

**Comment by afbora** [comment]
To be honest, it was the simple structure I was thinking of at first, and it didn't work.
Too many and complex parts of JS emerged as I went deeper.
@distantnative, I hope I wouldn't have wanted too much if I wanted you to make this feature. 🙏 😇 🙈 ❤️

**Comment by distantnative** [comment]
To be honest, I don't really know what the last idea for this feature was.
Maybe it makes sense to revisit the feature concept first (what do we want and how should it work) before we tackle the final implementation.

**Comment by afbora** [comment]
Then I'll rework it and give you a summary on a new PR after 3.5.5. 
If I have any deficiencies, I would like to ask you for help 🙏

**Pull request closed without merging**
