### PR TITLE
Fix sorting files on edge browser

### LINKED ISSUE #1973: [Panel] Behavior of files sorting to switch to upload in Edge browser
You can't hold and drag the picture in Chrome. However, you need to click on the `handle` (#icon-sort) for sort.

But you can drag and drop the picture on the Edge and when you drop it, it loads a file in the `.url` extension.

**To Reproduce**

1. Download starterkit
2. Login panel with Edge Browser
3. Enter an album `/panel/pages/photography+sky`
4. Drag (over the image, not from handle) any image and drop same field area

**Screencast (8.07MB)**

dragdrop

**Kirby Version**
3.2.2

**Console output**
No any error.

**Desktop**

 - Windows 10
 - Microsoft Edge 44.17763.1.0
 - Microsoft EdgeHTML 18.17763

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

`Dropzone` and `Draggable` components overlapped.  Dropzone drag & drop came into play when we kept the image (not from handle) in the Edge browser. I prevented it with `prevent` event.

Tested on 3.2.5 with Chrome & Firefox & Edge Browser

**Screencast on Edge Browser**

edge

## Related issues

- Fixes #1973 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Fixed code style issues with CS fixer and `composer fix`
- [ ] Added in-code documentation (if neeed)

### CODE REVIEW

**Review by bastianallgeier — COMMENTED** [review]
Unfortunately this fix breaks dragging files from the files section into a textarea

**Comment by afbora** [comment]
@bastianallgeier I missed that side, reverted `prevent` update.

It was loading as `filename.url` shortcut when you held the file and dropped it anywhere in the edge browser. I followed the event and noticed that the file type was `Files, text/html, text/plain`. I've solved this issue by preventing plain text from loading and that was really difficult specific browser issue.

Is it a problem if we prevent the `text/plain` type? What do you think? 🤔 

edge

**Review by bastianallgeier — COMMENTED** [review]
Great catch! I think we should somehow put that logic into a helper. Right now it's repeated in the same way quite a lot.

**Comment by afbora** [comment]
Can I ask you for help here? 😇

**Comment by bastianallgeier** [comment]
@afbora I added a new helper to identify upload events. It works fine in Chrome. Could you check if it all works as expected in Edge as well?

**Comment by afbora** [comment]
@bastianallgeier Works perfect! Thank you so much 👍

**Pull request merged**
