### PR TITLE
Implement automatic "future hooks"

### PR DESCRIPTION
**Pull request by lukasbestle**
Right now, Kirby only triggers the hook callbacks that have been registered before triggering the hook. In some cases (like "onload" events for complex plugins to notify other plugins) it makes sense to call a callback even if it is registered *after* triggering the hook.

This commit introduces a new parameter for the trigger method. If set to true, every newly registered hook with that name will get called with the arguments from the trigger call instantly after it has been registered. The behavior of calling hooks from the past is unchanged.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I'm a bit lost here. Could you post an example?

**Comment by lukasbestle** [comment]
Sure. :)

## Use-case

Let's say you have two plugins named `testplugin` and `testplugin-depending`. `testplugin-depending` requires `testplugin` to work, so we need to make sure `testplugin-depending` runs its code after `testplugin` has been loaded.

A very simple way to do such things is using hooks.

## Current implementation

The two plugins contain the following (simplified) code:

**testplugin.php**:

```php
<?php

$somedata = 'This value is generated by this plugin!';

kirby()->trigger('testplugin.load', array($somedata));
```

**testplugin-depending.php**:

```php
<?php

kirby()->hook('testplugin.load', function($somedata) {
	var_dump($somedata);
});
```

Now there's a problem: The hook gets registered *after* it is triggered, because the `testplugin-depending` plugin is loaded after the `testplugin` plugin. Result: The hook never gets called.

## New future-hook-feature

We only need to change the trigger call to change this behavior:

**testplugin.php**:

```php
<?php

$somedata = 'This value is generated by this plugin!';

// $future parameter set to true
kirby()->trigger('testplugin.load', array($somedata), true);
```

Kirby now stores the trigger call and invokes any newly registered hook immediately, even if it has been registered *after* the trigger call.

**Comment by bastianallgeier** [comment]
Ahh, now I get it. Do you find it very obvious? Maybe I'm a bit slow, but it took me quite a while to understand what this actually does and you somehow have to understand the internals of how plugins and hooks are loaded in order to get it. What do you think about introducing some kind of plugin require syntax instead. I'm not 100% sure yet, but something like: 

```
<?php 

kirby()->plugins()->load('testplugin');
kirby()->plugins()->load('someotherplugin');

```

**Comment by lukasbestle** [comment]
> Do you find it very obvious? Maybe I'm a bit slow, but it took me quite a while to understand what this actually does and you somehow have to understand the internals of how plugins and hooks are loaded in order to get it.

Yes, that's definitely true. I agree with you that my solution (while it works) isn't that easy to understand and complicates the whole hook system.

> What do you think about introducing some kind of plugin require syntax instead.

Wow, that's a simple and awesome solution. I tried to make my solution as broad as possible, but specific solutions are always better.
And guess what: The following code already works:

```php
<?php 

$testpluginReturn = kirby()->plugin('testplugin');
$someotherpluginReturn = kirby()->plugin('someotherplugin');
```

Awesome, problem solved. :)

**Pull request closed without merging**
