### PR TITLE
Multiselect input: UX improvements

### LINKED ISSUE #5744: [v4] Multiselect field: don't hide selected values, but highlight them
The UX of the multi select field got worse with v4 - as it is currently simply a tags field in a way.
However, a multiselect field should always show all options in its dropdown, never filter them. And instead should show those options that are selected with a highlighted styling.

Screenshot 2023-10-07 at 16 19 20

### PR DESCRIPTION
**Pull request by distantnative**
@bastianallgeier @afbora 
The code is still shit - just a rough implementation. But would be great to get your feedback on the UX. I think we should first get that right, agree on something and then I can work on implementing it in a clean way in the components.

Screenshot 2023-10-16 at 20 31 25

- Shows selected state in the dropdown
- Clicking on already selected options will remove them (unselect them)
- Dropdown fits to width of input

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Just a quick thought before I have a chance to try it. What if we use the checkboxes and radio inputs in the dropdown? This could even introduce the info line and we would be able to offload a lot of code to those components.

**Comment by afbora** [comment]
@distantnative Maybe you want to take a look these issues before refactoring the field:
- https://github.com/getkirby/kirby/issues/5629
- https://github.com/getkirby/kirby/issues/5627

**Comment by distantnative** [comment]
@bastianallgeier would that work for the tags input context as well?
@afbora I think we need to tackle those at the end, first find a UX that works

**Comment by bastianallgeier** [comment]
@distantnative yes, I think so and it would semantically also be correct.

**Comment by distantnative** [comment]
Closing in favor of https://github.com/getkirby/kirby/pull/5822

**Pull request closed without merging**
