### PR TITLE
Kql

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

**⚠️ Depends on https://github.com/getkirby/kirby/pull/4626**
**❓ This is a suggestion. There are no concrete plans yet to pursue this.**

### Feature
- KQL is now part of the core

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by johannschopplich** [comment]
Sweet Christmas!

**Comment by distantnative** [comment]
@johannschopplich 
> ❓ This is a suggestion. There are no concrete plans yet to pursue this.

And I mean it. This is me toying around with the idea, building it on top of refactored Query classes. But neither discussion nor decision with the team so far, if we really want to integrate it already.

**Comment by johannschopplich** [comment]
@distantnative I know. Simply wanted to report my euphoria as a contribution to the discussion.

**Comment by distantnative** [comment]
Will be easier with new KQL 1.3.0

**Pull request closed without merging**
