### PR TITLE
Fiber: handle popping state

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Fiber handles popping the window state now, fixes issues with e.g. language selector on back navigation
#5007

### Breaking changes
None

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by distantnative** [comment]
@afbora your testing would be great on this one

**Comment by afbora** [comment]
@distantnative Language drop down seems fixed but field contents still old:

Steps:
- Open a page (main language), edit and save
- Switch secondary language and use browser back (same for using forward)
- See old content value

**Comment by distantnative** [comment]
Ugh, so the popped state is old old... :(

**Comment by distantnative** [comment]
Trying it with a hard reload on pop event now...

**Comment by distantnative** [comment]
Found the next problem with that myself:
- switch to non-default language
- change something but don't save
- hit back button
- unsaved change now gets applied to default language

**Comment by afbora** [comment]
Nice working 🎉 except a little dialog and console error:

> TypeError: Cannot read properties of null (reading '$url')

Steps:

- Open fresh browser tab
- Enter panel login address and log in
- Use browser back
- See dialog and console error

**Comment by afbora** [comment]
> Found the next problem with that myself:

I can't reproduce that issue 🤔

**Comment by distantnative** [comment]
@afbora realised it's messed up: happens for me with the time field when I changed the value but am still in the field and then hit the back button. I think what must happen is that on field blur the input gets sent to the content store at the same time that the pop event takes place.

**Comment by afbora** [comment]
I don't know what issue you're having, but it seems to work great for me now 🎉

**Comment by afbora** [comment]
> Found the next problem with that myself:

I can reproduce now with following steps:

- Open `Notes` page in starterkit panel
- Edit `Exploring the universe` page in notes
- Edit a block without saving
- Use browser back
- See unsaved changes for `Notes` page

I have no idea about that 🤷‍♂️

**Comment by distantnative** [comment]
@afbora tried a more hardcore version with `window.location` which I think fixes most problems, but prevents us to go forward after going backwards once :/

**Comment by distantnative** [comment]
I keep thinking that something like

```js
async popState(event) {
	this.setState(event.state, { replace: true });
}
```

should be the right way.

But that has the same content store problem you described, @afbora .

**Comment by afbora** [comment]
> @afbora tried a more hardcore version with `window.location` which I think fixes most problems, but prevents us to go forward after going backwards once :/

@distantnative It seems to be working for me. Both backwards and forwards work without any problems. Am I missing something?

**Pull request closed without merging**
