### PR TITLE
Modify page cache flush

### PR DESCRIPTION
**Pull request by ezraverheijen**
Follow up for pull request #189
I really need an option (please rename it if there is a better description) like this for a site with a huge amount of content. I don't want (and don't need) the entire page cache to be flushed on every single update.

### CODE REVIEW

**Comment by lukasbestle** [comment]
Hm, that doesn't really make sense to me. A setting that would be awesome though is an array of template names for which this behavior is disabled (for pages like a sitemap, where the content is totally exclusive to that page).

**Comment by ezraverheijen** [comment]
The sitemap can be excluded from cache via c::set('cache.ignore')
I (and if I need it the otters might too) need an option to disable the entire cache folder  flush thingy

**Comment by ezraverheijen** [comment]
Maybe it fits other methods too, but update() and create() covers the minimum need for me in my case

**Comment by bastianallgeier** [comment]
I'm sorry, but I'm going to close this for now. I see why this could be useful sometimes, but it adds additional complexity to the entire caching mechanism and I want to avoid this for now.

**Pull request closed without merging**
