### PR TITLE
Update page sections on `page.sort` #3399

### LINKED ISSUE #3399: Page sections don't update if page got sorted in another section
If you have two page sections on the same view and you sort pages in one of them, the other one isn't updated.

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

When sorting pages in one page section, other page section weren't updating and thus maybe shown the same pages in old order.

### Fix
- Fixed updating page sections after sorting pages in another section

## Breaking changes

_None_

## Related issues/ideas

- Fixes #3399

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by lukasbestle** [comment]
Could the same happen with file sections?

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
@lukasbestle probably yes. We should test and fix that in another PR if needed.

**Comment by bastianallgeier** [comment]
@distantnative yikes. I thought changing the base was enough, but this is based off the develop branch. We should probably cherry-pick the changes.

**Comment by distantnative** [comment]
@bastianallgeier let's not rush closing PRs - I think Lukas suggestion makes total sense to be solved in this PR already. It'll be a quick addition one of the next days and then we can merge it. I will also take care of fixing the basing.

**Comment by distantnative** [comment]
Ok already have added it and fixed basing.

**Review by bastianallgeier — APPROVED** [review]
It's even better that you solved it all in one PR. Looks good to me!

**Pull request merged**
