### PR TITLE
Dom: Proper handling for Unicode in HTML and XML documents; more consistent export

### LINKED ISSUE #3798: Stuck in an unsaved changes loop
Related https://github.com/getkirby/kirby/pull/3758 PR and still continue unicode characters issue.

You can use following content to reproduce the issue:

````
[{"attrs":{"width":"full-width","mbottom":"true","bgcolor":"colorLightGray"},"columns":[{"blocks":[{"content":{"slides":[{"title":"\u0160ildymo sistemas pri\u017ei\u016brin\u010di\u0173 profesional\u0173 ir savo \u0161ildymo sistema besir\u016bpinan\u010di\u0173 vartotoj\u0173 pam\u0117gti cheminiai priedai","bg":["slide-1.png"],"text":"<ul><li><p>Skland\u017eiam ir ekonomi\u0161kam sistemos veikimui<\/p><\/li><li><p>Efektyviam \u0161ildymo problem\u0173 sprendimui<\/p><\/li><\/ul>","button":{"type":"page","value":"contacts","text":"Daugiau informacijos"}},{"title":"Priedai sistem\u0173 apsaugai nuo korozijos, purvo, nuovir\u0173","bg":["slide-2.png"],"text":"<ul><li><p>Tausoja katil\u0105, \u0161ilumos siurbl\u012f, kitus \u0161ildymo prietaisus ir \u012frang\u0105.<\/p><\/li><li><p>I\u0161lieka veiksmingi vis\u0105 sistemos eksploatavimo laik\u0105.<\/p><\/li><\/ul>","button":{"type":"page","value":"contacts","text":"Daugiau informacijos"}},{"title":"Magnetiniai \u2013 cikloniniai \u0161ildymo sistemos filtrai","bg":["slide-3.png"],"text":"<ul><li><p>Padeda pasi\u0161alinti \u012fvairiems ter\u0161alams ir apsaugo \u0161ildymo prietaisus nuo pirmalaikio gedimo.<\/p><\/li><li><p>Modeliai kompakti\u0161kai ir erdviai katilinei.<\/p><\/li><li><p>10 \u2013 25 met\u0173 garantija.<\/p><\/li><\/ul>","button":{"type":"page","value":"products","text":"Daugiau informacijos"}},{"title":"\u0160ildymo ir \u0161aldymo sistem\u0173 plovikliai","bg":["slide-4.png"],"text":"<ul><li><p>I\u0161tirpdo \u012fvairias nuos\u0117das.<\/p><\/li><li><p>R\u016bg\u0161tiniai ir ner\u016bg\u0161tiniai.<\/p><\/li><li><p>Tinkami visiems praplovimo \u012frenginiams.<\/p><\/li><\/ul>","button":{"type":"page","text":"Daugiau informacijos","value":"products\/plovikliai"}},{"title":"\u0160ildymo sistemos prot\u0117ki\u0173 hermetizavimo priemon\u0117s","bg":["slide-5.png"],"text":"<ul><li><p>Efektyvi pagalba atsiradus mikro prot\u0117kiams.<\/p><\/li><li><p>Suveikia per kelias valandas, nereikia i\u0161leisti sistemos.<\/p><\/li><\/ul>","button":{"type":"page","value":"products\/protekiu-hermetikai","text":"Per\u017ei\u016br\u0117ti produktus"}}],"height":"h-medium","align":"align-left","valign":"valign-middle","paddingleft":null,"paddingright":52,"overlaytoggle":"false","overlaytop":"#FFFFFF","overlaybottom":"#FFFFFF","overlaymobiletoggle":"true","overlaymobiletop":"#FFFFFF82","overlaymobilebottom":"#FFFFFF82","bgmobileposition":null,"titlestyle":"hstyle2","titlecolor":"#0F4C87","tagtitle":"h2","textstyle":"tstyle2","textcolor":"#0F4C87","fontsizea":"","fontweighta":""},"id":"38e799f7-99b2-41e9-8f9c-a046b8f807f6","isHidden":false,"type":"slides"}],"id":"3f93abad-add6-4267-bc58-268f7ee5f18b","width":"1\/1"}],"id":"c35e77bb-e370-4c26-b104-8be6c1184d04"},{"attrs":{"width":"container","mbottom":"false","bgcolor":"colorLightGray"},"columns":[{"blocks":[{"content":{"level":"h2","text":"FERNOX \u2014\u00a0jau 57 metus \u2014\u00a0patikimi, profesional\u016bs, aplink\u0105 tausojantys sprendimai j\u016bs\u0173 \u0161ildymo sistemai","halign":"","styleheading":"hstyle2"},"id":"7733aede-1e08-444e-93d7-0b42b0a04924","isHidden":false,"type":"heading"},{"content":{"features":[{"icon":["network.svg"],"title":"Fernox pasaulyje","text":"<p>Fernox - pasaulyje gerai \u017einomas vandens prie\u017ei\u016bros chemikal\u0173 ir \u00a0\u012frangos gamintojas. \u012emon\u0117 prad\u0117jo veikl\u0105 1964 metais Jungtin\u0117je Karalyst\u0117je, o \u0161iandien Fernox produktais prekiaujama daugiau nei 40-yje \u0161ali\u0173 Europoje, Amerikoje ir Azijoje.<\/p>"},{"icon":["science-molecule-strucutre.svg"],"title":"Produkt\u0173 panaudojimas","text":"<p>Fernox produktai skirti tiek priva\u010di\u0173, tiek pramonini\u0173 \u0161ildymo ir \u0161aldymo sistem\u0173 vandens paruo\u0161imui, vamzdyn\u0173 ir \u012frengini\u0173 praplovimui ir nukalkinimui, prot\u0117ki\u0173 hermetizavimui, apsaugai nuo u\u017e\u0161alimo. Platus magnetini\u0173\/ciklonini\u0173 \u0161ildymo sistemos filtr\u0173 pasirinkimas. Sukurta atskira produkt\u0173 grup\u0117 atsinaujinan\u010di\u0173 i\u0161tekli\u0173 \u0161ildymo sistem\u0173 prie\u017ei\u016brai.<\/p>"},{"icon":["file-iso.svg"],"title":"Kokyb\u0117","text":"<p>\u012emon\u0117 nuolat investuoja \u012f\u00a0mokslinius tyrimus ir ie\u0161ko novatori\u0161k\u0173 bei\u00a0aplink\u0105 tausojan\u010di\u0173 sprendim\u0173. Gymybos procese \u012fdiegti ISO 9001, ISO 14001, ISO\/TS 16949 ir OHSAS 18001 standartai. Produktai sertifikuoti \u012fvairiose nepriklausomose ES laboratorijose.<\/p>"}],"cols":4},"id":"1a1daaff-8bf8-4d04-9c13-6210f20843ba","isHidden":false,"type":"features"}],"id":"3a59ae10-4149-48a9-bd38-16bbfd0179b2","width":"1\/1"}],"id":"12fbd5d0-4d90-48f6-8ce4-c221e29e2f79"},{"attrs":{"width":"container","mbottom":"false","bgcolor":"colorLightGray"},"columns":[{"blocks":[{"content":{"level":"h2","text":"Norite prad\u0117ti naudotis m\u016bs\u0173 produktais?","halign":"left","styleheading":""},"id":"8134a98d-16d6-4ce5-ac11-3f42f901c194","isHidden":false,"type":"heading"}],"id":"a47bdbd3-2ab3-4793-9e11-4a2eb60e08ef","width":"1\/1"}],"id":"05e639e9-3dde-4387-a197-128c0578e341"},{"attrs":{"width":"container","mbottom":"false","bgcolor":"colorLightGray"},"columns":[{"blocks":[{"content":{"level":"h3","text":"Skambinkite:\u00a0+370 685 06 811","halign":"left","styleheading":""},"id":"fe43f682-998e-4359-a9a3-e60a931437a7","isHidden":false,"type":"heading"},{"content":{"text":"<p><strong>Atstovas Lietuvoje UAB \"Sandomus\"<\/strong><\/p><p>\u012emon\u0117s kodas: 302594355<\/p><p>PVM kodas: LT100005964216<\/p><p>Mobilus: +370 685 06 811<\/p><p>El. pa\u0161tas: info@fernox.lt<\/p><p><\/p><p>Adresas: S. \u017dukausko g. 32-7, Vilnius<\/p>"},"id":"d89ce57d-1adf-4f4a-b082-1abebdc99b7d","isHidden":false,"type":"text"}],"id":"183a9a54-8723-4a29-8dec-4fac60f1d96b","width":"1\/2"},{"blocks":[{"content":{"title":"","name":"Vardas \/ \u012emon\u0117","email":"El. pa\u0161tas","phone":"Telefonas","message":"Papildoma informacija","buttontext":"Si\u0173sti"},"id":"2e8c1a2e-51de-4c5b-bcd1-2c50ece48df8","isHidden":false,"type":"contactform"}],"id":"99b084c3-8c9b-4999-a444-f7a46820ffb5","width":"1\/2"}],"id":"90df7d47-2761-4c74-a36e-4fcb0a641f6e"}]
````

Kirby 3.6.0-beta.3

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

In the end it was a combination of @nilshoerrmann's suggestion and what I had in mind. Thank you Nils for the inspiration!

Modifications were needed in two different places because:
1. `libxml` needs to be told to parse the input as UTF-8. A `<meta>` tag would create an empty `<head>` and converting everything to entities is a hack. The XML declaration works great and is the easiest to remove right afterwards.
2. If the `<meta>` tag is used and kept in the document, additional processing (e.g. in `$dom->sanitize()`) will think that it's part of the input. So everything we add needs to be removed immediately after parsing.
3. On output we need the `<meta>` tag again as it's the only way to avoid an export as `ISO-8859-1` with entities.

I also used the opportunity to integrate the output consistency improvements from the `Sane` classes into `Dom` to make sure that the `Dom::toString()` output matches the parsed input as closely as possible.

### Fixed regressions

- Unicode characters in the writer field are no longer converted to HTML entities.

### Enhancements

- The `Toolkit\Dom::toString` method now exports the document with the same structure as the input.

### Fixes

-  The `image/svg` MIME type is now recognized by the `Sane` classes

## Breaking changes

None

## Related issues/ideas

- Related to, but does not fix #3798.

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by lukasbestle** [comment]
@afbora Could you please also validate that the unsaved changes loop is fixed by this? I wasn't able to reproduce it.

**Comment by afbora** [comment]
@lukasbestle Unfortunately 🙁 I think this issue is also related to the writer field.

https://user-images.githubusercontent.com/3393422/139602437-830d57dd-80ad-4eeb-90c9-88363aac1551.mp4

**Comment by afbora** [comment]
It actually saves to content correctly. The following may give you an idea, when you refresh the page:

image (33)

**Comment by nilshoerrmann** [comment]
Have you thought about putting the api response into the DOM before comparing the values?

**Comment by afbora** [comment]
Replacing special characters in the writer field seems to fix it.

**Comment by lukasbestle** [comment]
@afbora I'm done refactoring the `Dom` class for output consistency. Now it shouldn't matter what you throw at it, you will always get an output with the same structure. I can now also reproduce the `writer` field issue and it's still there. So I think it's a separate issue not directly related to `Sane`.

**Comment by afbora** [comment]
Thank you. While @bastianallgeier is reviewing this PR, I will then create a PR for the solution I have in mind regarding the writer field issue.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
