### PR TITLE
Accessing with default language slug on multilang

### LINKED ISSUE #2257: In a multi-language setting, a non-default page version can be accessed both with the default language slug and its own translated slug.
**Describe the bug**  
Already done in the title

**To Reproduce**  
1. Create a multi-language Starterkit with two languages
2. Change the slug of a page in the non-default language
3. Access the page on the frontend.
4. Then change the page slug to the original default language slug in the address bar
5. Instead of showing the error page, the same page is still shown.

**Expected behavior**  
The same page should not be available under two URLs.

**Screenshots**  

**Kirby Version**  
Tested with 3.3.0-rc-3 but also happens in 3.2.5 (other versions not tested yet, didn't happen in older versions, though, as far as I remember).

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Fixed the issue with separated finding page in collection based on multilingual option.

## Related issues

- Fixes #2257 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Review by lukasbestle — DISMISSED** [review]
Awesome fix!

**Comment by distantnative** [comment]
Haven't tested it myself yet, but from reading the code: What happens if we are in a multilang setup, but there is not `slug` entry in the content file cause the slug has not been translated at all?

**Comment by afbora** [comment]
@distantnative Ahh, good point! Opening default page if page not translated yet. The bigger problem is that you cannot access the page of that language on the panel. I'll take a look again.

**Comment by afbora** [comment]
I have done a few tests now. Since the front side and the panel use the same methods, if we prevent it from opening at the front, it does not open at the panel. We may need to find a way to separate the two sides 🤔

**Comment by afbora** [comment]
Now we know the issue better so i'm closing for now to find stable solution.

**Pull request closed without merging**
