### PR TITLE
Upgrade Node dependencies

### PR DESCRIPTION
**Pull request by johannschopplich**
## This PR …

Upgrades all relevant Node.js dependencies by running `npx -y taze major -w`, with manually adjustment to exclude incrementing Vue to v3 etc.

Vitest was quite outdated. Concurrent tests can't access snapshots anymore, I had to adapt the component tests slightly.

```sh
eslint-plugin-vue        dev     ~4mo    ^8.4.1  →   ^9.0.1   ~13d  
dayjs                            ~9mo   ^1.10.7  →  ^1.11.2   ~25d  
prosemirror-commands             ~4mo    ^1.2.1  →   ^1.3.0    ~1d  
prosemirror-history             ~10mo    ^1.2.0  →   ^1.3.0    ~1d  
prosemirror-inputrules          ~1.7y    ^1.1.3  →   ^1.2.0    ~1d  
prosemirror-keymap               ~7mo    ^1.1.5  →   ^1.2.0    ~1d  
prosemirror-model                ~5mo   ^1.16.1  →  ^1.17.0    ~1d  
prosemirror-schema-list          ~8mo    ^1.1.6  →   ^1.2.0    ~1d  
prosemirror-view                 ~5mo   ^1.23.6  →  ^1.24.1    ~1d  
@vitest/ui               dev     ~5mo  ^0.0.124  →  ^0.13.0    ~2d  
cypress                  dev     ~4mo    ^9.4.1  →   ^9.7.0    ~8d  
eslint                   dev     ~4mo    ^8.8.0  →  ^8.16.0   ~11d  
eslint-config-prettier   dev    ~1.1y    ^8.3.0  →   ^8.5.0   ~3mo  
prettier                 dev     ~6mo    ^2.5.1  →   ^2.6.2   ~2mo  
vitest                   dev     ~4mo    ^0.3.2  →  ^0.13.0    ~2d  
vue-docgen-api           dev     ~4mo   ^4.44.2  →  ^4.47.0    ~3d  
autoprefixer             dev     ~5mo   ^10.4.2  →  ^10.4.7   ~29d  
c8                       dev     ~5mo   ^7.11.0  →  ^7.11.3   ~16d  
postcss-logical          dev     ~9mo    ^5.0.0  →   ^5.0.4   ~4mo  
vite                     dev     ~27d    ^2.9.8  →   ^2.9.9   ~20d  
vite-plugin-vue2         dev     ~1mo    ^2.0.0  →   ^2.0.1   ~13d  

```

### Fixes

Before:

```
dist/css/style.css   105.39 KiB / gzip: 17.91 KiB
dist/js/index.js     321.86 KiB / gzip: 77.43 KiB
dist/js/vendor.js    386.65 KiB / gzip: 121.63 KiB
```

After:

```diff
dist/css/style.css   105.39 KiB / gzip: 17.91 KiB
dist/js/index.js     321.86 KiB / gzip: 77.43 KiB
dist/js/vendor.js    370.00 KiB / gzip: 119.10 KiB
```

Vendors are reduced from `386.65` to `370.00` kB.

### Breaking changes

None.

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by johannschopplich** [comment]
@distantnative Prettier 2.6 introduces [a new `singleAttributePerLine` option to print only one attribute per line in Vue SFC templates](https://prettier.io/blog/2022/03/16/2.6.0.html). This one for you. 😉

**Comment by distantnative** [comment]
Thanks Johann, I haven't upgraded vitest recently as I keep running into broken unit tests as you can see with this PR. We'd need to get these working again first.

**Comment by bastianallgeier** [comment]
Yep, I had the exact same issue with the tests and I couldn't figure out what it was. Makes absolutely no sense why this stops working. But I really want that 15kb reduction in the vendor file :) Do you know where it comes from?

**Comment by johannschopplich** [comment]
I think either `dayjs` or `prosemirror` reduces the bundle. All the other upgraded dependencies are dev deps.

Tests failed earlier as well. Thus, we probably can upgrade `vitest`.

**Comment by distantnative** [comment]
He is right :D - but why did our Github checks not complain on releases.

Anyways, JS unit tests are still in their infancy. Let's merge this and get on fixing and extending them later.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
