### PR TITLE
Refactored table block and structure field

### LINKED ISSUE #3323: Table block: width in `columns` property ignored
**Describe the bug**  

In the preview of the table block (`blocks/table`) the width settings of the `columns` property are being ignored.

**To Reproduce**  
1. Create a block that extends `blocks/table`
2. Set column widths under the `columns` property
3. Use the block and add an entry
3. Look at the preview

Sample code:
```yaml
name: Tabelle
extends: blocks/table
fields:
  rows:
    type: structure
    columns:
      entry:
        width: 1/3
      description:
        width: 2/3
    fields:
      entry:
        type: text
        counter: false
        label: Eintrag
        width: 1/3
      description:
        type: writer
        label: Erläuterung
        marks:
          - bold
          - link
        width: 2/3
    label: Einträge
```

**Expected behavior**  

The columns having the set widths.

**Screenshots**  

Bildschirmfoto 2021-05-12 um 17 08 37

**Kirby Version**  

3.5.5

**Console output**  

No console output.

**Desktop (please complete the following information):**  
 - OS:  macOS
 - Browser:  Google Chrome
 - Version:  90.0.4430.212

### LINKED ISSUE #3324: Table block: writer field output in preview not correct
**Describe the bug**  

In the preview of the table block (`blocks/table`) the output of the writer field is not correct. The HTML tags are visible and not applied.

**To Reproduce**  
1. Create a block that extends `blocks/table`
2. Add a writer field to the `fields`
3. Use the block, add an entry and enter something in the writer field
3. Look at the preview

Sample code:
```yaml
name: Tabelle
extends: blocks/table
fields:
  rows:
    type: structure
    columns:
      entry:
        width: 1/3
      description:
        width: 2/3
    fields:
      entry:
        type: text
        counter: false
        label: Eintrag
        width: 1/3
      description:
        type: writer
        label: Erläuterung
        marks:
          - bold
          - link
        width: 2/3
    label: Einträge
```

**Expected behavior**  

The content of the writer field being rendered correctly.

**Screenshots**  

Bildschirmfoto 2021-05-12 um 17 08 37

**Kirby Version**  

3.5.5

**Console output**  

No console output.

**Desktop (please complete the following information):**  
 - OS:  macOS
 - Browser:  Google Chrome
 - Version:  90.0.4430.212

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

I moved the common methods used by the structure field and the table block into mixins (`/mixins/forms/structure.js`)

@distantnative , I'm waiting for your review before marking PR as ready.

### Fixes
- Fixed `width` prop of columns in table block preview
- Fixed preview output in table block preview

### Enhancements
- Table block and structure field refactored to display properly in block table

## Breaking changes

None

## Related issues/ideas

- Fixes #3323 
- Fixes #3324 

## Ready?

- [ ] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Review by texnixe — DISMISSED** [review]
Works fine in my tests

**Comment by distantnative** [comment]
Tbh, I have worked so little (not at all) with blocks that I'm probably not the right one to review this. @texnixe knows much more about blocks, so I'd trust her much more

**Comment by distantnative** [comment]
But ideally we don't include `dist` files in the PRs, they often lead to merge conflicts with other PRs otherwise.

**Comment by afbora** [comment]
@distantnative I'll revert the dist files. i pushed it for @texnixe to test. So, are the implementation style and code structure correct? 🤔

**Comment by afbora** [comment]
- PR rebased.
- Dist files reverted. 
- Ready to review and merge.

**Comment by bastianallgeier** [comment]
@afbora can you base this off the releases/3.5.7 branch instead of develop?

**Comment by afbora** [comment]
Closing favor of  new PR #3411

**Pull request closed without merging**
