### PR TITLE
Move RTL CSS rules to separate file

### PR DESCRIPTION
**Pull request by distantnative**
- Transforms all CSS Logical Properties to old (left, right etc.) options without preserving the logical props
- Makes LTR baked-in default of CSS values
- Splits RTL rules into a separate file

```
dist/css/style.css   106.70kb / brotli: 14.88kb
dist/js/index.js     316.04kb / brotli: 60.11kb
dist/js/vendor.js    379.32kb / brotli: 103.63kb

Post-processing CSS...

dist/css/style.css      106.7 KB
dist/css/rtl.css         12.2 KB
```

## TODOS
- [ ] `rtl.css` doesn't get loaded when user changes languages
- [ ] Problems with `inset` shorthand

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Something is weird. When I check out this PR and try to get it running, styles are completely broken. Is it dependent on anything else?

**Comment by distantnative** [comment]
Caching issue maybe?
Seems to work fine for me. You see the problem with `npm run dev` or `build` ?

**Comment by bastianallgeier** [comment]
With npm run dev. I tried cleaning the cache, deleting the media folder, etc. but no luck.

**Comment by distantnative** [comment]
Ok something must've been stuck in my cache... now I see it too :(

**Comment by distantnative** [comment]
Ok it seems there is a bug in `postcss-logical` with `inset-inline`... investigating

**Comment by distantnative** [comment]
@bastianallgeier better?

**Comment by bastianallgeier** [comment]
Most stuff looks good now, but drawers are still a mess.

**Comment by bastianallgeier** [comment]
I've fixed it but I'm not sure if this is the way you would do it in the directive.

**Comment by distantnative** [comment]
Why the directive on the overlay? The directive is based on the content language not UI

**Comment by bastianallgeier** [comment]
Oh, I completely misunderstood it 🙈

**Comment by distantnative** [comment]
This feels a bit like a dead end - closing it until we find a better approach.

**Pull request closed without merging**
