### PR TITLE
Expose $library and $helper #1846

### LINKED ISSUE #1846: Panel: expose libraries to plugins
Such as dayjs

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
Exposes libraries and helpers via `this.$library.` and `this.$helper.`.
Also switched to using them within our own code.

## Related issues
- Fixes #1846

### CODE REVIEW

**Review by bastianallgeier — DISMISSED** [review]
That looks absolutely lovely <3

**Comment by distantnative** [comment]
Note to myself: Make sure to add new helpers from 3.2.5 first.

**Review by bastianallgeier — APPROVED** [review]

**Comment by distantnative** [comment]
@bastianallgeier did you add the new helper from 3.2.5 as well?

**Comment by bastianallgeier** [comment]
@distantnative The only one that's missing is the previewThumb thing, but I don't know if it is that useful in its current state. It's pretty specific.

**Pull request merged**
