### PR TITLE
Add language specific UUID URLs

### PR DESCRIPTION
**Pull request by bastianallgeier**
## This PR …

This is an attempt to finally get parts of the multi-language UUID issues solved. (https://github.com/getkirby/kirby/issues/5551)

This adds a new route for language-specific UUID urls: 

Examples: 
```
/en/@/page/1234
/en/@/file/1234
```

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
Either we should add unit tests or we should be more explicit what we want to ignore for coverage.

**Comment by bastianallgeier** [comment]
@distantnative I'm trying to create tests for the UUID route but I fail to setup a test environment with working UUIDs. Could you maybe have a look at the test? Why can the model not be found like that?

**Comment by distantnative** [comment]
Had you tried manually adding a uuid in the app setup `['content' => ['uuid' => 'my-uuid']]`? That's how many of the other tests do it.

**Comment by bastianallgeier** [comment]
Yep, I tried that too but also without luck.

**Comment by distantnative** [comment]
@bastianallgeier Ok I finally understood where it fails:
- The uuid route looks up the model lazily, so only from cache. Since the cache is not populated, it fails
- When I was trying to manually set a UUID, I did it with `content`. But we are in multilang territory, so we have to set the `translations` array instead

Alternatively, solving https://github.com/getkirby/kirby/issues/5181 too.

**Comment by distantnative** [comment]
@bastianallgeier Apparently, sometimes it takes months to realize what one is overlooking. I even wrote

> Since the cache is not populated, it fails.

But only today it clicked that, well yea then we need to add a `$uuids->populate()` line to add it to the cache.

**Review by distantnative — DISMISSED** [review]
@bastianallgeier Please check if the unit test is testing the right things from your perspective.

**Comment by bastianallgeier** [comment]
@distantnative yes, looks good to me! I can't believe that we might actually be able to merge this :)

**Review by distantnative — APPROVED** [review]

**Pull request merged**
