### PR TITLE
Refactored tabs component (+ unsaved changes badges) + fix

### LINKED ISSUE #2742: [Panel] Link in tab jumps to first tab before following route
Kirby 3.4.0 reintroduced the issue #1389.

**Sample reproduced blueprint for starterkit**

````yaml
title: Sandbox

tabs:
  content:
    label: Content
    fields:
      text:
        type: textarea
        size: huge
        
  test:
    label: Test
    sections:
      notes: sections/notes
````

**Kirby Version**  
3.4.0

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

- Refactors `k-tabs` as "dumb" component (so it can also be used in other scenarios by developers)
- Simplifies setup in conjunction with `k-sections`
- Adds messages for missing blueprints for site, page and file
- Adds badges for unsaved changes in tab on tab

Also fixes #2742

### CODE REVIEW

**Comment by distantnative** [comment]
@bastianallgeier rebased :)

**Comment by bastianallgeier** [comment]
I fixed a few things, but batches don't really work properly for me and I'm not sure why. I was thinking about removing them again from this PR to finalise the tabs first and then add them later. What do you think?

**Comment by bastianallgeier** [comment]
BTW: I've created a tabs environment in the sandbox to test different tab scenarios for site, pages, files and users.

**Comment by bastianallgeier** [comment]
Ah, I found a fix for the badges. Let's keep them in there for now. We can still remove them later if needed.

**Pull request merged**
