### PR TITLE
Improve input disabled styles

### LINKED ISSUE #6163: Date field: don't show placeholder when disabled
Potentially also relevant for other fields that have default placeholders...

I think when a (date) field is disabled, there should be no placeholder shown, but empty fields:

Screenshot 2024-01-16 at 21 46 12

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Disabled inputs don't show placeholders anymore
- Choice inputs have similar disabled styling as other fields
- #6163

### For review team

- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Instead of adding logic to the component, could we simply use CSS to hide the placeholder?

**Comment by distantnative** [comment]
@bastianallgeier added a version with CSS.

**Comment by bastianallgeier** [comment]
I think the CSS solution is a lot better. What do you think? I was wondering though if this is so global that we could actually put it in the reset.css for all inputs or would that be too aggressive? I'm not 100% sure.

**Comment by distantnative** [comment]
@bastianallgeier that could lead to unwanted consequences for plugins, I fear

**Comment by bastianallgeier** [comment]
You are right!

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
