### PR TITLE
Options refactoring to fix double-escaping issues

### LINKED ISSUE #3955: Translation failed on select fields
External translation not work on select fields:
```
foo:
  label: path.to.translation.label
  type: select
  options:
    option1: path.to.translation.option1
    option2: path.to.translation.option2
```
The panel shows the path in the dropdown.

### LINKED ISSUE #4043: Special characters in tags field saved escaped when selected using autocomplete
## Description
I have a tags field that gets its options from a query:

```yaml
fields:
  bikeManufacturer:
    type: tags
    max: 1
    options: query
    query: page.parent.childrenAndDrafts.pluck('bikeManufacturer', ',', true)
    required: true
```

When I save a tag featuring an ampersand (e. g. “Riese & Müller“) it gets saved correctly. But when I then go to a sibling page and select that same value from the autocomplete options, it’s getting saved and output as `Riese &amp; Müller`.

**Expected behavior**  
The value being saved just like the original.

## To reproduce

1. Create a blueprint using the YAML provided above.
2. Add a page and save a value featuring an ampersand in the tags field.
3. Create a second page and select the previously saved value from the autocomplete options.
4. Create a third page and look at the provided autocomplete options or the value in the just saved txt file of the second page.

## Your setup
**Kirby Version**  

3.6.1.1

**Console output**  

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 12.0.1
 - Browser: Google Chrome
 - Version: 96.0.4664.110

Maybe related to #4041.

### LINKED ISSUE #4229: Panel: Multiselect field searches through literally encoded html entities (e.g. `&amp;`)
## Description
When searching in the `multiselect` field for something like "a" results start showing things for `&amp;`

The might be related to #4041 and/or #4043.

**Expected behavior**  

Results should always retain their original titles and I wouldn't expect searching the encoded entities.

**Screenshots**  

Screen Shot 2022-03-24 at 12 56 51 PM

https://user-images.githubusercontent.com/417182/159999625-ed62974c-11f8-404b-8fa3-57e580785166.mov

## To reproduce

```yaml
          channelUIDs:
            label: Channels
            type: multiselect
            search:
              display: 10
            options: query
            query:
              fetch: 'kirby.collection("channels")'
              text: "{{ page.title }}"
              value: "{{ page.uid }}"
```

## Your setup
**Kirby Version**  

`3.6.3.1`

**Console output**  

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS
 - Browser: Safari
 - Version: Version 15.4 (17613.1.17.1.6)

**Additional context**

### LINKED ISSUE #4590: Tags field loses content when saving
## Description
When saving the page directly after typing some text, the tags field will disregard the input. You have to blur the field or press enter to actually trigger a change.

**Expected behavior**  
The field should not lose content.

**Screenshots**  

tags

## To reproduce

1. Add a tags field to your blueprint
2. Enter some text
3. Hit ⌘S or Ctrl + S depending on your OS

## Your setup
**Kirby Version**  
3.7.4-rc.1

### LINKED ISSUE #4638: Tags field: input doesn't get separated on blur
Maybe I add this to the same issue, as this is closely related. When enter some comma separated tags and then instead of hitting enter, I click outside the field, the tags will visually show as one big, merged tag:

Bildschirmfoto 2022-09-12 um 16 22 27

They are correctly saved to the content file though and when I leave the page and then navigate back to it, they show correctly again:

Bildschirmfoto 2022-09-12 um 16 23 20

When I hit enter in the tag field, the tags are separated correctly directly.

_Originally posted by @trych in https://github.com/getkirby/kirby/issues/4590#issuecomment-1243820783_

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

This PR implements a few principles to options-supporting fields:
- backend and frontend always only exchange raw values for the value prop (array of strings), no text etc
- the option prop is the one providing a list of value-text entries 
- values must never be escaped but also must never be displayed via `v-html` in the Panel
- dynamic options (from API or query) escape their text unless using `{< >}`
- most fields only support values that can be matched to an option, only tags field can allow non-option values

### Fixes
- Tags field separates tags on blur correctly
https://github.com/getkirby/kirby/issues/4638
- Tags field don't loose current input when hitting Cmd+S
https://github.com/getkirby/kirby/issues/4590
- Various escaping issues for fields with options
  - https://github.com/getkirby/kirby/issues/4043
  - https://github.com/getkirby/kirby/issues/4229

### Enhancements
- Easily translate options via an i18n key
https://github.com/getkirby/kirby/issues/3955
```yaml
# via `*` pseudo locale
options:
  a:
    *: my.i18n.key.a
  b:
    *: my.i18n.key.b

# via `t()` query helper
options:
  a: "{{ t('my.i18n.key.a') }}"
  b: "{{ t('my.i18n.key.b') }}"
```

(The latter only works in conjunction with https://github.com/getkirby/kirby/pull/4626)

### Refactoring
- Adds a new `Option` namespace with refactored options classes
- Adds several related classes as back port from 3.9 (e.g. in `Blueprint`, `Field`...) - test coverage deactivated until 3.9 for these

- New blueprint syntax for options (with polyfills for the old syntax):
```yaml
# manual options
# shorthand
options:
  - a
  - b
  - c

# long form
options:
  type: array
  options:
    - a
    - b
    - c
 
# api
options:
  type: api
  url: https://api.getkirby.com
  query: Companies
 
# query
options:
  type: query
  query: site.contactoptions.toStructure
  text: "{< item.nameWithHtml >}"
  value: "{{ item.twitter }}"
```

### Deprecations
- `Kirby\Form\Options`, `Kirby\Form\OptionsApi`, `Kirby\Form\OptionsQuery` have been deprecated and will be removed in Kirby 3.9

### Breaking changes
- Multiselect field does not display option value as info

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
@distantnative I can no longer use it as below. Is there a bug or has the syntax changed completely? If so, can you give a few different new usage examples?

````yaml
fields:
  optionQueries:
    label: Option queries
    type: select
    options: query
    query: site.children.published
````

> The $data prop has been deprecated for initiating the Query class and will be removed in Kirby 3.9. Instead, pass data as parameter to the resolve method: Query::factory($query)->resolve($data) in file: \test\kirby\4626\kirby\src\Cms\Helpers.php line: 30

**Comment by afbora** [comment]
Sorry, I mixed with `New Query classes: t() query function, closure arguments` PR 🙈

**Comment by afbora** [comment]
Simple multiselect field throws error
> Sortable: `el` must be an HTMLElement, not [object Comment]

````yaml
fields:
  multiselect:
    label: Multiselect
    type: multiselect
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
````

**Review by bastianallgeier — DISMISSED** [review]
It looks good to me from what I can see by going through the code. We already discussed to add more test setups to the sandbox and I hope we can find as many potential issues as possible there and in the RC phase.

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
I think it's time to merge this. If there are still issues we can fix them in additional PRs later.

**Comment by afbora** [comment]
> I think it's time to merge this. If there are still issues we can fix them in additional PRs later.

I was just starting to test on it 😅 
I've found two issues but I'm not sure about this issues related with this PR. I can create new issues if you want.

1. Simple tags field escaping when editing

````yaml
tags:
  label: Tags
  type: tags
````

tags-field-issue

2. Error on related field is empty

If the related field is empty, it gives an error. Instead, the field is expected not to offer any options.

> Invalid query result data: Kirby\Cms\NestObject in file: test\kirby\4624\kirby\src\Option\OptionsQuery.php line: 143

````yaml
tags_from_other_field:
  label: Tags (Options from other fields)
  type: tags
  options: query
  query: page.tags.split
````

**Comment by distantnative** [comment]
@afbora let's open issues for these, so we can track them better to fix until release (RC or final)

**Comment by afbora** [comment]
@distantnative OK. Separately or both in the same issue?

**Comment by distantnative** [comment]
best even separately

**Comment by sebastiangreger** [comment]
I don't have the resources right now to create a complete ticket with reproducible step-by-step code etc., but want to mention this nevertheless as this was a really hard nut to crack:

In 3.7 I was using this blueprint field definition, pulling in a plain array of tags using a site method:

```
tags:
  type: tags
  label: Tags
  options: query
  query:
    fetch: site.fieldcache('tags')
    text: "{{ arrayItem.value }}"
    value: "{{ arrayItem.value.slug }}"
```

The data returned by `$site->fieldcache('tags')` is of format:

```
[
  0 => 'tag1',
  1 => 'tag2',
  2 => 'tag3',
  // etc.
]
```

This no longer works in 3.8.0-rc.2 and actually leads to a very long loading time for the panel pages baring such field (is the server side of the Fiber exchange getting choked up on this in the background?). I had to change it to this in order to get my tag suggestions back and get rid of the long loading times:

```
tags:
  type: tags
  label: Tags
  options: query
  query: site.fieldcache('tags')
```

**Comment by distantnative** [comment]
@sebastiangreger please add this to a new issue ticket nevertheless. It's really hard to keep track of such comments on already merged PRs. Thanks!

**Comment by sebastiangreger** [comment]
> @sebastiangreger please add this to a new issue ticket nevertheless. It's really hard to keep track of such comments on already merged PRs. Thanks!

Sure, I fully understand! #4739

**Pull request merged**
