### PR TITLE
Fixes object field related console errors

### LINKED ISSUE #4681: [3.8.0-rc.1] new object field some console errors
Sorry for overlooking the errors in the console before the PR merged.

### Few issues 

1. When first click add and open the drawer

> Uncaught TypeError: Cannot read properties of undefined (reading 'isOpen')
> Uncaught TypeError: Cannot read properties of undefined (reading 'open')

2. When click `tags` field

> Uncaught TypeError: Cannot read properties of undefined (reading 'focus')

### Sample blueprint

````yaml
fields:      
  person:
    label: Person
    type: object
    fields:
      category:
        label: Category
        type: multiselect
        options:
          design: Design
          architecture: Architecture
          photography: Photography
          3d: 3D
          web: Web
      name:
        type: text
      pages:
        type: pages
      files:
        type: files
      tags:
        type: tags
````

### PR DESCRIPTION
**Pull request by afbora**
Fixes #4681 

I'm not 100% sure this is the solution. Because it contains specific changes to solve only related problem.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
This PR breaks the autofocus feature in the drawer.

**Comment by bastianallgeier** [comment]
@afbora I fixed it a bit differently. I think the setTimeout is the root cause of the issue, but one nextTick isn't enough. I reverted your changes to the MultiSelect Input because they aren't needed if the field is created correctly. Could you check if it works for you with this fix?

**Comment by afbora** [comment]
@bastianallgeier Same..

screen-capture-1456-Sandbox - Kirby Demo-localhost

Also console errors

> TypeError: Cannot read properties of undefined (reading 'open')
> Uncaught TypeError: Cannot read properties of undefined (reading 'querySelector')

**Comment by bastianallgeier** [comment]
I don't get it. How can this be so different between Win and Mac? Sorry for force-pushing over your PR? Do you still have the local branch? Could you force-push again to overwrite my stuff?

**Comment by afbora** [comment]
Unfortunately not. Because I updated my local to test it 😅

**Comment by bastianallgeier** [comment]
Yikes, so sorry! I will try to reconstruct it.

**Comment by bastianallgeier** [comment]
I've reimplemented the changes. Could you please have a look at them if I missed anything. I also simplified the focus code again and increased the timeout. This should make the focus method more reliable when it relies on elements being there.

**Comment by afbora** [comment]
Seems only `tags` field focus issue left (when click tags preview on object field)

> Uncaught TypeError: Cannot read properties of undefined (reading 'focus')

**Comment by afbora** [comment]
While there is no such issue in the structure or blocks field, I still could not understand why we had this error in the object field.

**Comment by bastianallgeier** [comment]
@afbora could you take care of the tags focus issue. I'm not entirely sure what you mean? I also have absolutely no idea why it happens here.

**Comment by afbora** [comment]
@bastianallgeier I've pushed a commit that fix the tags field issue but I'm still not sure about the solution. I don't understand why it gives this error only in object field 🤷‍♂️

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
@afbora I think we will meet this again when we move the structure field to the drawer. The changes right now seem pretty solid and I would go for it and wait what else turns up later.

**Pull request merged**
