### PR TITLE
Use srcset for panel thumbs

### LINKED ISSUE #1520: [Panel] Blurry images in image section
**Describe the bug**
We are using an image section limited to a single image in the main column of our page (2/3 width). The layout is set to cards in order to have a large preview of the cover image.

Generally, everything displays as expected but Kirby is loading a small image scaling it up to the needed size which results in a very blurry preview. The source image is 2560 × 1600 pixels.

grafik

Setting `size: large` has no effect. The maximum image width seems to be 400 pixels.

**To Reproduce**
Simplified blueprint:

```yml
title: Projekt
sections:
  cover:
    type: files
    headline: Titelbild
    template: cover
    layout: cards
```

**Expected behavior**
The image should not be scalled and display in correct resolution.

**Kirby Version**
Kirby 3.0.3-rc.1 using Firefox on macOS Mojave.

### PR DESCRIPTION
**Pull request by distantnative**
@bastianallgeier currently the original is loaded in `src`- probably not ideal.

## Related issues
- Fixes #1520

### CODE REVIEW

**Comment by nilshoerrmann** [comment]
Is there a reason why not to use a srcset here and let the browser choose the best size? I'm asking because the layout is changing responsively and so do the image display sizes.

**Comment by distantnative** [comment]
@nilshoerrmann I thought it would be a much bigger effort and wanted a quick fix... turns out it might be much simpler than I thought. I just pushed a first draft too this PR.

**Comment by nilshoerrmann** [comment]
Cool, thanks!

**Review by bastianallgeier — APPROVED** [review]
This is such a good idea and so much cleaner 👏

**Pull request merged**
