### PR TITLE
UUIDs: case-insensitive IDs

### PR DESCRIPTION
**Pull request by distantnative**
### Enhancement
- UUIDs are fully lowercased now to avoid issues between filesystems handling casing differently
https://github.com/getkirby/kirby/issues/6232

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
`Question`: This only affects newly generated ones, right? The existing UUID cache can be reused? Do you think we are risking more collisions though?

**Comment by distantnative** [comment]
@bastianallgeier Yes only newly generated ones. For collision chance, see https://github.com/getkirby/kirby/issues/6232#issuecomment-2016814710/

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
@distantnative do you want a second opinion from @lukasbestle? Otherwise, I'm fine to merge it.

**Comment by distantnative** [comment]
Merging is fine, I think, as this PR is 1:1 what Lukas suggested in the issue.

**Pull request merged**
