### PR TITLE
Languages dropdown: badge for translation changes

### PR DESCRIPTION
**Pull request by distantnative**
### Summary of changes
- Shows badge on languages dropdown button whether any translations have unsaved changes

### Enhancement
- Panel: Languages dropdown indicates whether any translations have unsaved changes

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
This is really cool. For some reason, I don't get it to show the real count of changed languages though.

**Comment by distantnative** [comment]
@bastianallgeier it doesn't count the current viewed into. Only how many other languages have changed. Does that explain what you see?

**Comment by bastianallgeier** [comment]
Oh, yes. That explains it. But for my taste, it would need to include the current one as well. Especially when we show the changes in the dropdown later too. I think if you open the dropdown and two languages show changes in there, but the badge only says 1 it would feel wrong.

**Comment by distantnative** [comment]
I didn't include it in the beginning as new changes to the current view wouldn't be reflected from what was loaded from the backend. But I think hat we could solve by sending the same number as now from the backend and adding `+1` if the current view has `$panel.content.hasChanges`.

It's still a bit distracting visually that so many things suddenly change when there are no changes at all and one adds the first change to the current view, but I understand that the PR as is right now is also confusing.

**Comment by bastianallgeier** [comment]
Without wanting to create extra work, maybe we should take a step back here. What happens for example when you are in a view with tabs and the tabs each also have badges with counters? I was just wondering if we could use a badge without showing a number at all. Maybe just the badge or a badge with a tiny edit icon or something. Omitting the numbers could help to simply indicate "Something has changed here" and let the dropdown then have more information.

**Review by bastianallgeier — APPROVED** [review]
I really like it with the minimal style!

**Pull request merged**
