### PR TITLE
Update check: hide button if no url

### LINKED ISSUE #4716: [3.8.0-rc.2]: Update check - don't show "version info" button when no info
Currently, the button gets only disabled. Which is rather confusing as one has only one dropdown open and can't quite realise the difference between active/disabled right away. Button should simply be hidden when not available.

Screenshot 2022-09-28 at 19 34 25

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- https://github.com/getkirby/kirby/issues/4716

Screenshot 2022-09-28 at 19 53 45

Screenshot 2022-09-28 at 19 53 41

### CODE REVIEW

**Comment by lukasbestle** [comment]
Not sure TBH. We disable buttons throughout the UI for any feature that is possible but currently not available.

A missing button is IMO more confusing than helpful. A user may think "wait a second, wasn't there a button recently? Why is it gone?" without realizing that other plugins may have that button. Hiding buttons is certainly a possibility, but it's confusing because we don't do it anywhere else.

**Comment by distantnative** [comment]
I literally tried to click a disabled button for 15 seconds and thought Vue was broken, because I didn't at all realise its state could be disabled. A user does not have the background knowledge that these buttons can be presented enabled/disabled. Due to the nature of the dropdown a user also only sees one button at a time. Our disable state is not recognisable as disabled on top of a black background if you only see one disabled button with no comparison to an enabled styling.

We might want to solve this differently. But the current UI is a very broken UX.

**Comment by lukasbestle** [comment]
Yeah, that makes sense. I'm not against the change, let's see what the others think.

**Comment by afbora** [comment]
> I literally tried to click a disabled button for 15 seconds and thought Vue was broken, because I didn't at all realise its state could be disabled.

Same 🙈 I already thought of suggesting this but then gave up. Now I totally agree with @distantnative 👍

**Comment by bastianallgeier** [comment]
I think it makes a lot of sense here to remove the button entirely. Related question but for a different PR: why don't we link to the 1.0.0 version in the example above?

**Review by bastianallgeier — APPROVED** [review]

**Comment by lukasbestle** [comment]
> Related question but for a different PR: why don't we link to the 1.0.0 version in the example above?

@bastianallgeier Because we don't know the repo URL for that (no data on getkirby.com).

**Comment by bastianallgeier** [comment]
Ah, that makes sense.

**Pull request merged**
