### PR TITLE
Fix fullwidth tabs (Fix #1999)

### LINKED ISSUE #1999: [Panel] Tabs are displayed full width
**Describe the bug**
Tabs in the Panel are displayed full width instead of left aligned.

**Screenshots**
grafik

**Kirby Version**
Kirby 3.2.3

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR
Tabs now keep their normal width again

## Related issues
- Fixes #1999

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
Not entirely my ball park, but one potential issue came to my mind: What if the label in the tab is too long for `15rem`? Maybe it's fine because it's more important visually to have the tabs equally sized, but I'm wondering how it worked before the change that broke it.

**Comment by nilshoerrmann** [comment]
Isn‘t this the use case [`flex-basis`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis) was made for?

**Comment by bastianallgeier** [comment]
The old version before the regression cut the labels and also caused weird padding issues. After my fix in this PR the labels simply wrap when they are too long. Still looks ok.

**Review by lukasbestle — APPROVED** [review]
That should be fine then!

**Pull request merged**
