### PR TITLE
Remote: Validate TLS certs by default

### LINKED ISSUE #2653: CURLOPT_SSL_VERIFYPEER disabled in Remote::fetch()
Hello,

I just took a look at `Remote::fetch()` due to some forum question and I noticed that `CURLOPT_SSL_VERIFYPEER` is set to `FALSE` by default. Is there a reason why this security feature is disabled by default? I would have expected SSL cert validation to be enabled by default or to find some information why this is disabled but I found nothing about this.

See this line: https://github.com/getkirby/kirby/blob/6bd14bc8099d6c9dbe67ef0582b8c0a2d4c0888c/src/Http/Remote.php#L152

I'm sorry if this should have been posted in the forum or if it's an obvious misunderstanding on my side.

Best Regards,

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

**Note:** This PR depends on #2660.

The `Http\Remote` class now validates the TLS certificate of the remote server by default. Kirby ships with a CA bundle based on the Mozilla CA list. We keep that CA bundle up-to-date.

It is also possible to use a different CA bundle by configuring it in `site/config.php`:

```php
<?php

return [
    'remote.ca' => ...
];
```

Options are:

- An absolute path to a CA file in `.pem` format
- An absolute path to a CA directory with certificate files that cURL can understand
- The special value `Remote::CA_INTERNAL` for Kirby's internal CA (default)
- The special value `Remote::CA_SYSTEM` to use the CA bundle that is configured in `php.ini`
- `false` to disable validation completely (not recommended)

## Related issues

- Fixes #2653

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by GiantCrocodile** [comment]
Is it possible to combine these options @lukasbestle? It might make sense to have e. g. system's CA bundle + Kirby 3's or one from an URL + Kirby 3's. This would make sure you don't have to build custom CA bundle packages if you need a combination.

**Comment by lukasbestle** [comment]
@GiantCrocodile cURL does not support multiple CA files or directories, there can only be one of each type. So the use-case is pretty limited.

**Comment by GiantCrocodile** [comment]
I see. You are right. It's a limitation in openSSL library used by cURL: https://curl.haxx.se/mail/lib-2012-07/0214.html.

Thank you for the improvement :)!

**Comment by lukasbestle** [comment]
For most use-cases the new implementation should be fine as the bundle that now ships with Kirby includes all CAs that are also supported by browsers. So basically every public domain should be covered. If you do need to make a request to an internal host that uses a self-signed or mTLS certificate, you can pass the correct `ca` option to the `Remote` class just for that request.

**Comment by GiantCrocodile** [comment]
True, excellent argument @lukasbestle. I'm very eager to see 3.4.0 released; although some fixes to the editor plug-in would be nice too :).

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
