### PR TITLE
3.5.5-rc.1

### PR DESCRIPTION
**Pull request by bastianallgeier**

### CODE REVIEW

**Comment by afbora** [comment]
1. `panel/package-lock.json` file deleted, is this intended?
2. FYI: the `tr` language file is out of date. I updated it on Transifex yesterday. No problem for now, we can update it while stable release.

**Comment by bastianallgeier** [comment]
@afbora the package-lock.json is still there. Github just seems to have a new type of changes viewer for it. I don't really understand why transifex is not giving me the latest tr file. I will try again.

**Comment by bastianallgeier** [comment]
Ok, should be fixed now. I have to actually send a force flag when downloading translations again.

**Comment by afbora** [comment]
`+283 −16.908` spoiled my perception on `package-lock.json` 🙈

**Review by afbora — APPROVED** [review]

**Pull request merged**
