### PR TITLE
Fix infinite loop: FileVersion asset methods #3347

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

Fixes regression introduced by the `Filesystem` PR. Infinite loop would appear e.g. after uploading an avatar. This line https://github.com/getkirby/kirby/blob/2970a28/src/Cms/FileVersion.php#L40 would cause the invite loop to `FileVersion::__call()`. Adding `IsFile::exists()` will prevent this.

## Related issues/ideas

- Fixes https://github.com/getkirby/kirby/issues/3347

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~
- [x] ~~Add changes to release notes draft in Notion~~

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
We could alternatively fix this with `$method !== 'exists' && $this->exists() === false` in https://github.com/getkirby/kirby/blob/2970a28/src/Cms/FileVersion.php#L40. Then we wouldn't need to add another method. Both have advantages and disadvantages. What do you think?

**Comment by distantnative** [comment]
I think I find adding the method a bit cleaner. The other one seems a bit like a hack and probably a bit confusing to read down the road.

**Comment by lukasbestle** [comment]
OK, but I think there should be a test for the infinite loop then to avoid that we remove the method later by accident because we see it as an unneeded duplicate.

**Comment by distantnative** [comment]
So I would've thought this is a proper test:

```php
    public function testExists()
    {
        $original = new File([
            'filename' => 'test.jpg',
            'root'     => __DIR__ . '/fixtures/files/test.jpg'
        ]);

        $version = new FileVersion([
            'original' => $original,
            'root'     => __DIR__ . '/fixtures/files/test-version.jpg',
            'modifications' => [
                'width' => 50,
            ]
        ]);

        $this->assertFalse($version->exists());

        // calling an asset method will trigger
        // `FileVersion::save()` if it doesn't
        // exist yet
        $this->assertSame(128, $version->width());

        $this->assertTrue($version->exists());
    }
```

But it fails with

```
Exception: File not found: kirby/tests/Cms/Files/fixtures/files/test-version.jpg
```

If I set `root` of `$version` to `__DIR__ . '/fixtures/files/test.jpg'`, the first assert fails, cause the file already exists. So I am thinking whether we have a logical problem here: We call `FileVersion::save()` in https://github.com/getkirby/kirby/blob/2970a28/src/Cms/FileVersion.php#L40 when the `root` does not exist, but `$kirby->thumb()` which is called in `FileVersion::save()` seems to require that `root` exists.

**Comment by lukasbestle** [comment]
@distantnative The `Darkroom` thumb engine overwrites thumbs in place, so it expects that the file already exists. This is done inside the `thumb` component with `F::copy()`.

The issue is that `Cms\File` has a `setRoot()` method that is useless on purpose. So the `root` is actually not set, which results in a root `/dev/null/content/test.jpg`, which then means that the file cannot be copied.

This works:

```php
    public function testExists()
    {
        $page = new Page([
            'root' => __DIR__ . '/fixtures/files',
            'slug' => 'files'
        ]);

        $original = new File([
            'filename' => 'test.jpg',
            'parent'   => $page
        ]);

        $version = new FileVersion([
            'original' => $original,
            'root'     => __DIR__ . '/fixtures/files/test-version.jpg',
            'modifications' => [
                'width' => 50,
            ]
        ]);

        $this->assertFalse($version->exists());

        // calling an asset method will trigger
        // `FileVersion::save()` if it doesn't
        // exist yet
        $this->assertSame(50, $version->width());

        $this->assertTrue($version->exists());
    }
```

But please put the `test-version.jpg` file into `tmp` instead of `fixtures/files`. Then the `tearDown()` method of the test class can just `Dir::remove(__DIR__ . '/tmp')`.

**Comment by distantnative** [comment]
✅

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
