### PR TITLE
 Add `content.locking` option and lower frequency #2000

### LINKED ISSUE #2000: Content locking stalling local dev server
**Describe the bug**
For testing purposes I had a lot of panel tabs open and the sheer amount of lock requests was stalling my local dev server.

In a test on my machine I had around 15 panel tabs open. At this time the response time was around 3-5s. After closing all tabs (red line) except one the response time dropped to around 400-500ms.

62860120-71984e00-bcff-11e9-8740-eb4082fd29c1
Since this is probably just an edge case in local development a simple config setting could suffice to disable the locking mechanism.

Another idea would be to make use of the [visibility api](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API?redirectlocale=en-US&redirectslug=DOM%2FUsing_the_Page_Visibility_API) to enable or disable the lock polling depending on the tab visibility. But this could potentially cause other issues.

**Kirby Version**
3.2.2

**Desktop**
 - Windows 10
 - Local PHP Server
 - Firefox

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
As reported, pinging the API every 5 seconds could cause heavy loads with many tabs open. I think we are fine by just checking every 15 seconds and setting the lock every 40 seconds. Protected period now would be 200 seconds.

## Related issues
- Fixes #2000

### CODE REVIEW

**Review by lukasbestle — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Comment by afbora** [comment]
@distantnative `content.locking` default is `false` so `disabled`, right?

**Comment by lukasbestle** [comment]
@afbora No, it‘s enabled by default:

https://github.com/getkirby/kirby/pull/2025/files#diff-5969670d929f8fb659bd1d375d73acacR273

**Comment by afbora** [comment]
Hmm i guess the locking process has changed a bit. 
Previously, it was locking continuously and periodically. 
Now, as far as I can see;

1. If no `locking` setting, it only locks when changes are made.
2. Continuous and periodic locking if set to true
3. Doesn't lock if set to false

And I like this logic 👍

**Comment by distantnative** [comment]
I am not sure if I understand your description. It was always and still should be:

If no `content.locking` option is set or set to `true`:
- Continously check if a lock exists (every X seconds, we only increased that X now)
- If unsaved changes exist, send requests to set a lock every X seconds (again we increased that a bit)

New in 3.25, if `content.locking` is set to `false`:
- Don't do any of this.

**Comment by afbora** [comment]
Yes, it works as you say now, but I always see different behavior from time to time even though I delete media files. I think it's about cookies.

I will let you know if it repeats 👍

**Pull request merged**
