### PR TITLE
Fix block keydown propagation

### LINKED ISSUE #5272: [v4] Keyboard shortcuts for Nested Blocks field get applied to parent
## Description
When using nested blocks inside a field, hotkeys will be applied both to the selected blocks field and the parent blocks field.

https://streamable.com/idlffi

**Expected behavior**  
Keyboard shortcuts would not apply to parent if selecting a nested blocks field

## Your setup
**Kirby Version**  4.0.0-alpha.2

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- #5272

### CODE REVIEW

**Comment by bastianallgeier** [comment]
TBH, I think we can ignore this. With the latest drawer changes, we no longer render two drawers at once.

**Comment by distantnative** [comment]
@bastianallgeier No of course we do and continue to do so with the fields previews block

**Comment by bastianallgeier** [comment]
Oh right. It makes sense that we need it for the fields preview. But how do we render two drawers at once?

**Comment by distantnative** [comment]
Why drawers? There it’s just nested blocks. As you said, one drawer. But in the preview you have a blocks inside a block and so we need to stop propagation

**Comment by bastianallgeier** [comment]
🙈 Totally stood on se Leitung

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
