### PR TITLE
`Uuid`: don’t populate when read from cache

### PR DESCRIPTION
**Pull request by distantnative**
@lukasbestle Seems like I am too blind to realise why suddenly unit tests keep failing.

### CODE REVIEW

**Comment by lukasbestle** [comment]
From reading through the code I also can't find the reason. Might need step debugging with Xdebug to find which methods are called in which order.

**Comment by distantnative** [comment]
Found a way to implement https://github.com/getkirby/kirby/issues/4762 properly without breaking unit tests.

However, for that to work `Uuid::populate()` must first run `Uuid::key()` and `Uuid::value()` before checking and escaping out if already cached. Not sure if that's really the better performance trade off just to save some additional calls of `Uuid::isCached()`.

**Comment by distantnative** [comment]
The more I think about this, the more I think it's a bad idea and we should just stick with the current checking the cache itself.

**Comment by lukasbestle** [comment]
> Found a way to implement #4762 properly without breaking unit tests.
> 
> However, for that to work `Uuid::populate()` must first run `Uuid::key()` and `Uuid::value()` before checking and escaping out if already cached.

Could you please explain why this is necessary and why the tests broke without this?

The idea of #4762 was to skip the populate step when we actively know that we got the ID from cache (thus making the process faster in the 99% case of a repeated page load). If we call `value()`, we don't gain anything as it calls `model()`, which queries the value from cache (exactly what would happen anyway just below).

**Comment by distantnative** [comment]
Cause we only know if it got retrieved from cache after calling `->model()` once. Neither way of initializing (via passing a model object or an ID string) says whether it's already cached or not. But that's how you would call the populate method, either `Uuid::for($page)->populate()` or `UUID::for('4688ghftj57gjb')->populate()`. 

And you are right, we wouldn't gain anything, which is why I suggest to close this. I don't think the idea actually works.

**Comment by bastianallgeier** [comment]
Ok, I'm closing it.

**Pull request closed without merging**
