### PR TITLE
Add GitHub action for CI

### PR DESCRIPTION
**Pull request by distantnative**
**This is WIP**

@lukasbestle have you dealt with GitHub Actions before to figure this out together?

### CODE REVIEW

**Comment by lukasbestle** [comment]
To be honest I'm not sure if the effort is actually worth it. Travis works great for us at the moment, doesn't it?

**Comment by distantnative** [comment]
Travis feels quite slow at times, would be interesting to see if something integrated with GitHub can be faster. Plus it's nice to learn about Github Actions... even though my commit history looks frustrating XD

**Comment by lukasbestle** [comment]
I see. :)

Would you mind working in a separate repo until you get it working? I get an email for each of your commits. 😄

> @lukasbestle have you dealt with GitHub Actions before to figure this out together?

Sorry, I can't really help. I have played around with it, but not created a full setup so far.

**Comment by distantnative** [comment]
Oh shoot...it's difficult, I kinda need the whole repo to see if the tests actually run (right now I had it working except the APCu tests).

**Comment by distantnative** [comment]
And I only have actions in the Kirby organization. A second repo would need to be public and in this organization - I am afraid that could confuse users.

**Comment by bastianallgeier** [comment]
I would be very happy to invest more time in Actions. Travis is in fact super slow and I hope we could fix that. But I think we could also simplify the process of building js and css files for plugins with a proper setup. So far it's a nightmare to have dev files and dist files mixed up. I also want to find out if we can automate more stuff with it, like increasing the version number in the composer.json and other things.

**Comment by lukasbestle** [comment]
> But I think we could also simplify the process of building js and css files for plugins with a proper setup. So far it's a nightmare to have dev files and dist files mixed up.

What do you mean exactly?

> I also want to find out if we can automate more stuff with it, like increasing the version number in the composer.json and other things.

I thought about and experimented with that as well. Unfortunately the way GitHub currently handles releases won't really work with that. If GitHub allowed putting an Action between the push on the "Create release" button and the actual release being created, we could easily do that. But right now, GitHub first creates the Git tag and then triggers the Action (which can't really modify the code anymore).

I wanted to open a feature request ticket at GitHub a few weeks ago, but unfortunately I forgot about it. Will do soon.

I'm also working on the performance comparison testing feature. I think it makes sense to integrate that directly into the Actions setup and not still into Travis.

**Comment by bastianallgeier** [comment]
> What do you mean exactly?

Kirby loads the index.js and index.css files for each plugin, so they are the ones that need to be built in the end before you create a release or push to master. But while developing our plugin setup also overwrites them with a dev version to enable HMR. There's a lot of HMR code in there, which should not be in the dist files. This means that you constantly have to switch between npm run dev and npm run build when you want to make a new commit. It's pretty annoying and also error-prone. 

> Version number

That's a shame :(

> Performance

Yes, absolutely!

**Comment by lukasbestle** [comment]
@bastianallgeier Regarding the plugin setup: Ah, OK. You mean that we could provide a GitHub Action in our Panel Pluginkit, right?

@distantnative What's the current status of the action in this PR? Anything still missing?

**Comment by bastianallgeier** [comment]
@lukasbestle yep, that's what I thought.

**Comment by distantnative** [comment]
@lukasbestle The current status is that it is not working XD 
I had to give up after hours of trying to get it right, but haven't found the time for a second attempt.

**Comment by bastianallgeier** [comment]
Let's close it. We can still reactivate it later if we want to invest additional time.

**Pull request closed without merging**
