### PR TITLE
Add console info message when system health checks ended

### PR DESCRIPTION
**Pull request by afbora**
I needed to use `async` and `await` to get the message to be printed after all the checks are complete.

### CODE REVIEW

**Review by lukasbestle — APPROVED** [review]
👍

**Comment by lukasbestle** [comment]
Oh shit, only just realized after merging that this will make all checks run in series.

@afbora Can you try if this works:

```js
// `Promise.all` as fallback for older browsers
let promiseAll = Promise.allSettled || Promise.all;

await promiseAll([
  this.check("content"),
  this.check("git"),
  this.check("kirby"),
  this.check("site")
]);
```

**Comment by afbora** [comment]
> Promise.allSettled called on non-object

@lukasbestle I'm getting above error (dialog, not in console) if you mean like following:

```js
async created() {
  console.info(
    "Running system health checks for the Panel system view; failed requests in the following console output are expected behavior."
  );

  // `Promise.all` as fallback for older browsers
  let promiseAll = Promise.allSettled || Promise.all;

  await promiseAll([
    this.check("content"),
    this.check("git"),
    this.check("kirby"),
    this.check("site")
  ]);

  console.info("System health checks ended.");
},
```

**Comment by lukasbestle** [comment]
Ah, sorry. This should work:

```js
async created() {
  console.info(
    "Running system health checks for the Panel system view; failed requests in the following console output are expected behavior."
  );

  // `Promise.all` as fallback for older browsers
  let promiseAll = (Promise.allSettled || Promise.all).bind(Promise);

  await promiseAll([
    this.check("content"),
    this.check("git"),
    this.check("kirby"),
    this.check("site")
  ]);

  console.info("System health checks ended.");
},
```

**Comment by distantnative** [comment]
We should be able to just work with `Promise.all` - I think our existing browser requirements cover that.

**Comment by distantnative** [comment]
Although I am reading that `Promise.all` might not finish all calls if one fails.

**Comment by distantnative** [comment]
Strike my comments, now I understood yours.

**Comment by afbora** [comment]
@lukasbestle Yes, works great!

**Pull request merged**
