### PR TITLE
Allow to prefill the login form

### PR DESCRIPTION
**Pull request by lukasbestle**
Main use case for me is to make it easier to log in to the Demokit. We could also use it in the Sandbox.

---

### Enhancements

- The login form can now be prefilled for testing use cases with the new `value` prop of the `k-login-view` component

### Breaking changes

None

## Docs

Probably too obscure to document

## Ready?

- [x] In-code documentation (wherever needed)
- [ ] Unit tests for fixed bug/feature
- [x] Tests and checks all pass

### For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
I'd suggest to just calling them email and password.

And let's avoid v-bind=$propd - that'll cause issues down the road with Vue 3. already looking into how to reduce this in our existing code (so totally get why you added it as we currently use it a lot).

**Comment by lukasbestle** [comment]
Got rid of `v-bind`.

Naming the props just `email` and `password` would be super confusing IMO because the data is also called `email` and `password`. "Prefilled" makes clear that it's just the initial value.

**Comment by distantnative** [comment]
The data object is only internally and is `user.email` and `user.password`. 

Alternatively, the prop would be `value` with an object as well to be more in line with our other components.

**Comment by lukasbestle** [comment]
Fine for me. Went with a `value` object so we can also prefill the code if needed.

**Review by distantnative — DISMISSED** [review]
@lukasbestle looks good to me, added some inline docs for the props when we're already touching this. Also switched to inherit props to make them more consistent - we're trying to do it like that in more places recently.

**Comment by lukasbestle** [comment]
Looks good, thanks for the changes.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
