### PR TITLE
Structure field: delete all button

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

screen-capture-1480-Test - Mægazine-localhost

### 🎉  Features

- Structure field: delete all button https://kirby.nolt.io/458

### Breaking changes
None

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I think I would go for the same dropdown as the blocks field here.

**Comment by afbora** [comment]
@bastianallgeier I thought about it but gave up. Because after adding a block we don't have to use dropdown to add the next blocks. But for the structure field the developer will always have to click the dropdown two times.

**Comment by bastianallgeier** [comment]
I think we could do the same for the structure field: https://github.com/getkirby/kirby/pull/4858

- The plus button is visible below the last row as soon as the field is not empty and when more items can be added
- We replace the add button at the top with a dropdown and include the delete all option there. 

For future releases, we should also add "Insert before" and "Insert after" options to the row dropdowns. This would be aligning the features with blocks and layouts and could be super useful for the structure fields as well.

**Comment by afbora** [comment]
@bastianallgeier I've updated the PR

screen-capture-1480-Test - Mægazine-localhost

**Comment by bastianallgeier** [comment]
This is cool. I just realised that we have no proper solution as soon as pagination appears. I'm afraid we have to move it forward to the next milestone

**Comment by afbora** [comment]
Where do you think we should put the add button? Now currently like following with this PR:

captures_chrome-capture-2022-11-8 (1)

**Comment by afbora** [comment]
An idea 💡 Did you like it?

captures_chrome-capture-2022-11-8 (2)

**Comment by afbora** [comment]
Could you give me an idea please? @getkirby/kirby-staff 😅

**Comment by afbora** [comment]
Otherwise, I suggest to removing `Add` feature for the PR. We can implement just  the `Delete all` feature 🙂

**Comment by bastianallgeier** [comment]
Your design idea was brilliant. I just moved it around …
Screenshot 2022-12-13 at 14 22 33

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
