### PR TITLE
Fixes for new date/time fields

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
@distantnative still a draft? or should I start reviewing it?

**Comment by distantnative** [comment]
@bastianallgeier Was hoping to get feedback first, but I think you can review it and we'll see during RC if it really catches all issues.

**Comment by distantnative** [comment]
Arg, forgot the unit tests. Will fix them tonight.

**Comment by distantnative** [comment]
@bastianallgeier ready

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
