### PR TITLE
New page status icons

### PR DESCRIPTION
**Pull request by distantnative**
Another bit from `storybook`:

Screen Shot 2020-10-09 at 15 01 50

### CODE REVIEW

**Comment by bastianallgeier** [comment]
What needs to be done to move this out of draft mode?

**Comment by distantnative** [comment]
The other icons PR, cause we need those icons.

However, I just thought this morning that the other PR is taking the wrong direction. With Inertia we would rather work with the SVG file not Icons.Vue.

So maybe better to really just add the new icons in both places for the moment.

**Comment by bastianallgeier** [comment]
Yes, I agree! Putting the icons into a Vue component was really just a developer experience fix, but it's blowing up the JS bundle unnecessarily. Would you mind adding them?

**Comment by distantnative** [comment]
@bastianallgeier first merge https://github.com/getkirby/kirby/pull/2811, than this

**Comment by distantnative** [comment]
@bastianallgeier ready

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
