### PR TITLE
Switches from integer to return to array for `Str::similarity` method

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Please check out @lukasbestle [comment here](https://github.com/getkirby/kirby/pull/2936#issuecomment-771146235).

## Related PR

- Improves #2936 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Added in-code documentation (if needed)
- [x] CI passes (runs automatically when the PR is created or run `composer ci` locally)
  Running locally requires PHPUnit, PHP-CS-Fixer, Psalm, PHPCPD and PHPMD.

- [ ] Checked whether the PR needs documentation, if needed added to the [release docs checklist](https://github.com/getkirby/getkirby.com/pulls)

### CODE REVIEW

**Comment by afbora** [comment]
@lukasbestle Any chance you could have a look at this before the RC? 🙏

**Review by lukasbestle — COMMENTED** [review]
Looks great! I'm making a few minor changes, one moment please.

**Review by lukasbestle — APPROVED** [review]
I made the following changes:

- Replace the `$caseSensitive` argument with a `$caseInsensitive` argument. This is for consistency with the other `Str` methods and important to avoid confusion. The built-in PHP functions have these kind of inconsistency problems all the time, so at least we should be consistent. ;)
- Wording fixes in the docblock
- Use `compact()` for the return value
- Don't pass the `$caseInsensitive` param recursively for better performance (the `Str::lower()` is applied once at the beginning and doesn't need to be applied over and over)
- Test the whole array return value in the unit tests

I really love the method now! Great work!

**Comment by afbora** [comment]
@lukasbestle A great touch 👍 🎉

**Pull request merged**
