### PR TITLE
Panel menu: enable automatically those from config

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Oh, yes please :)

**Comment by afbora** [comment]
After this PR:

image (2)

**Comment by distantnative** [comment]
@afbora how does your config look like?

**Comment by bastianallgeier** [comment]
Yikes, I get the same when there's no config for the panel.

**Comment by distantnative** [comment]
Yikes, really had a shortcut in my Brian (the negative ones) - feel free to revert it or I will try to fix it tonight

**Pull request merged**
