### PR TITLE
Refactor async JS code

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by afbora** [comment]
I don't know if it's important, but I think await is also missing in some async api methods (`/panel/src/api`). Because some of them use await while others don't. For example, await was used when creating the language, but not when creating the page or user.

**Comment by bastianallgeier** [comment]
@afbora's right. There's a lot of inconsistency in api methods. Sometimes we wait, sometimes we don't. @distantnative I assume that waiting is not really necessary if you return a method that already awaits. But I'm not 100% sure.

**Comment by distantnative** [comment]
I think if a method is async, there's no difference whether you do normal return or return await.

**Comment by bastianallgeier** [comment]
Then we should remove some unnecessary awaits.

**Review by bastianallgeier — DISMISSED** [review]

**Comment by afbora** [comment]
Just one more: https://github.com/getkirby/kirby/blob/fix/async-code/panel/src/fiber/index.js#L296

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
