### PR TITLE
Updated supported version in security.md

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

We should keep the supported version up to date more often. This fixes it.

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
Maybe we should add „until 31.12.2020“ to v2 while we are at it.

**Comment by lukasbestle** [comment]
Oh, and we could use a yellow warning emoji instead of a checkmark for v2.

**Comment by lukasbestle** [comment]
💡 Idea: Because we also need access to the supported version from the planned update checker, it‘s probably better to create a page “security support” on getkirby.com. We can then link to that from security.md. I will create the page today or tomorrow.

**Comment by lukasbestle** [comment]
@bastianallgeier @distantnative I have updated the `SECURITY.md` with a link to the security page.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
