### PR TITLE
LinkField: fix dropdown for only option

### LINKED ISSUE #6186: Link field with single option breaks pages dropdown on empty state
## Description
When creating a `link` field and restricting it to only pages, like so:

````yml
  link:
    label: Link
    type: link
    options:
      - page
````

The field looks as expected, however, when you click where it says "Select...", you don't get the dropdown of pages:
GIF showing that clicking on the link field doesn't open the pages dropdown, despite it showing Page is selected.

You have to click on “Page” and then select “Page” (the only option), from the dropdown, then the pages dropdown appears as expected:

GIF showing that when you click Pages then Pages, the pages dropdown now opens.

**Expected behavior**  
For the pages dropdown to appear when clicking "Select" without first needing to click "Pages" > "Pages".

## To reproduce

1. Create a link field with only the `page` `option`
2. Click on "Select..."
3. Dropdown doesn't appear

## Your setup
**Kirby Version**  
4.0.3

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS
 - Browser: Chrome
 - Version: 120

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Link field: no dropdown is shown if only one type option is active
#6186
- Link field: no dropdown icon is shown when field is disabled

### For review team

- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
> TypeError: Cannot read properties of undefined (reading 'type')

Getting console error when single option that not have dropdown like `url` option.

````yaml
link:
  type: link
  options:
    - url
````

**Review by bastianallgeier — APPROVED** [review]
Works great! I've added two more examples to the sandbox.

**Comment by afbora** [comment]
@bastianallgeier Did you see my comment?

**Comment by bastianallgeier** [comment]
That's so weird. Do you see the times? Your comment is 4 minutes after mine, but still it is sorted before my approval. My guess is that you posted it earlier but it only went through after my approval. I didn't see it when I approved it. I will check again.

**Comment by afbora** [comment]
Really weird.

screen-capture-1814-LinkField_ fix dropdown for only option by distantnative · Pull Request #6_-github com

**Comment by bastianallgeier** [comment]
Hm, I just tried but I don't get the console error.

**Comment by bastianallgeier** [comment]
@afbora I've added a fix https://github.com/getkirby/kirby/pull/6197

**Pull request merged**
