### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by bastianallgeier**
I think the Sponsor Button with a link to our buy page is something we should add to all our repos.

### CODE REVIEW

**Comment by distantnative** [comment]
Does it work with leaving those unused lines in there?

**Comment by bastianallgeier** [comment]
Yes, it works. I took it directly from the editor plugin.

**Comment by lukasbestle** [comment]
But do we need these extra lines? I'm for making the file a one-liner for cleanliness.

**Comment by bastianallgeier** [comment]
I just removed the parts that we don't need.

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
