### PR TITLE
Render the error page on invalid media URLs

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

More consistent behavior that also allows overriding the error behavior with custom code on the error page.

## Related issues

- Fixes https://forum.getkirby.com/t/adjusting-the-media-hash-generation/21456/14?u=lukasbestle.

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Added in-code documentation (if needed)
- [x] CI passes (runs automatically when the PR is created or run `composer ci` locally)
  Running locally requires PHPUnit, PHP-CS-Fixer, Psalm, PHPCPD and PHPMD.

- [x] Checked whether the PR needs documentation, if needed added to the [release docs checklist](https://github.com/getkirby/getkirby.com/pulls)

### CODE REVIEW

**Comment by distantnative** [comment]
Wondering whether this could be a breaking change for some setups - (for whatever reason) checking for text/plain on error responses but now getting HTML.

**Comment by lukasbestle** [comment]
I don‘t think so. We previously had `HTTP 404` already, so that would have been much more reliable to check for. But to be honest, I don‘t see many use-cases where you would need to check the response anyway (as the media URLs are mainly used for linking to files). Do you have an example use-case?

**Comment by distantnative** [comment]
Having looked at it again, you're right: I think it's a good change that won't really cause issues anywhere.

Questions is if this is urgent or could wait until 3.6.0 since strictly it's a breaking change (public method returns something different now) - one that won't break many (if any) actual setups though.

**Comment by lukasbestle** [comment]
You are right, it's probably better to move this to 3.6.0.

Marking it as draft to avoid that we merge it by accident. The code is already done.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
