### PR TITLE
Upgrade to Vite 5

### PR DESCRIPTION
**Pull request by distantnative**
- Upgrades to vite 5
- Manually includes tailored prismjs
- Remove lightning's again (much larger bundle size with it)

### CODE REVIEW

**Comment by distantnative** [comment]
Ok the bundle sizes are very different, so I think it somehow slimmed prismjs down.
Unfortunately the plugin isn't maintained anymore and clashes with Vite 5 moving to ESM for the config file.

**Comment by bastianallgeier** [comment]
Is it worth to upgrade at all before the launch?

**Comment by distantnative** [comment]
No. Let's do it for 4.1 - issue/questions remain though

**Comment by bastianallgeier** [comment]
When I installed the plugin, it was part of the installation process to put it in the vite config. I honestly never thought about what it does exactly.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
