### PR TITLE
Keep title when switching template in create dialog 

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

I'm not sure the solution but it seems works for me great. Also I couldn't write unit test for getting title and value prop while changing template.

### Fixes
- Keep title when switching template in create dialog #6328

### Breaking changes
None

## Ready?

- [ ] In-code documentation (wherever needed)
- [ ] Unit tests for fixed bug/feature
- [ ] Tests and checks all pass

### For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
The problem is that any other (custom) fields would still be lost.

**Comment by afbora** [comment]
Yes. I see. I'll check out. But if you think this (getting values of custom fields) is complex one, I would merge the PR to fix the regression.

**Comment by afbora** [comment]
@distantnative By the way, since custom fields will usually be different (of course they can be the same) based on template, it makes sense to keep only the title and slug common to all templates for now.

**Comment by distantnative** [comment]
Fair point

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
I agree, let's keep this simple first.

**Pull request merged**
