### PR TITLE
Fix column block gap

### LINKED ISSUE #5935: [v4] Sections and fields misalign in combined panel layouts
## Description
When combining sections and fields, sections get a large top margin while fields do not. This results in unbalanced layouts.

**Expected behavior**  
Fields and section should align nicely.

**Screenshots**  
grafik

## To reproduce
Blueprint for the given example
```yml
title: Plugin
num: zero
columns:
  - width: 1/3
    sections:
      header1:
        type: fields
        fields:
          headline1:
            type: headline
            label: Beschreibung
          description:
            label: Beschreibung
            type: textarea
            size: tiny
          introduction:
            label: Einleitung
            type: textarea
            size: small
      cover:
        label: Titelbild
        type: files
        max: 1
        layout: cards
        size: huge
        image:
          ratio: 16/9
          cover: true
  - width: 1/3
    fields:
      headline2:
        type: headline
        label: Metaangaben
      category:
        label: Kategorie
        type: tags
      source:
        label: Quellplugin
        type: select
        options:
          type: query
          query: page.sources
          text: '{{ item.value }}'
          value: '{{ item.key }}'
      type:
        label: Typ
        type: select
        options:
          - MIT
          - Plus
      price:
        label: Preis
        type: number
        after: €
        when:
          type: Plus
      feature:
        label: Feature
        type: toggle
  - width: 1/3
    sections:
      header3:
        type: fields
        fields:
          headline3:
            type: headline
            label: Dokumentation
      docs:
        label: Dokumentation
        type: pages
        image: false
        templates:
          - documentation
          - textreference
      versions:
        label: Versionen
        type: pages
        image: false
        templates:
          - version
```

## Your setup
**Kirby Version**  
Kirby 4 beta 3 – not sure how Kirby 3 does this in comparison.

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

Since our blueprints promote mixing fields sections and other sections we need to stick to the same vertical gap between `fields` and `columns grids to achieve consistent spacing that aligns between Panel elements.

### Fixes
- Fixed Panel column block gap
#5935

### For review team

- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
@bastianallgeier if you feel Panel layouts are getting too dense with this, I suggest to raise the gap for both variants to something like e.g. `spacing-10`

**Comment by bastianallgeier** [comment]
I think it looks a lot more consistent from what I've checked in the demokit and starterkit. But there are a few places where it definitely is visually very different. I wonder if we need to move it to 4.1 because of that.

**Comment by bastianallgeier** [comment]
I've added a new alignment test page in the lab btw.

**Comment by distantnative** [comment]
@bastianallgeier ture, not need to cramp it into the patch update

> I've added a new alignment test page in the lab btw.

I never know when to do that for PRs (shouldn't be always you who has to do it) as I don't want to push something to the sandbox that's not on the relevant branches yet.

**Comment by bastianallgeier** [comment]
@distantnative tbh, I feel like this is the prefect task for those who review a PR, because it kills two birds with one stone. I can test your PR and I can enhance the sandbox at the same time. If you don't feel like it is helping you while creating the PR, you can totally leave it up to me.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
