### PR TITLE
`Data\Json` and `Data\Xml`: Decode empty strings

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

The `Txt` and `Yaml` classes already accepted empty strings, so I think it makes sense to have the same behavior for the other formats.

### Enhancement

- The `Data\Json::decode()` and `Data\Xml::decode()` methods now accept empty strings and treat them as an empty data set (empty array) for consistency with `Data\Txt::decode()` and `Data\Yaml::decode()`

## Breaking changes

The `Data\Json::decode()` and `Data\Xml::decode()` methods no longer throw exceptions if an empty string is passed. If a differentiation between an empty string and an empty data set is required, you need to check for empty strings before calling `decode()`.

## Related issues/ideas

- See https://github.com/getkirby/kirby/pull/3483#issuecomment-873722279

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
But `Yaml::decode()` and `Txt::decode()` right now wouldn't follow the same behaviour?

**Comment by afbora** [comment]
Empty array as `[]` returns when empty string as `''` send to `Yaml::decode()` and `Txt::decode()` methods, but `Json::decode()` and `Xml::decode()` were throwing an error. This PR is resolving it for consistency.

**Comment by distantnative** [comment]
But shouldn't we add the same if statements for consistency? Would be easier to understand if they all check for it and sparing to run the parsers on an empty string might also be good.

**Comment by afbora** [comment]
I understand 👍  Yes, if we add the same if condition, there will be consistency as a general view. (Although it now returns the correct output). Of course, as you said, the parser does not need to run when empty string sends. So yes, it would be nice to easily see by looking at the code that they all exhibit the same behavior across all handlers.

**Comment by lukasbestle** [comment]
Very good points! I will add the remaining lines.

**Review by afbora — APPROVED** [review]
I've added remaining lines.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
