### PR TITLE
Use optional chaining `(?.)` in frontend

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Use optional chaining `(?.)`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

All browsers supported
https://caniuse.com/mdn-javascript_operators_optional_chaining

### Refactoring
- Switched to `Optional chaining operator` on Frontend

## Breaking changes

None

## Related issues/ideas

None

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by johannschopplich** [comment]
I love minor refactors like this. Beautiful. 🤭☺️

**Comment by bastianallgeier** [comment]
I like it a lot. We should just make sure to test this properly to not overlook any unwanted side-effects. I can't see any from scanning the files, but we should still check.

**Comment by gearsdigital** [comment]
Not sure if you have some static code analysis somewhere but you should consider adding it because it can help to prevent unwanted side-effects.

https://eslint.org/docs/rules/no-unsafe-optional-chaining

*edit You have! And that's awesome 😎

**Comment by distantnative** [comment]
Don't wanna ruin the party, but technically it would be a breaking change as it raises the browser requirements of our Panel.

Current requirements:
- Chrome 63+
- Firefox 67+
- Safari 11.1+
- Edge 79+
- Opera 50+
- Mobile Safari 11.1+
- Android Browser 92+
- Chrome for Android 92+

With this change:
- Chrome 80+
- Firefox 74+
- Safari 13.1+
- Edge 80+
- Opera 67+
- Mobile Safari 13.4+
- Android Browser 95+
- Chrome for Android 95+

The new requirements would cover 91.81% of all users according to https://caniuse.com/mdn-javascript_operators_optional_chaining. Our current requirements 94.24%.

**Review by distantnative — CHANGES_REQUESTED** [review]
Don't wanna ruin the party, but technically it would be a breaking change as it raises the browser requirements of our Panel.

Current requirements:
- Chrome 63+
- Firefox 67+
- Safari 11.1+
- Edge 79+
- Opera 50+
- Mobile Safari 11.1+
- Android Browser 92+
- Chrome for Android 92+

With this change:
- Chrome 80+
- Firefox 74+
- Safari 13.1+
- Edge 80+
- Opera 67+
- Mobile Safari 13.4+
- Android Browser 95+
- Chrome for Android 95+

The new requirements would cover 91.81% of all users according to https://caniuse.com/mdn-javascript_operators_optional_chaining. Our current requirements 94.24%.

It's no big break at all, but I would still argue that users shouldn't be forced to communicate new browser requirements to clients on minor updates. That's why I think we would need to move this to 3.7

**Comment by johannschopplich** [comment]
@distantnative Are you sure? I don't trink so. Since the `target` for Vite stays untouched, all optional chaining occurences will get transpiled by esbuild.

This can easily get shipped in 3.6.1. You won't break the browser requirements. They are defined by [Vite's default browser target](https://vitejs.dev/guide/build.html#browser-compatibility).

**Comment by distantnative** [comment]
Got you, sorry somehow thoughts this needs to be supported natively.

**Review by distantnative — APPROVED** [review]
Given that, the changes itself look good to me.

**Pull request merged**
