### PR TITLE
Remove blocks field migrations: editor and builder

### PR DESCRIPTION
**Pull request by afbora**
### Fixes
- https://github.com/getkirby/backlog/issues/19

### Breaking changes

- Removed `builder` and `editor` field migration for blocks field.

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Review by bastianallgeier — COMMENTED** [review]
It looks good to me. I just wonder if we should remove this block as well: https://github.com/getkirby/kirby/blob/1f17292a4f62de4893f13ee0efbc4f129e8463c0/src/Cms/Blocks.php#L123-L133

**Comment by afbora** [comment]
I didn't remember very well. What was the old YAML format used for? Honestly, you know these parts best @bastianallgeier

**Comment by bastianallgeier** [comment]
The builder used YAML. That's why we still try to read it here. But when we throw out builder support, we can also throw out the YAML parsing attempt.

**Comment by afbora** [comment]
I've removed that code block.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
