### PR TITLE
Panel: decrease loading spinner opacity

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

I think it looks better with a bit less opacity while loading

### Enhancements
- Panel: the loading spinner has reduced opacity

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] ~~In-code documentation (wherever needed)~~
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by lukasbestle** [comment]
To be honest I think it looks weird if just the loading spinner in particular is grey while every other piece of text and all icons are white. What is the reasoning for the change?

**Comment by distantnative** [comment]
I find the full white icon a bit irritating as it signals it could be the actual icon for the item. With the reduced opacity, I prefer it a 100% more (but that's taste and probably differs) as it communicates that this is a transitional state and once the actual icon appears, returns to full opacity. For me the Panel experience is way more pleasing with this change.

**Comment by lukasbestle** [comment]
I get your points. I think this is something for @bastianallgeier to decide.

**Comment by afbora** [comment]
Obviously, since the spinner icon replaces the white site icon, the gray spinner looks better (more suitable for the loading situation). I like it 💛

**Comment by bastianallgeier** [comment]
I have to say that I quite like it. The spinner always had an issue with the multiple parallel loading processes, because it often restarts spinning with a weird visual glitch. The opacity change is really just a minor detail, but it feels a bit more polished to me.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
