### PR TITLE
Add support for role attribute to link Kirbytag.

### PR DESCRIPTION
**Pull request by tobiastom**
This might be helpful if you want to markup a link as a button, but when a button itself would not work without javascript:

`<a role="button" href="somehere">Go here</a>`

I can see that there might be other related changes wanted, but this is supposed to be a simple proposal for a feature request.

### CODE REVIEW

**Comment by tobiastom** [comment]
@lukasbestle Done. Sorry that I missed the list in the first place. :)

**Comment by lukasbestle** [comment]
Thank you. We will consider this for the next minor release. :)

**Comment by tobiastom** [comment]
Thank you. :)

**Comment by lukasbestle** [comment]
Oh, you sent it to master. I have manually merged it into develop for Kirby 2.3.2. Thank you. :)

**Comment by tobiastom** [comment]
Thank you! :)

**Pull request closed without merging**
