### PR TITLE
Checks section fields to prevent error

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR
If `fields` property not exists, panel was throw `PHP error` as `Illegal offset type in isset or empty`. 

Because when `fields` property does not exist, the `$type` variable returns an `array` instead of a `string` (returns `fields` as array). As you know, when `$type` is an `array`, an error occurs because it searching for an array in the array index.

So a new control was written to ensure that the `$type` variable is `string` and `not empty` before the if condition of the error line (This implement of 613. line)

Btw, with this fix, non string field types will not work.
I'm not sure if the integer is a field type like `type: 123`

## Related issues

- Fixes https://github.com/getkirby/kirby/issues/1935

## Todos
If you feel like you can help to check off the following tasks, that'd be great. If not, don't worry - we will take care of it.
- [x] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [ ] Fix code style issues with CS fixer and `composer fix`
- [ ] If needeed, in-code documentation (DocBlocks etc.)

### CODE REVIEW

**Comment by texnixe** [comment]
Hm, but now you get the same error message, no matter if a correct type is set or not. I think if the `fields` property is missing, it should say so, otherwise the error message is misleading.

**Comment by afbora** [comment]
Not exactly i think, it was a PHP error, not a defect in the message. 
This fix checks if both fields are missing and the type is correct.

If fields are missing or not defined correctly, the message indicates which section has an error. 
This allows the user to check and correct the corresponding section.

**Comment by afbora** [comment]
**Before**

FireShot Capture 003 - Kirby Panel - localhost

**After fix**

FireShot Capture 004 - Exploring the universe - Mægazine - localhost


Certainly clearer than before. But it could be a more descriptive sentence :))

>Invalid section type for ("SECTION NAME")

I think the important thing is to fix the PHP error.

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
I think it's indeed a lot better!

**Pull request merged**
