### PR TITLE
Fix `V::size` unit test for Field objects 

### LINKED ISSUE #3544: Running unit tests only for `Toolkit` namespace fails
While they pass when we run all unit tests

### PR DESCRIPTION
**Pull request by afbora**
## Related issues/ideas

- Fixes #3544

### CODE REVIEW

**Comment by distantnative** [comment]
```
composer run-script test tests/Toolkit
```

still fails for me

**Comment by distantnative** [comment]
Is it working for you, @afbora? Only running tests for the `Toolkit` namespace?

**Comment by afbora** [comment]
It gave an error when I ran only `VTest`. This was fixed with PR. But as you said, now when I run the entire Toolkit namespace, the same error continues 🙁

**Comment by afbora** [comment]
By the way, I realized that it is not fully related to `Supports countable field objects`. Only when VTest runs alone I was giving the error but this PR fixes it. We can merge this PR without closing the related issue. I'll keep tracking down for running entire Toolkit tests fails.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
