### PR TITLE
Add to top feature for structure field

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

When `unshift` is enabled, the adding item is always added to the top of items. 

Option name is inspired by the native method in php and javascript language. Do you have a better and more understandable name idea instead of  `unshift`? 😅 

````yaml
fields:
  social:
    label: On the web
    type: structure
    unshift: true
    fields:
      platform:
        label: Platform
        type: text
        width: 1/2
      url:
        label: URL
        type: url
        width: 1/2
````

## Related issues

- Closes https://github.com/getkirby/ideas/issues/203

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
I like the feature, but I think the option name is indeed not optimal. `unshift()` is pretty uncreative and confusing naming in PHP and JS (which likely inspired each other), but I don't think we need to continue that trend. ;)

Maybe `newPosition: top|bottom`?

**Comment by afbora** [comment]
Boolean seems more logical to me if it won't be more than 2 options. How is following options?

````yaml
addTop: true   // default: false
addToTop: true // default: false
prepend: true  // default: false
append: false  // default: true (more logical)
````

**Comment by bastianallgeier** [comment]
I have to say that I like "prepend: true" the most so far.

**Comment by afbora** [comment]
I have changed option name `unshift` to `prepend`.

**Review by lukasbestle — APPROVED** [review]
I like `prepend: true` as well. 👍

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
