### PR TITLE
Fix loading blueprint with i18n’ed name #4177

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Blueprints with different translations for `name` key now can be loaded
#4177 

### Breaking changes
_None_

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
-  ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
What I find confusing: In "normal" blueprints we use the `title` field for the human-readable blueprint name. Why do we use the `name` field in block blueprints?

I feel like we should rather rename the `name` field to `title` to make it consistent. Then the block blueprints can use the same translation logic in the `Blueprint` class.

**Comment by distantnative** [comment]
@lukasbestle I asked @bastianallgeier the same and he said it's due to the transition from builder and blocks plugins. But we also said, like you suggest, that aliasing/renaming would be good. Similarly to https://github.com/getkirby/kirby/issues/4194.

Nevertheless, I think this would be a good quick fix before we can tackle the consistency updates.

**Comment by lukasbestle** [comment]
OK, I see. Makes sense. I think we should then add TODO comments to ensure that we remove this hack once the consistency is restored.

**Comment by bastianallgeier** [comment]
I wonder if we should actually tackle the inconsistency issue first. Translating the name is weird because it's normally used in a pretty id-ish way, where translations could theoretically be catastrophic. 

So maybe a better solution would be to introduce title as new official option and simply convert name for block fieldsets before it even hits the constructor.

**Comment by distantnative** [comment]
@bastianallgeier I think it all depends on timelines. If the consistency alignment takes us a few month, I'd prefer to do the quick fix like this now. If the consistency alignment can happen e.g. in 3.6.4, then sure.

**Comment by bastianallgeier** [comment]
I don't think we have to make the full alignment already. We'd basically just polyfill the title for now to fix the issue and move on with more consistency fixes later.

**Comment by bastianallgeier** [comment]
I think I would do the following. 

We change this line …

https://github.com/getkirby/kirby/blob/04127160ed1ab8dc277763cd8ba4ebc5a097bc18/src/Cms/Fieldset.php#L57 

… to …

```php
$this->name = $this->createName($params['title'] ?? $params['name'] ?? Str::ucfirst($this->type));
```

This would be a very minimal change for now, which is still 100% compatible with the current syntax. Then @shoogstoel can already use the title option for his blocks that he needs to load with the custom loader. 

The adjusted code for `Blueprint::load` would otherwise only serve this single use-case, which is pretty specific anyway.

**Comment by distantnative** [comment]
Ok, let's do it

**Comment by distantnative** [comment]
Hmm, @bastianallgeier, but with your change, the bug would continue to exist for anyone using translations on `name`, am I right? It would be up to users to change their code to use `title` instead?

**Comment by bastianallgeier** [comment]
Yes, you are right. But only if they load the Block Blueprint manually with Blueprint::load() which is pretty unusual. It should work when you translate the Block name and just use the Blocks field regularly.

**Comment by distantnative** [comment]
Maybe my mind is too twisted, but if the custom block blueprint looks like this:

```
/site/plugins/button/blueprints/blocks/button.yml

name:
  en: Button
  de: Knopf
icon: bolt
fields:
  link:
    type: url
  text:
    type: text
```

This would work?

**Comment by bastianallgeier** [comment]
I thought it would work in our regular setup, yes. Is it failing?

**Comment by bastianallgeier** [comment]
I've tested it and it works. I've already created a replacement for this PR: https://github.com/getkirby/kirby/pull/4239

**Pull request closed without merging**
