### PR TITLE
Content Locking: activity indicator and countdown to unlock

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
- Adds activity indicator and countdown to unlock
- Refines the unlock protect duration
- add three dots animated icon

Screen Shot 2019-10-11 at 20 13 52

Screen Shot 2019-10-11 at 19 51 20

## Solves
#2195

### CODE REVIEW

**Review by afbora — COMMENTED** [review]
I'm having a issue but I'm not sure whether this is related to this PR. 
While the page is locked, I can navigate and ~~update~~ fields with TAB 🤔 

> The content lock can only be removed by the user who created it. Use unlock instead.

Sorry, i didn't see the error on the console.

Maybe we can prevent the fields from navigate around with TAB.

**Comment by distantnative** [comment]
@afbora I agree we should try to prevent tabbing around. It's not really part of the PR though. Probably best to create a separate issue.

**Review by afbora — COMMENTED** [review]
When the timer runs out, the `Unlock` button remains disabled and it can't clickable.
When I refresh the page, the button `disabled` attr is gone as successful and works properly onclick.

image

**Comment by afbora** [comment]
> @afbora I agree we should try to prevent tabbing around. It's not really part of the PR though. Probably best to create a separate issue.

#2204

**Comment by distantnative** [comment]
@afbora 
I just simplified the PR a lot. Now it's either the loading indicator for 60 seconds (to make sure no new setLocks from the other user are still coming in) and after that directly enabled unlock button.

**Comment by afbora** [comment]
@distantnative Now i cant see countdown. Did you remove it?
Waiting animation then coming out `Unlock` button without countdown.

**Comment by distantnative** [comment]
@afbora Yes, as I said I simplified it so it goes directly from spinning animation to enabled unlock button.

**Comment by afbora** [comment]
I get it. I didn't see any issue. It works perfectly for me 👍 
The only suggestion could be a more beautiful spinner? I don't think it's exactly circular 😅

**Comment by distantnative** [comment]
I mainly went for the spinner that we already have and use for when API is loading

**Comment by afbora** [comment]
spin

@distantnative I understand. 
It has nothing to do with PR, but as you will see, we can actually use a better one.

**Comment by distantnative** [comment]
@afbora wondering if the CSS animation just needs a `transform-origin` property.

**Comment by afbora** [comment]
> an element whose layout is governed by the CSS box model which is either a block-level or atomic inline-level element, or whose ‘display’ property computes to ‘table-row’, ‘table-row-group’, ‘table-header-group’, ‘table-footer-group’, ‘table-cell’, or ‘table-caption’ [CSS21]

@distantnative I just fixed the animation issue about inline elements on transform.
W3 Reference: https://drafts.csswg.org/css-transforms-1/#terminology

**Pull request merged**
