### PR TITLE
`Dir::copy()`: Support skipping the global ignore list

### PR DESCRIPTION
**Pull request by lukasbestle**
### Enhancements

- The `Dir::copy()` method now supports `false` as the argument for `$ignore`. In this mode, all files are copied, including those listed in the global `Dir::$ignore` list.

### Breaking changes

None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~

### CODE REVIEW

**Comment by bastianallgeier** [comment]
The both lists in combination don't seem very intuitive at first sight. At least I'm not fully sure I understand the concept :)

**Comment by lukasbestle** [comment]
The reason why I picked this up was the Sandbox. There we use `Dir::copy()` to install and save the environments, but files like `.gitignore` weren't copied because `Dir::read()` (used internally by `Dir::copy()`) ignores them in the static `Dir::$ignore` ignore list. So if we want `Dir::copy()` to copy the entire directory, we need a way to tell it not to use the static ignore list. We need this for submodule support in the Sandbox, but I think it could also be useful in other cases.

My first solution was to simply override the static ignore list so that it is never used by `Dir::copy()`, with the thought that any ignores could still be passed with the `$ignore` argument. However it would be a huge breaking change.

So I ended up with another argument that defaults to the current behavior (`null` uses the static ignore list). But it can also be set to an array for a custom ignore list that applies to every directory level. So e.g. you could say `['.htaccess']` to just ignore htaccess files, no matter on which directory level they are. This was so far not possible with `Dir::copy()`.

I think the separate `$globalIgnore` argument is a simple and flexible implementation without breaking change. I'm open for naming alternatives if it helps.

**Comment by distantnative** [comment]
I do understand the use case but have to agree that having too ignore parameter is quite confusing. And not sure this can be fixed through different naming.

My understanding is that the existing parameter supports ignoring of specific paths while your new parameter supports file names no matter at which path? Couldn't we rather support wildcards/glob or similar for the existing parameter then?

**Comment by distantnative** [comment]
And for our specific use case in the sandbox it might be indeed best to unser and reset the global list. Why would that be a breaking change if we just do that in our sandbox?

**Comment by lukasbestle** [comment]
The issue with wildcards/globs is that the static ignore list would still apply. Without a separate argument, there wouldn't be a way to disable the static ignore list without a breaking change.

I'm closing this then. Unsetting and resetting the static list from the Sandbox feels a bit like a hack, but I think it's still OK and better than a core implementation we are not happy with.

**Comment by distantnative** [comment]
And passing `false` to the existing parameter to disable the global prop?

**Comment by lukasbestle** [comment]
Oh, that could indeed work to disable ignores completely. 👍
Do you think it's useful on its own or would we also need a way to say "don't use the global ignores, but use this custom list instead"? For that I don't have an idea yet.

**Comment by distantnative** [comment]
Ok, I had a bit closer look and I think the main problem is that so far `::copy` uses its parameter as own ignore list, not interacting with how `::read` handles ignoring (falling back then to the global list). I feel like both methods should better work together here.

If we would pass `$ignore` to `::read()` it is a bit of a breaking change because so far the parameter and global list would both be applied. When passing the local list over to read, the global list would be ignored. This is a breaking change, I am still wondering if this wouldn't be the correct way to do it, also to be consistent with `::read()` on its own.

Would it be too cumbersome to require people who want both global and local list to pass in the future `::copy($dir, 4target, true, array_merge(Dir::$ignore, [$a, $b, $c]))`? Maybe yes. Don't have the best idea in mind yet - but maybe we get the discussion going in that direction: How could we improve `::copy` by actually passing its `$ignore` to `::read` instead of doing its own check in the loop?

**Comment by lukasbestle** [comment]
An additional issue is that the `::copy()` ignore list are full paths while the `::read()` ignore list just applies to a single directory level. I think it's confusing to combine both into one list, otherwise it would be impossible to express "just ignore files named XYZ at the root of the copied directory". For that we'd need to replace everything with wildcard patterns, support a leading slash to match on the root etc. It all gets very complex that way.

**Comment by lukasbestle** [comment]
@distantnative I'm currently leaning towards just supporting `false` for "don't use the global ignore list", without any more magic. What do you think?

**Comment by distantnative** [comment]
Maybe that is the best actionable solution indeed. I was trying to find a complete solution but didn't manage.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
