### PR TITLE
`Database\Query`: Separate `$mode` for `filterQuery()`

### LINKED ISSUE #4564: `Database\Query`: Separate `$mode` for `filterQuery()`
https://github.com/getkirby/kirby/issues/4518#issuecomment-1212402524

### PR DESCRIPTION
**Pull request by distantnative**
### Refactoring
- `Database\Query`: Added new third parameter `$mode` for `filterQuery()`
#4564

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]

**Comment by lukasbestle** [comment]
Does this fix the bug? Given that the last argument is still used, I think you can still not pass a literal `AND` or `OR` without it getting treated as mode.

**Comment by distantnative** [comment]
Then I didn't understand the bug, I thought I followed the description from https://github.com/getkirby/kirby/issues/4518#issuecomment-1212402524 1:1.

**Comment by distantnative** [comment]
Do I get you right then, that `filterQuery` shouldn't at all test for this anymore?

```php
$last   = A::last($args);

// if there's a where clause mode attribute attached…
if (in_array($last, ['AND', 'OR'], true) === true) {
```

?

**Comment by lukasbestle** [comment]
Yes, I think so. This would be a breaking change, but with the `->orWhere()` and `->andWhere()` methods there are more clean alternatives.

If we don't want a breaking change, we could add a deprecation warning instead.

**Pull request merged**
