### PR TITLE
Use k-stats for system view

### PR DESCRIPTION
**Pull request by distantnative**
### Enhancements
- Uses `k-stats` for system view
Screen Shot 2022-05-27 at 20 01 49

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] ~~In-code documentation (wherever needed)~~
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Review by afbora — COMMENTED** [review]
- The license registration button is both a link and a dialog trigger. When we open in a new tab, it goes to another page. I would expect it to be a `button` if it is not an external link.
- I would prefer the text headers `xl` instead`2xl`.
- Considering the translations in different languages, there is a high probability of gliding/overflow issues on mobile.

screen-capture-1426-System - Mægazine-localhost

**Comment by distantnative** [comment]
1. I will look into why `k-link` isn't rendered only as button in this case
2. That's how `k-stats` is styled. Not sure if we should overwrite styles in this case
3. @bastianallgeier maybe makes sense to let `k-stats` break into single column a bit earlier in general?

**Comment by lukasbestle** [comment]
It looks. So. Great.
Awesome use of `k-stats`. 👍

I agree on the breakpoint for the single column.

**Comment by distantnative** [comment]
Ok I think I solved 2 and 3.

I also realised why 1 is - was mixing up `k-link` and `k-button-link`. Have to see how to solve, just using `k-button` is making some problems.

**Comment by distantnative** [comment]
Ok, I think I solved 1 as well.

**Review by afbora — APPROVED** [review]
LGTM, loved 💛

**Pull request merged**
