### PR TITLE
Remove deprecated `DS`

### PR DESCRIPTION
**Pull request by distantnative**
### Breaking changes
- Removed deprecated `DS` constant. Use `/` instead.

### CODE REVIEW

**Review by lukasbestle — APPROVED** [review]

**Comment by afbora** [comment]
@distantnative I couldn't see this warning in release notes: https://getkirby.com/releases/4.0

**Comment by bastianallgeier** [comment]
@afbora because we brought it back :)

**Comment by afbora** [comment]
@bastianallgeier So why I can't see in `v4/develop` branch?
https://github.com/getkirby/kirby/blob/v4/develop/config/setup.php

**Comment by bastianallgeier** [comment]
Forget what I'm saying. This is old. We've removed it again as it seems. But I've lost track when that happened.

**Comment by lukasbestle** [comment]
It's because the release notes on the site have not been updated for many pre-releases. It's one of my todos to fix this today/tomorrow :)

**Pull request merged**
