### PR TITLE
[v4] `$model->file()`: adhere to sort order

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

Especially in the Panel, it currently seems odd that the default preview image is not the first image as shown not he Panel page

### Enhancement
- `$model->file()`, `$model->image()` etc. return the first file/image considering the `sort` field (and not just the filename).

### Breaking changes
- `$model->file()`, `$model->image()` etc. return a different file now, if the lowest `sort` field value is not also the first alphabetical filename

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Review by lukasbestle — APPROVED** [review]
I think it makes sense. But more opinions would be good.

**Comment by distantnative** [comment]
What bothers me is that now the system needs to read every content file just to return one file

**Comment by lukasbestle** [comment]
Hm, that's true. Maybe we could use a cache for the sorting order and file templates. But that adds complexity again.

**Comment by distantnative** [comment]
Yea, there my gut tells me that it's out of proportion. Trying to fix something nobody has much complained so far. Maybe something to take to #concepts to get more input on how benefit vs. costs would play out for users.

**Comment by bastianallgeier** [comment]
While I agree that it makes more sense, I also agree that it feels too massive for such a simple comfort feature

**Comment by distantnative** [comment]
Let's close it?

**Pull request closed without merging**
