### PR TITLE
`Obj::toKeys()`

### PR DESCRIPTION
**Pull request by distantnative**
https://forum.getkirby.com/t/db-record-object-how-to-get-in-record-objekt-all-present-keys-field-names/31995

### Enhancements
- New `Toolkit\Obj::toKeys()` method

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Review by bastianallgeier — DISMISSED** [review]

**Comment by bastianallgeier** [comment]
After approving the PR, I realised that this could be a breaking change if your object actually has a "keys" field 🙈 What do we do about it?

**Comment by afbora** [comment]
Maybe we can solve with new method name, stupid idea: `::toKeys()`

**Comment by bastianallgeier** [comment]
@afbora I like that suggestion. It's not consistent with `Collection::keys()` but it would definitely avoid the problem here.

**Comment by distantnative** [comment]
I'd be fine with that

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
