### PR TITLE
Implement query templating for more section and field props

### LINKED ISSUE #1823: [Panel fields] Query templates for placeholder
**Describe the bug**
The Blueprint Query Language does not seem to be supported in placeholder fields (at least for Text fields).

In my situation, a parent page has a "default" value stored in a field, and children have a field that can optionally override that field. It would be very helpful to have the "default" value displayed as a placeholder on the children pages.

```
      headline:
        label: Headline
        type: text
        placeholder: "{{ page.parent.defaultHeadline }}"
```

**To Reproduce**
1. Have a parent page with a field
2. Have a child page with a Text field has a placeholder that should display the parent field
3. View the child page in the panel

**Expected behavior**
The stored value of the parent should be in the placeholder text. Instead the string `{{ page.parent.defaultHeadline }}` literally appears as the placeholder.

**Kirby Version**
`3.0.1-rc.1`

### LINKED ISSUE #1862: [Panel] Query language in headline not working
**Describe the bug**
According to the documentation it should be possible to use query language in section headlines:

> The headline for the section. This can be a simple string or a template with additional info from the parent page.

However, a section definition like this displays just a literal string:

```
drafts:
  headline: "Articles for {{ page.title }}"
```

**To Reproduce**
1. Add the above headline to a section in a blueprint
2. Open a page with this blueprint in the Panel

**Expected behavior**
The query template should be resolved.

**Kirby Version**
All Kirby versions up to 3.2rc2

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
Implement query templating for more section and field props

## Related issues
- Fixes #1823
- Fixes #1862 

## Todos
- [ ] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [x] Fix code style issues with CS fixer and `composer fix`
- [ ] If needeed, in-code documentation (DocBlocks etc.)

### CODE REVIEW

**Review by bastianallgeier — CHANGES_REQUESTED** [review]
The tests fail so far because the toString method doesn't work if there's no model and we have tests that don't pass a model. I wonder if we should A) fix the tests and always pass a model or B) make it work without a model. I think A) would be better and we probably also need to make the model a required property.

**Comment by distantnative** [comment]
@bastianallgeier Tried to implement A) – I hope I didn't mess up anything else as I had to alter a lot of places.

**Review by bastianallgeier — APPROVED** [review]
It's massive, but I think it's good to have the model as required prop and I cannot find any problems in the code. Let's trust our tests in this case and we still have the RC phase to test this some more.

**Comment by distantnative** [comment]
Just realized, I might need to add actual tests for the new enhancements.

**Pull request merged**
