### PR TITLE
Remove unused local variables

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by afbora** [comment]
Also i found:

````
src/Session/FileSessionStore.php
    118:Local variable '$path' is not used anywhere
    156:Local variable '$path' is not used anywhere
    261:Local variable '$path' is not used anywhere
    
src/Parsley/Inline.php
    38:Local variable '$html' is not used anywhere
````

**Comment by afbora** [comment]
There are also 4 unused imports, do you want me to report?

**Comment by distantnative** [comment]
@afbora but the PR is removing exactly these reported ones

**Comment by afbora** [comment]
Ahh! I think I'm blind 🙈

**Comment by distantnative** [comment]
:D No worries. Unused imports, sure. I am currently trying to activate PHPMD rules that Lukas first had deactivated to do them step by step. With the unused variables I didn't manage to fix all of them, so I haven't activated the rule yet but wanted to already merge these rather straightforward fixes.

**Comment by afbora** [comment]
Unused imports

````
src/Cms/AppCaches.php
    Import 'Kirby\Cache\Cache' is never used
    
src/Cms/AppTranslations.php
    Import 'Kirby\Data\Data' is never used
    
src/Database/Database.php
    Import 'Exception' is never used
    
src/Cms/S.php
    Import 'Kirby\Session\Session' is never used
````

**Review by bastianallgeier — DISMISSED** [review]
It's great to catch such stuff

**Pull request merged**
