### PR TITLE
 Use return value of route:after hook

### LINKED ISSUE #1605: Return value of the route:after hook is ignored
**Describe the bug**
A short section in the guide about Kirby’s Router suggest to use the `route:after` hook to minify the HTML output ([Guide > Routing > route:after](https://getkirby.com/docs/guide/routing#before-and-after-hooks)). Unfortunatly that won't work, as a return value of an event handler will be ignored by the router instance ([./src/Http/Router.php@108](https://github.com/getkirby/kirby/blob/master/src/Http/Router.php#L108)).

**To Reproduce**
Register a custom hook and try to customize the response, as suggested in the guide:

```php
// site/config/config.php

use Kirby\Cms\Page;
use Kirby\Cms\Response;
use voku\helper\HtmlMin;

return [
  'hooks' => [
    'route:after' => function ($route, $path, $method, $result) {
      if (is_a($result, 'Kirby\Cms\Page')) {
        return new Response((new HtmlMinify())->minify($result->render()));
      }
      return $result;
    }
  ],
];
```

**Expected behavior**
The router instance should take the return value of the handler as the new response object. If multiple hooks are registered for the `route:after` hook, each handler should be triggered in sequence and the return value of one handler should be provided as argument to the next handler.

**Kirby Version**
3.0.3

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

It is now possible to modify the router's `$result` using hooks as already documented on the site.

## Related issues

Fixes #1605.

## Todos
- [x] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [x] Fix code style issues with CS fixer and `composer fix`
- [x] If needeed, in-code documentation (DocBlocks etc.)

### CODE REVIEW

**Comment by bastianallgeier** [comment]
After the discussion on Slack yesterday we should really stick to semver rules and not introduce non backwards compatible breaking changes. 

Maybe we can solve the problem by moving back to a response component like in v2 which does not have anything to do with hooks and is just there to pass through output.

**Comment by distantnative** [comment]
@bastianallgeier I think the bigger problem here is that trigger hooks can't return anything and it is very unclear sometimes when/why trigger is use dover apply.

This has also prevented me so far to implement any new hook that is called when no route is found.

**Comment by lukasbestle** [comment]
Hm, I‘m not so sure about being strict with semver. It‘s more for libraries where updates using package managers need to be possible without having to read the changelog.

If we don‘t have any breaking changes at all in 3.x updates, this would lead to two things:

- All big changes will again be bundled in 4.0.0. I think it‘s better to distribute the big changes over time and not have them all together in one release.
- We need to find a lot of workarounds because we can‘t improve things “the right way” just because of breaking changes.

**Comment by lukasbestle** [comment]
I think the hardest part is for us to realize which changes are breaking so that we can put those changes into the changelog.

But I’d say we need to do that anyway. In v2 times we often had breaking-changes without making them explicit in the changelog. I think *that* was the issue, not that we had the changes at all. People ran into issues and had to find out why.

And if we make the changes explicit (maybe in a separate section at the top), imagine what the changelog would look like in 4.0.0.

**Comment by lukasbestle** [comment]
I have an idea how we could avoid the breaking-change here: If a hook function returns `null`, ignore the return value and continue with the last/original value. What do you think?

**Comment by lukasbestle** [comment]
I have implemented it this way now. If you think this behavior is risky as well, feel free to move #1605 and this PR to 3.3.0.

**Comment by bastianallgeier** [comment]
That's a great idea! I moved it to 3.3.0.

**Pull request merged**
