### PR TITLE
Change throw exception for toggle field on required fields

### LINKED ISSUE #2914: [Panel] A non-admin user cannot create new users because no role can be specified
**Describe the bug**
When trying to create a new user while logged in with a non-admin user who has the permission to create users, no roles appear for selection in the user create dialog. Clicking `Create` even though no role is selected fails due to the following error: `error.user.create.permission`.

**To Reproduce**

1. Setup the [plainkit](https://github.com/getkirby/plainkit)
2. Create a new user role with `users.create` permissions
3. Create a new user with this role and log in to the panel with this user
4. Try to create a new user via the panel

**Expected behavior**
All roles except admin should be selectable for a non-admin user when creating a new user.

**Probable cause**
The method [`Roles->canBeCreated()`](https://github.com/getkirby/kirby/blob/6112f1cb8ebf9c36e8a9f97ae08acc910ddbc792/src/Cms/Roles.php#L53) only returns the admin role if a non-admin user is logged in, because `$newUser->permissions()->can('create')` returns false for all other roles. This happens because of the following code in [`UserPermissions->canCreate()`](https://github.com/getkirby/kirby/blob/6112f1cb8ebf9c36e8a9f97ae08acc910ddbc792/src/Cms/UserPermissions.php#L45)

```php
// users who are not admins cannot create admins
if ($this->model->isAdmin() === false) {
    return false;
}
```

with the following changes everything works as expected

```php
// users who are not admins cannot create admins
if ($this->model->isAdmin() === true) {
    return false;
}
```

This has been changed with d83a9582a0463acd8d13b2e028e60cef55ccf43e. Was this accidental or intended and I missed something?

**Screenshots**

**Kirby Version**
3.4.4

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 19042.572
- Browser: Firefox
- Version: 82.0.2 (64-Bit)

### LINKED ISSUE #2917: Bad validation error message for toggle fields
## Describe the bug
When a `toggle` field is defined as `required: true` and the user tries to save a page with the toggle set to `off`, the page is not saved and the user is shown an odd validation error message.

## To Reproduce
- Grab the starterkit
- Edit the `about.yml` blueprint and add the lines from below
- Open the `About us` page in the panel
- Toggle the new toggle field on and off again
- Click save the page
- The form validation fails, as the only valid state of a toggle in Kirby 3, is the active state.

```yml
      certain:
        label: Are you sure?
        type: toggle
        default: false
        required: true
        text:
          - "No"
          - "Yes"
```

## Expected behavior
There are multiple options to deal with this issue:

- Show a more descriptive validation error, explaining which field it relates to and what value it expects
- Remove the option to set the `toggle` field as required, because what's exactly the point of requiring a toggle field, if the only valid state is to have it set to `on`?
- Change the validation rule, but not exactly sure to what?

## Screenshots
image

## Kirby Version
3.4.4

## Console output
HTTP 400 (Bad Request) response from the API endpoint

```json
{
    "status": "error",
    "message": "Invalid form with errors",
    "code": 400,
    "exception": "Kirby\\Exception\\InvalidArgumentException",
    "key": "error.invalidArgument",
    "file": "\/kirby\/src\/Cms\/ModelWithContent.php",
    "line": 771,
    "details": {
        "certain": {
            "label": "Are you sure?",
            "message": {
                "required": "Invalid argument \"-\" in method \"-\""
            }
        }
    },
    "route": "pages\/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
}
```

## Desktop (unrelated)
 - OS: Windows
 - Browser: Chrome
 - Version: 86.0.4240.183

## Additional Information
Related [forum post](https://forum.getkirby.com/t/bad-error-when-saving-required-toggle-field/19950)

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Updated translation key for required field validation message and included quick small fix with reverting a commit.

## Related issues

- Fixes #2917 
- Fixes #2914 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I'm really sorry @afbora. I made a mistake. Your PR is great, but it will lead to a lot of problems with Transifex. We cannot simply reimport the translation files there. The regular workflow is to update the en.json as source file and the Transifex will take care of updating the translations. But when we do that and rename the string, Transifex will remove all translations and replace it with the English version. I haven't thought about that when we talked about it. 

I think the most backward compatible way, would be to leave the translation files as they are and change how the exception is thrown. Sorry :(

**Comment by afbora** [comment]
@bastianallgeier I found this to be the simplest solution. Otherwise, I would have to change the `Exception` class 🤔

**Review by bastianallgeier — APPROVED** [review]
Yep, that's the perfect solution.

**Comment by eXpl0it3r** [comment]
Was that change in the `src/Cms/UserPermissions.php` intentional? Looks like it was added due to a commit revert...

**Comment by afbora** [comment]
@eXpl0it3r We rolled back the previous update because it was incorrect. Yes it is intentional.

**Comment by eXpl0it3r** [comment]
Ah okay, I was just confused seeing such an unrelated commit on this PR and since it was permission related, I thought, I'd rather ask. 😄

**Comment by afbora** [comment]
Yes you are right 🙈 , I included it in this PR as it is a small update. It is already written in the issue description.

**Pull request merged**
