### PR TITLE
Styling fix for the toolbar in the text block

### LINKED ISSUE #5502: [v4] New sticky Writer Toolbar in Block Text preview inconsistent with Writer Field
## Description
The new _sticky_ Writer Toolbar behaves differently when rendered within the WriterField component or within a Block Text preview component. 

**Expected behavior**  
The TextPreview Toolbar position, size and spacing to be more consistent with the Writer Field toolbar.
- More spacing between the toolbar and field content.
- The Toolbar to extent across the available horizontal space. Like it does in the Field. 

**Screenshots**  
image
WriterField Toolbar with good spacing to the fields text content and stretching across horizontally.

image

Toolbar rendered inside TextPreview component has not enough spacing to text content and does not fill the available horizontal space, which looks odd.

## To reproduce
Create a blocks field with the blueprint below and add a new Text Block with some content.
```yaml
type: blocks
fieldsets:
  text:
    name: field.blocks.text.name
    icon: text
    wysiwyg: true
    preview: text
    fields:
      text:
        type: writer
        label: Text
        headings:
          - 2
          - 3
        toolbar:
          inline: false 
```

## Your setup
**Kirby Version**  
4.0.0-alpha.7

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Fixes

- Styling fix for the toolbar in the text block #5502 

Screenshot 2023-08-30 at 12 44 31

### CODE REVIEW

**Comment by bastianallgeier** [comment]
It's not the most beautiful solution in the world with the two toolbars, but there are not too many other alternatives to do this.

**Comment by ovenum** [comment]
Would prefer the less floating toolbar as used in the Writer field, it feels more attached to field it belongs to. 
But also can’t see a better solution for the block toolbar overlapping the writer toolbar. So this looks like the best solution.

**Comment by distantnative** [comment]
Why does it need to stretch full width if it doesn't need the space? Looks a little odd

**Comment by bastianallgeier** [comment]
It really doesn't. That's just closer to what's happening in the textarea or the write field.

**Comment by distantnative** [comment]
Ok only now realized that this if for `inline: false `. But honestly it feels broken like this. Is there no way to not have the padding wrap around?

**Comment by bastianallgeier** [comment]
We could totally solve this with :has 🙈

**Comment by distantnative** [comment]
@bastianallgeier Could we circumvent this with adding lines in this direction?


```css
.k-block-container.k-block-container-type-text {
	padding: 0;
}
.k-block-type-text-input.k-writer[data-toolbar-inline="true"] {
	padding: 0.75rem;
}
.k-block-type-text-input.k-writer:not([data-toolbar-inline="true"])
	> .ProseMirror {
	padding: 0.75rem;
}
```

**Comment by bastianallgeier** [comment]
@distantnative uhh, that's actually pretty nice and simple. Just changed it.

**Pull request merged**
