### PR TITLE
Define DS constant in Composer setups as well

### LINKED ISSUE #1475: Move code from the bootstrap.php to a file that is autoloaded
If a user loads Kirby using the Composer autoloader instead of requiring the `bootstrap.php` file, the contents of the `bootstrap.php` won't be autoloaded as that file is not included in the Composer autoloading config.

We do two things inside it apart from loading the Composer autoloader:

- PHP version check
- Set `DS` constant

To ensure compatibility, we should move these two features to a file that is autoloaded by Composer.

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

The `DS` constant was not available if Kirby was loaded using the Composer autoloader and not the `bootstrap.php` directly.

I decided not to move the PHP version check into an autoloaded file as that check only really makes sense in the CMS context. If Kirby classes are used as a library in another project, you wouldn't want the fatal screen. After all, Composer checks the PHP version anyway at the time of installation.

## Related issues

- Fixes #1475.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I don't feel great about loading another file for just one constant to be honest.

**Comment by lukasbestle** [comment]
It's cached by OPCache, so it shouldn't be a huge issue, but I see your point. What would you prefer?

**Comment by bastianallgeier** [comment]
Maybe this is a good chance to combine aliases, tests and constants into a single config/setup.php and load everything in there. This could also require the helpers directly then.

**Comment by lukasbestle** [comment]
That's a good idea! I will do that later today.

PS: What does `tests.php` do? It looks like it can currently never run as we don't have a `config/tests` directory. 🤔

**Comment by bastianallgeier** [comment]
@lukasbestle that's the autoloader for all test classes. It works as expected as dirname(__DIR__) walks one level up and looks for a test directory there.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
