### PR TITLE
Better error messages for blocks and layout fields 

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

captures_chrome-capture-2022-8-4 (1)

### Enhancements

- Better error messages for blocks and layout fields https://kirby.nolt.io/313

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by distantnative** [comment]
I like the idea to make this more explicit. I would go even further

```
There's an error on the "{field}" field  in block no. {index} using the "{fieldset}" fieldset
```

**Comment by afbora** [comment]
Thanks for the suggestion @distantnative Also do you have suggestion for layout field validation?

````html
<!-- current sytnax -->
There's an error in block {blockIndex} in layout {layoutIndex}
````

**Comment by afbora** [comment]
What do you think following one for layout validation?

````html
<!-- new  syntax -->
There's an error on the "{field}" field in block no. {blockIndex} using the "{fieldset}" fieldset in layout {layoutIndex}

<!-- output -->
There's an error on the "Link" field in block no. 2 using the "Button" fieldset in layout 3

````

**Comment by distantnative** [comment]
@afbora I like it. But also makes me think that we can drop the "no. " from the block message as well. "block 2" or "layout 3" work just fine.

**Comment by bastianallgeier** [comment]
I wonder if we should use "block type" instead of "fieldset". Fieldset is still coming from the builder days and to be honest, I'm not super happy about it. As an editor you select a certain kind of block type to create your page. I don't think the word "fieldset" is very meaningful to editors. It only appears in blueprint definitions. 

The rest of the PR looks great!

**Comment by afbora** [comment]
Finally like that?

````
There's an error on the "Link" field in block 3 using the "Button" block type

There's an error on the "Link" field in block 3 using the "Button" block type in layout 2
````

**Comment by afbora** [comment]
Error texts rephrased ✅

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
