### PR TITLE
fix: #4056 panel redirect without panel access

### LINKED ISSUE #4056: User blueprint: `home` option redirect fails for users w/out panel access
## Description
Setting a frontend URL in the `home` option of a user blueprint (e.g. `home: "{{ site.find('notes').children.first.url }}"`) leads to a pop-up with an error "You are not allowed to access the panel" if `panel: false` is set for that user.

**Expected behavior**  
Forwarding a user without panel access to a frontend URL should not lead to an error. This is a precondition to making use of the Kirby core's login flows for frontend-only users.

As discussed in [this Discord thread](https://discord.com/channels/525634039965679616/921888554521616444).

## To reproduce
1. Install a fresh Starterkit and create an admin user
2. Add `panel: false` and `home: "{{ site.find('notes').children.first.url }}"` to the `user/default.yml` blueprint
3. Try to log in

## Your setup
**Kirby Version**  
3.6.1

**Your system (please complete the following information)**
 - Device: PC
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 95

**Additional context**  
Possibly related to #4054 (probably need to be fixed first, before this will work)

### PR DESCRIPTION
**Pull request by pReya**
## Describe the PR
This closes #4056. With 3.6 the permission check has been moved into `src/Panel/Home.php` when `Home::url()` is being called, so it needs to be disabled in the router via the `auth => false` property in the route definition. Otherwise it will fail before `Home::url()` is even called.

### Fixes
- Redirect for `home:` redirects from the user blueprint, when the user has no panel access #4056 

## Related issues/ideas

- Fixes #4056 

## Ready?

#4077 needs to be merged before. If you agree with this approach I will try to come up with a test case for this.

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
This is not valid solution. Seems working when user already logged. But doesn't work if user try to login (new session) with your `auth = false` solution. You'll get `The JSON response could not be parsed` error.

**Comment by pReya** [comment]
> This is not valid solution. Seems working when user already logged. But doesn't work if user try to login (new session) with your `auth = false` solution. You'll get `The JSON response could not be parsed` error.

@afbora This is another bug. I've created another PR for this problem: #4077. The other PR will need to be merged first.

**Comment by afbora** [comment]
Ohh, sorry I missed that. I'll check that 👍 

Btw you need to change base branch `main` to `develop` for both PR to safely merge.

**Review by bastianallgeier — DISMISSED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Argh, I didn't properly read the required redirect changes before merging. I'll have a look at that asap.

**Pull request merged**
