### PR TITLE
`Http\Uri`: definable schemes

### PR DESCRIPTION
**Pull request by distantnative**
### Refactoring
- Allows modifying allowed schemes for `Http\Uri` when extending via `Uri::$schemes` property

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by afbora** [comment]
For users or an internal extending? I just wonder because of `protected` property.

**Comment by distantnative** [comment]
For my use case (UUIDs) it would work with protected (as I am extending `Uri` and then the child class can redefine the allowed schemes. But if you think this would be useful as public, we can do that too.

Maybe @lukasbestle has a thought if that would be a security risk potentially?

**Review by lukasbestle — COMMENTED** [review]
I think it's sensible to keep this protected just for internal use. Different URI types should have a separate class to avoid confusion.

We could even make it a class constant to make this internal nature even more clear.

**Comment by distantnative** [comment]
@lukasbestle I would leave it a property as for the UUID uri we might want to make it a public property to allow developers extending the supported UUID schemes... a bit far fetched, but I think leaving it as property would be fine then.

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
