### PR TITLE
Fix pasting blocks in block selector

### LINKED ISSUE #5109: [3.9.2] Blocks field: copy/paste regression
@distantnative is it possible that I found a regression on this fix. Nothing breaking though. I've tested it with a plainkit to be sure it has nothing to do with my setup:

* When you copy a block and paste in the "add block" area it doesn't work
* When copy copy a block and paste in the dedicated "paste block" area, it does work

Screen recording: https://x.gnx.li/js9MwZH8

_Originally posted by @samzzi in https://github.com/getkirby/kirby/issues/4282#issuecomment-1472757094_

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

@afbora maybe you can help checking that this doesn't break other use cases in turn

### Fixes
- Fixed issue with pasting blocks in block selector dialog 
#5109

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by afbora** [comment]
99.99% seems to work great 🎉 There is only a very slight difference with block copying in 3.9.1. What is the reason for this?

### Steps to reproduce

- Add heading and image block
- Copy heading block
- Click once on image (no edit)
- Paste view CMD/CTRL + V
- Nothing happens (paste working on 3.9.1)

**Comment by distantnative** [comment]
@afbora seems to work for me - am I doing something differently than you?

https://user-images.githubusercontent.com/3788865/226192689-79b7d246-a85f-4832-96cc-95e856cea120.mov

**Comment by afbora** [comment]
@distantnative No luck, still same. Could you follow another reproduce steps for your sample:

- Copy first block
- Click to first block to focus/inline editing
- Press TAB multiple times until to focused second image block
- Paste copied block via CMD/CTRL + V
- See issue is nothing happened

**Comment by distantnative** [comment]
@afbora could reproduce it now and might've found a fix (that hopefully doesn't break something else)

**Review by afbora — APPROVED** [review]
Seems works great 🎉

**Pull request merged**
