### PR TITLE
DELETE `lock`: fail gracefully if already deleted

### LINKED ISSUE #4897: `The page "*" cannot be found` error when page deleted
## To reproduce

1. Create a page from panel
2. Edit the page without save
3. Try to delete
4. See error console (a dialog appears very quickly, closes, and sometimes remains visible)

## Your setup
**Kirby Version**  
3.8.3-rc.1 & 3.8.x (and probably 3.7.x, not tested yet)

**Console output**  
````json
{
    "status": "error",
    "message": "The page \"blog/test\" cannot be found",
    "code": 404,
    "exception": "Kirby\\Exception\\NotFoundException",
    "key": "error.page.notFound",
    "file": "/test/kirby/starterkit-3.8.3-rc.1/kirby/src/Cms/Find.php",
    "line": 85,
    "details": [],
    "route": "(.*)/lock"
}
````

### PR DESCRIPTION
**Pull request by distantnative**
Fixes #4897

### Fixes
- Fixed console errors for failed `lock` request when deleting page with unsaved changes
#4897

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by afbora** [comment]
This PR fixes the issue 👍 But we can think make it for also should apply for `PATCH` routes. Because If a lock request comes at a time when there is no page, it will still give an error. Rare but possible :)

**Review by afbora — DISMISSED** [review]

**Comment by distantnative** [comment]
Can you produce such a situation? I'm. It sure what the right return value in the case for PATCH would be. If we have an actual situation, maybe we know.

**Comment by afbora** [comment]
I reduced the `/lock` request seconds to less than 10 seconds (because it was unlikely that I would make a request at exactly the 10th second), I could see the error dialog.

> The page "notes/test" cannot be found

Like I said, it's unlikely, but it could happen.

**Comment by distantnative** [comment]
Hmm, this is difficult. I think if we return `false`, we will get an error as well. But passing `true` seems wrong - if the page cannot be found the lock info wasn't updated at all.

**Comment by lukasbestle** [comment]
I feel this behavior is caused by a race condition in the Panel frontend rather than by the API. I think the proper solution would need to be that the Panel no longer requests locks after the delete request for the page was sent.

**Comment by distantnative** [comment]
> I feel this behavior is caused by a race condition in the Panel frontend rather than by the API. I think the proper solution would need to be that the Panel no longer requests locks after the delete request for the page was sent.

I tried to find that but I couldn't. Can't stop locking quickly enough after deletion to not have the lock request already sent. So this is the only solution I could come up, I think it's better than none (and for the DELETE request I think the current implementation also makes sense).

**Review by lukasbestle — DISMISSED** [review]
I agree. If we find the source of the race condition for `PATCH` later, we can still fix that independently.

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
