### PR TITLE
Replace event bus with mitt

### PR DESCRIPTION
**Pull request by distantnative**
## Status: ready for review 👀

One small preparation for Vue 3 migration (eventually, down the road)...
https://v3.vuejs.org/guide/migration/events-api.html#_3-x-update

## Breaking changes
_Calling the `this.$events` methods should exactly work as before._

## Related issues
- Contributes to #3189

## Ready?

- [x] CI passes (runs automatically when the PR is created or run `composer ci` locally)
  Running locally requires PHPUnit, PHP-CS-Fixer, Psalm, PHPCPD and PHPMD.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Do you know how big mitt is?

**Comment by distantnative** [comment]
200 bytes gzipped - that's what they claim

**Comment by distantnative** [comment]
We could compare it with https://github.com/scottcorgan/tiny-emitter - mitt just seems the most favoured one looking around Vue 2 > 3 migration guides.

**Comment by distantnative** [comment]
Current `develop`:
Screen Shot 2021-05-05 at 17 02 14

With this PR/mitt:
Screen Shot 2021-05-05 at 17 02 54

**Comment by bastianallgeier** [comment]
How is it smaller with that package? 🤣🤣🤣

**Comment by distantnative** [comment]
Vendor grew slightly. But don't ask me about all this bundling voodoo!

**Comment by bastianallgeier** [comment]
oh, right. Slightly like in 30 kb 🙈  Not sure why I missed it.

**Comment by distantnative** [comment]
I hope rather 0.30 and not full 30! :D

**Comment by bastianallgeier** [comment]
Oh god. I probably need a break. 🤣  Ok, let's not worry about the size of mitt any longer. The rest looks great.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
