### PR TITLE
Use `await this.$nextTick()`

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I can't test the PR right now, but need those methods all be changed to async for this to work?

**Comment by distantnative** [comment]
@bastianallgeier you can't use `await` inside a function that's not marked `async`. But technically those already have been async in the past due to passing a callback to `$nextTick` so far.

**Comment by afbora** [comment]
I've tested the PR, looks working great 👍

**Comment by bastianallgeier** [comment]
Yikes, I tried to resolve the merge conflicts but failed. @distantnative could you give it a try.

**Comment by afbora** [comment]
Sorry, I just realized the conflict after the commit 🙈 Now I've pushed a commit. I hope it's correct 🙂

**Pull request merged**
