### PR TITLE
Set default language in multi-language setups

### LINKED ISSUE #3647: When logging into the Panel in a multi-language installation, the preselected content language is not the default language.
**Describe the bug**  
In Kirby 3.5.7.1 (and probably earlier versions), when you have a multi-language setup with German as default and English as secondary language, and you log in to the Panel, the content language switcher defaults to the default language (in this case this would be German).

From my tests it seems as if Kirby remembers which language version I was working on last, because when I log out while in the German default translation and then log back in, I am back in the German version. However, when cookies and sessions are deleted, I return to the English version. This happens independent of the selected user language.

**To Reproduce**  
1. Set up a multi-language Starterkit with German as default and English as secondary language
2. Log into the Panel
3. Watch the language switcher default to the secondary language.

**Expected behavior**  
I would expect the same behavior as in 3.5.7.1.

**Kirby Version**  
Tested with 3.6.0-alpha-4

**Desktop (please complete the following information):**  
Mac OS11.2.2  with Firefox 91.0 (64-bit)

**Additional context**  
https://forum.getkirby.com/t/default-language-not-used-after-login/23207/5

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Related issues/ideas

- Fixes #3647

## Ready?

- [x] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
language

I tested this issue with this PR, and the issue I'm having seems to be the subject of this PR as well.

**Steps to reproduce**

1. TR default, EN, secondary, EN user language
2. You'll see login screen as default language
3. Log-in panel
4. You will see some parts in Turkish and some parts in English
5. Logout
6. You will see login screen as English
7. When you refresh login screen, you'll see Turkish again

**Comment by distantnative** [comment]
@afbora I think you're describing a different/new problem though. The referenced issue is about the content language being wrong, but it looks as you reporting that the Panel UI language is wrong

**Comment by bastianallgeier** [comment]
I agree. It's translation vs. content language. If the default content language is now loaded correctly in your tests, we should still merge this and create a new issue for the weird translation issue.

**Review by afbora — APPROVED** [review]

**Comment by distantnative** [comment]
@afbora will you test again and open a new issue if you still encounter your issue?

**Comment by afbora** [comment]
Already created https://github.com/getkirby/kirby/issues/3725 The title may not be very clear 😅

**Comment by distantnative** [comment]
Overlooked, sorry!

**Pull request merged**
