### PR TITLE
`PageTree` controller class

### PR DESCRIPTION
**Pull request by distantnative**
### Summary of changes
- Moved page tree request logic from area config to `PageTree` Panel controller clas
- Added unit tests

### Reasoning
Make more code testable.

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### CODE REVIEW

**Comment by afbora** [comment]
@distantnative I couldn't test moving the page for this branch or v5 (disabled all parents). Works great for v4. Could you able to move any page with this branch?

**Comment by distantnative** [comment]
@afbora does it work now for you?

**Comment by afbora** [comment]
@distantnative Still broken for me. Now I can move any page to any target. This is not correct behavior.

**Comment by distantnative** [comment]
@afbora what's your test case where the result of this PR is different to `develop-minor`?

Mine is using the starter kit and creating a test `note` page on the top-level. That `note` page I can move in the same pages on this branch as on `develop-minor` with certain pages disabled:

`develop-minor`:
Screenshot 2024-10-08 at 2 56 54 PM


This PR:
Screenshot 2024-10-08 at 2 55 41 PM

**Comment by afbora** [comment]
I was tested for starterkit with `v5/refactor/page-tree-controller-class` branch.
v5-develop test_panel_site

Something wrong. I've tested on 4.4.1 for `Exploring the universe` page. It should be like that as default.
4 4 1 test_panel_site

**Comment by distantnative** [comment]
Oh interesting, this seems to be rather a difference `main` vs. `develop-minor` branch. Not this PR. I wonder why.

**Comment by distantnative** [comment]
@afbora I think it's because of https://github.com/getkirby/kirby/pull/6717

**Comment by bastianallgeier** [comment]
I'm pretty sure it's caused by this PR https://github.com/getkirby/kirby/pull/6717

**Comment by bastianallgeier** [comment]
@distantnative haha, I posted the exact same comment basically 4 seconds after yours :)

**Review by afbora — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Is the failing unit test a false positive?

**Comment by distantnative** [comment]
They were still set up for the `no pages section needed` state.

Fixed them and added more specific ones too.

**Pull request merged**
