### PR TITLE
Supports list items in info fields #2946

### LINKED ISSUE #2946: Lists not displayed properly in Info field
**Describe the bug**
Ordered and unordered lists in info fields are not displayed with a number or bullet:

image

**To Reproduce**  
Add the following field:

```yml
type: info
label: Publish Checklist
text: |
  1. Check the URL (slug)

  - foo
  - bar
```

**Kirby Version**  
3.4.2

### PR DESCRIPTION
**Pull request by afbora**
### Sample Blueprint

````yaml
fields:
  test:
    type: info
    label: New Info Texts
    text: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan augue non bibendum facilisis. Fusce in lectus quis enim euismod aliquam. Donec cursus placerat tellus, eu eleifend ante porttitor eget. 
      
      1. Mauris quam metus, convallis et tempor at, posuere sed ex. Suspendisse potenti. 
      2. Vestibulum elementum finibus gravida. Cras bibendum quam at felis commodo porta. 
      3. Aliquam non enim nulla. Morbi placerat ultrices nunc non dapibus. Etiam imperdiet tincidunt diam, non rhoncus lorem bibendum nec. 
      
      Quisque id turpis semper elit auctor tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere leo sapien, quis suscipit sapien mollis eget. Nulla facilisi. Vivamus facilisis, lacus ut scelerisque consectetur, orci mauris maximus ligula, vitae rhoncus magna orci eu augue. Mauris convallis, ipsum gravida mattis imperdiet, quam elit efficitur tellus, volutpat venenatis neque orci quis tortor.
      
      - Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 
      - Quisque a laoreet augue. 
        - Curabitur rhoncus cursus est ac consequat. 
        - Curabitur aliquet, augue quis rhoncus feugiat, neque sapien rhoncus velit, nec accumsan elit ex sed nisl. 
      - Morbi fermentum, mauris eu aliquet finibus, mi ex aliquet lacus, ac imperdiet nisi urna non ligula. Suspendisse vitae posuere purus. 
      
      Duis sit amet odio in nunc vehicula molestie ut id felis. Nunc varius euismod eros at sodales. Sed consequat vel enim at hendrerit. Praesent maximus pellentesque elit eu tincidunt. Nullam gravida nibh in augue laoreet, eu volutpat lacus sagittis. Integer rhoncus pulvinar condimentum. Nunc blandit magna at ligula dapibus, quis consequat odio venenatis. Etiam efficitur urna sit amet metus porta, sed consectetur diam placerat. 
      
      1. Aliquam vel 
         1. sapien sollicitudin 
         2. eleifend 
         3. nec a lacus
      2. ligula feugiat 


````

### New View

screen-capture-691-Home - Mægazine-localhost

## Related issues

- Fixes #2946 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Added in-code documentation (if needed)
- [x] CI passes (runs automatically when the PR is created or run `composer ci` locally)
  Running locally requires PHPUnit, PHP-CS-Fixer, Psalm, PHPCPD and PHPMD.

- [x] Checked whether the PR needs documentation, if needed added to the [release docs checklist](https://github.com/getkirby/getkirby.com/pulls)

### CODE REVIEW

**Comment by texnixe** [comment]
@afbora How about making the nested indents line up with the indent of the upper levels?

**Comment by afbora** [comment]
@texnixe You're meaning the top indent of list-items lining up with the paragraphs, right?

**Comment by texnixe** [comment]
No, I meant the indentation of the nested list items.

**Comment by afbora** [comment]
@texnixe Like that?

screen-capture-694-Home - Mægazine-localhost

**Comment by texnixe** [comment]
I think the nested level should be indented to where the text of the parent level starts (at least that's what I would prefer).

**Comment by afbora** [comment]
I think I'm too close? 😅 

screen-capture-697-Home - Mægazine-localhost

**Review by bastianallgeier — DISMISSED** [review]

**Comment by afbora** [comment]
@bastianallgeier @texnixe  asked for a few improvements, but I didn't implement it because we didn't make the final decision. Do you think the first comment is good?

**Comment by bastianallgeier** [comment]
I saw this too late. I think ideally we would have a single axis like this …

105911672-79ef6080-603b-11eb-82ae-dddbe22b3348

**Comment by afbora** [comment]
It's actually so easy but to be honest, I couldn't understand exactly what style it would be, I'm sorry 🙈

**Comment by bastianallgeier** [comment]
I removed the list style position and now it looks fine in my opinion. 

Screenshot 2021-01-28 at 13 47 54

**Review by bastianallgeier — APPROVED** [review]

**Comment by afbora** [comment]
This is great. Thank you for taking care 👍

**Pull request merged**
