### PR TITLE
Unify collection methods

### PR DESCRIPTION
**Pull request by distantnative**
@lukasbestle Is that the direction we discussed (from your view)?
Still running into 2 unit tests failing.

We also talked about `find` and `findBy` but those don't seem as straightforward to me.

### CODE REVIEW

**Comment by lukasbestle** [comment]
The general direction (code in `filter/group/sort` and aliases as `filterBy/groupBy/sortBy`) is what we discussed. I agree on `find/findBy` – with their similar argument syntax it will likely not be possible to merge them. But I'd say that's fine. Better to unify the other methods than none.

I haven't reviewed the code in detail yet in the draft state. Feel free to request a review once the PR is ready, also let me know in case you want any help. :)

**Comment by distantnative** [comment]
@lukasbestle I don't quite get why `phpunit tests/Toolkit/CollectionTest` gives me

```
1) Kirby\Toolkit\CollectionTest::testGroupByWithInvalidKey
Failed asserting that exception of type "Exception" is thrown.
```

but `phpunit tests/Toolkit/CollectionTest --filter=testGroupWithInvalidKey` runs without failures.

**Comment by afbora** [comment]
@distantnative First, you actually wrote wrong the method name on filter, so missing `By` and should be like following to get failure 😅

    phpunit tests/Toolkit/CollectionTest --filter=testGroupByWithInvalidKey

Second, as you know you may forgot to throwing an `Exception` for a non-string parameter like in current `groupBy` method:

````php
if (is_string($field) === false) {
    throw new Exception('Cannot group by non-string values. Did you mean to call group()?');
}

**Comment by distantnative** [comment]
🙈 stupid haha. thanks for pointing out the typo.

**Comment by afbora** [comment]
@distantnative Missing one more `sortBy()` method:
https://github.com/getkirby/kirby/blob/refactor/collection-methods/src/Toolkit/Collection.php#L864

**Review by bastianallgeier — DISMISSED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
