### PR TITLE
Fix for issue #5042 Page::create ignores isDraft prop 

### LINKED ISSUE #5042: Page::create ignores isDraft
## Description

The code I have written to populate a blog with a mix of drafts and published articles prefixed with the value from the date field for sorting fails, all pages are drafts. The `isDraft` prop is documented here https://getkirby.com/docs/reference/objects/cms/page/create.

## To reproduce

1. `composer create-project getkirby/plainkit`
2. Change dir into the project
3. `composer require fakerphp/faker`
4. Create a file `seed-blog.php` in the root of the project with the following:

```
<?php

use Kirby\Cms\Page;

require 'kirby/bootstrap.php';

$app = new Kirby();
$app->impersonate('kirby');

$blog = $app->site()->find('blog');

$faker = Faker\Factory::create();
$faker->seed(12345);

for ($i = 0; $i < 100; $i++) {
    $date = $faker->dateTimeThisDecade();
    $page = Page::create([
        'parent'   => $blog,
        'slug'     => $slug = join('-', $faker->words(5)),
        'isDraft'  => $faker->boolean(25),
        'template' => 'article',
        'content'  => [
            'title' => $faker->sentence(),
            'date'  => $date->format('Y-m-d H:i:s'),
            'body'  => $faker->paragraphs(5, true),
        ],
    ]);
}
```

4. Create `content/blog` folder
6. Create `site/blueprints/pages/article.yml` with the following:

```
num: '{{ page.date.toDate("Ymd") }}'

fields:
  date:
    type: date
  body:
    type: textarea
```

7. `php seed-blog.php`

**Kirby Version**  

3.9.1

### PR DESCRIPTION
**Pull request by SeriousKen**
## This PR …

Fixes code to match documentation for props array, also allows creation of unlisted pages by setting `isDraft` prop to true and leaving `num` empty (this currently doesn't work). Fixes issue https://github.com/getkirby/kirby/issues/5042

### Fixes
Issue https://github.com/getkirby/kirby/issues/5042

### Breaking changes
Should not introduce breaking change

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by distantnative** [comment]
@SeriousKen Thanks for starting to tackling this but we cannot just throw away the `drafts` key that would be a big breaking change as users currently are using it to create draft pages. 

I think for now we really need to support boths keys.

**Review by SeriousKen — COMMENTED** [review]
Updated PR to allow both draft and isDraft props

**Comment by distantnative** [comment]
@SeriousKen would you be able to add unit tests that cover both cases:
- providing a `draft` prop that with this PR is finally respected
- providing a `draft` prop but also an `isDraft` prop checking that the provided `isDraft` prop isn't overwritten but the one used
?

If not, we'll try to see when we can add them before we can merge this PR. Thanks :)

**Comment by SeriousKen** [comment]
I've added test cases that should cover those two cases.

**Review by afbora — APPROVED** [review]

**Review by distantnative — APPROVED** [review]

**Pull request merged**
