### PR TITLE
`Obj::set()` method

### PR DESCRIPTION
**Pull request by distantnative**
## Enhancement
- New `Obj::set()` method

## Breaking changes

None

## Related issues/ideas

- Fixes #

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
There is a magic property getter and returns `null` but no setter. Is it normal?

**Comment by distantnative** [comment]
I was also a bit confused why the magic setter returns null... but when I change that, everything blows up :D 
The magic setter is inherited from `stdClass` I think.

**Comment by bastianallgeier** [comment]
The magic getter is only taking affect when the property does not exist. The concept behind this is that `$obj->doesNotExist` no longer throws an Exception with the magic getter but returns null instead. 

The logic within the getter is a bit weird though. It would totally be fine to write: 

```php
public function __get() {
  return null;
}
```

There's no magic setter because setting was handled via $obj->newProp = 'something'

To be honest, I'm still not sure if we actually need a set method here. The Obj class is intended to be the most basic upgrade for stdClass. When we introduce a set method, we also need to make sure to use that in a new magic setter and that there's a get method. Otherwise it wouldn't make sense in my opinion.

**Comment by afbora** [comment]
Hmm, why we don't use like that? Doesn't it make more sense than returning `null`?

````php
public function __get(string $property)
{
    return $this->get($property);
}
````

**Comment by bastianallgeier** [comment]
The magic getter is never called when the property exists.

**Comment by distantnative** [comment]
You're right. Somehow my mind thought there was a `get()` method and thus `set()` was missing. But let's stay without both of them.

**Pull request closed without merging**
