### PR TITLE
Fix invalid date in table layout

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

I've found a simple solution that shows custom value prop if defined. Otherwise date preview handles rest. I hope it's correct solution.

### Fixes
- "Invalid Date" parsing dates in pages section with layout:table #6230

### Breaking changes
None

## Ready?

- [x] In-code documentation (wherever needed)
- [x] ~Unit tests for fixed bug/feature~
- [x] Tests and checks all pass

### For review team

- [x] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I think we can keep it even simpler by checking for a valid parsed date and fall back to the raw value. This would still allow date parsing for the custom column value. I also added lab examples. Could you give it another quick look if you agree with my solution?

**Comment by afbora** [comment]
@bastianallgeier It works but this creates inconsistency.

screen-capture-1829-Notes - Mægazine-localhost

**Comment by bastianallgeier** [comment]
What are the values for those rows?

**Comment by afbora** [comment]
For first one: 2023-11-24 16:00:00
The last one: 2020-09-05 00:00:00

You can test on notes pages in starterkit with:

````php
return [
    'date.handler' => 'intl',
];
````

````yaml
sections:
  listed:
    extends: sections/notes
    label: Published
    status: listed
    layout: table
    columns:
      date:
        value: "{{ page.date.toDate('dd.MM.Y') }}"
````

**Comment by bastianallgeier** [comment]
Ah, now I understand. The custom value is leading to dates, which cannot always be parsed. Some of them work. Some of them don't. I would say that we should accept this as a limitation, because you can still work around it by switching the column type to text. 

@distantnative do you have an opinion on this?

**Comment by distantnative** [comment]
I agree, I think after all the `value: "{{ page.date.toDate('dd.MM.Y') }}"` is using it incorrectly.

Then again, that's mainly because I don't think we have column types documented in a good way (which would be then the proper way to get the right preview).

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
I would merge this fix for the next patch and then we should also take care about the column type docs.

**Pull request merged**
