### PR TITLE
Add users section for panel

### PR DESCRIPTION
**Pull request by afbora**
### WIP PR

Now we have a section to list users. 
May I have your opinion for the first stage of PR, please? @distantnative 🙏 

I didn't know what the section's `model` data should be for users `section`? 
Could it be a site as `'model' => $this->site()`?

**Sample usage**

````yaml
sections:
  users:
    type: users
    roles: 
      - editor
      - user
    sortBy: birthdate desc
    query: kirby.users.filterBy('birthdate', '<=', date('Y-m-d H:i:s'))
    text: "{{ user.email }}"
    info: "{{ user.birthdate }}"
````

## Related issues

- Closes https://github.com/getkirby/ideas/issues/422

## Ready?

- [x] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by REHvision** [comment]
Thanks @afbora for working on this! :heart: 

I've built my own users section plugin since I need this quite frequently (it works but it's kind of hacky and I got stuck refactoring it).

Now I think it's best to just wait for the core users section and hope it lands in one of the next Kirby versions :wink:

**Comment by afbora** [comment]
@REHvision I hope to see this feature in the upcoming Kirby versions 👍

**Comment by distantnative** [comment]
Will have a look at it once we have merged our bigger UI changes.

**Comment by afbora** [comment]
@distantnative An already incomplete PR. If it will take more time to review and correct it, I think we can close it to create fresh one.

**Comment by distantnative** [comment]
I think sections might change quite a bit once the big storybook branch is integrated. So it might be good to put this one to the side for now, close the PR and revisit it once the bigger changes are implemented.

**Comment by afbora** [comment]
We look forward to storybook 😄

**Comment by distantnative** [comment]
Trust me, we all do XD

**Pull request closed without merging**
