### PR TITLE
Fix number field issues #2306

### LINKED ISSUE #2306: Number field auto-removes decimals if step option is not set.
**Describe the bug**  
If you enter a decimal value into a number field that has no decimals defined, as soon as the field is no longer focused, the decimals are cut off without an further hint that there was something wrong with the data. Shouldn't the field validate the entered value?

**To Reproduce**  
1. Define a number field without the step option
2. Go to the Panel and enter a number with decimals and save.
3. See as when you leave the field, the decimals are removed without any explanation, but the save bar pops up again.

**Expected behavior**  
Maybe the field should come up with a warning rather than popping up the save bar and auto-removing the decimals as the current behavior is somewhat confusing.

**Kirby Version**  
Tested with Kirby 3.3.0.

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

- Decimals are no longer removed by default
- Empty values are stored correctly again

## Related issues

- Fixes #2306 & #2288

### CODE REVIEW

**Review by afbora — COMMENTED** [review]
After I finish writing the number, if I click outside the input after saving the page while still focus on number input, the value changes (with step option) and the savebar appears (always).

number

**Comment by afbora** [comment]
https://github.com/getkirby/kirby/blob/fix/2306-keep-decimals/panel/src/components/Forms/Input/NumberInput.vue#L111

@bastianallgeier I guess, is that supposed to be like that?

````js
this.number = this.format(value);
````

**Comment by bastianallgeier** [comment]
@afbora yes! Otherwise the formatting would be happening instantly when you type and strange side effects happen.

**Comment by afbora** [comment]
> this.number = this.format(value);

@bastianallgeier New commit?

**Comment by bastianallgeier** [comment]
We cannot solve the problem of the save bar in any other way. The forced formatting fixes for the number field have to happen once you focus on another field. They cannot happen when typing in the field. That's why it can happen that the value changes again. But I think this is fine.

**Comment by afbora** [comment]
Hmm.. I'm not sure but how about we check that the value really changes in this way? Seems to be working 🤔 

````js
onChange(value) {
  this.number = this.format(value);
  
  if (value !== this.number) {
    this.$emit("input", this.number);
  }
},
````

**Comment by bastianallgeier** [comment]
@afbora I don't really understand the idea behind it

**Comment by afbora** [comment]
Since `onChange()` run when we focus out the input after saving the value, let `$emit()` run if the value in the input has actually changed.

Now, whether the value changes or remains the same bar is constantly coming out after focus out.

**Comment by bastianallgeier** [comment]
Ok, I think we are overthinking this issue for the benefit of a small visual improvement. I reverted everything to let the HTML number input decide. Decimals are not shown when they are just .00 and I think this is actually fine. Whenever we tried to "improve" the number input it went down the drain and we introduce bugs that were completely unnecessary. 

How do you feel about this @distantnative, @lukasbestle, @texnixe?

**Comment by bastianallgeier** [comment]
I take everything back. I think I have a solution now that's somewhere between what I came up with first and what @afbora suggested. Could you have a look at it again @distantnative @lukasbestle @texnixe

**Comment by bastianallgeier** [comment]
I decided to merge this now. It's a lot better than the solution in 3.3.0 and if we find additional issues in the RC we can still fix it.

**Pull request merged**
