### PR TITLE
`layout: table` for pages and files sections

### PR DESCRIPTION
**Pull request by distantnative**
### Feature

- Adds `layout: table` option to pages and files sections
  Screen Shot 2022-05-31 at 16 43 25
  Screen Shot 2022-05-31 at 16 43 15

  ```yaml
  notes:
        type: pages
        layout: table
        columns:
          tags:
            label: Tags
            type: tags
          author:
            label: Written by
            value: "{{ page.authors.toUsers.first.name }}"
          crazy:
            label: My HTML
            value: "{{ page.myHtmlMethod }}"
            type: html
  ```

### Enhancements
- New `k-image-field-preview` and `k-flag-field-preview` components
- `k-items` supports table layout

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
Great job @distantnative Love that ❤️ 

Few points:

1. Not match box when search

screen-capture-1428-Notes - Mægazine-localhost

2. Just a question: Is it possible followings for different cases (especially virtual pages)?
- Disable title
- Disable title link
- Change title column order

**Comment by distantnative** [comment]
@afbora on no. 2: none of these is supported right now

**Comment by distantnative** [comment]
@afbora ok now it does, also fixed empty state

```yaml
type: pages
layout: table
text: false        #disables default title column
info: false       #disables default info column
columns:
  tags:
    label: Taggy
    type: tags
  title:
    label: Title moved and as normal text
```

**Comment by afbora** [comment]
@distantnative In general, the sorting/sortable part of the sections (not just for table layout) is broken.

**Comment by distantnative** [comment]
Arg probably related to my mixin shuffling, shouldn't have started with that.

**Comment by afbora** [comment]
### `min/max` validation issue steps on starterkit

1. Set `min: 1` and `max: 2` of images section in `album.yml`
2. Go to panel
3. Add new album
4. Upload 1 image to album
5. Change status page as `public`
6. Delete all images or upload more images from `content` folder manually
7. Refresh the page
8. See error highlight on images section
9. Edit headline or any input
10. Try to save page and success (should throw error)

**Comment by bastianallgeier** [comment]
@afbora could you try that with the stable release? I'm pretty sure this is one of the logic issues that we already had before.

**Comment by afbora** [comment]
@bastianallgeier You're right. Just like you said 💯 

So looks great and ready to merge for me 👍

**Review by afbora — DISMISSED** [review]
❤️

**Comment by bastianallgeier** [comment]
@afbora thank you for testing again. I'm currently trying to fix the coverage issues.

**Comment by bastianallgeier** [comment]
I give up on our CI workflow today. This PR is ready in my opinion. I've added a couple more tests that should get coverage right. I hope tests run through on develop at some point, so I'll merge it now.

**Pull request merged**
