### PR TITLE
Bring back `DS`

### PR DESCRIPTION
**Pull request by distantnative**
- [x] Remove from breaking change list

### CODE REVIEW

**Review by lukasbestle — APPROVED** [review]

**Comment by psterker** [comment]
Sadly, this will clash with other tools like PHPStan or Laravel, resulting in the following warning:

`Warning: Constant DS already defined in /my-project-path/kirby/config/setup.php on line 7` 

A simple `if (!defined('DS'))` check would do the trick.

**Comment by lukasbestle** [comment]
Making the definition lazy (skipping it if it already exists) prevents the code from behaving deterministically.

However we could remove the constant in v4 entirely (given it was already deprecated in 3.8). What do you think @distantnative?

**Comment by distantnative** [comment]
@lukasbestle yes, no objection from my side

**Comment by lukasbestle** [comment]
For reference: #5590

**Pull request merged**
