### PR TITLE
File: fix not creating PDF as different format

### LINKED ISSUE #6268: File blueprint: error when create/format option is set and document is uploaded
## Description
When a file blueprint has the format option set so that images get converted to another format, uploading a PDF results in an error `imagecreatefromstring(): Data is not in a recognized format `. The uploaded file is corrupt due to the conversion process.

**Expected behavior**  
Images should be converted to the format defined in the blueprint. Any other file should be uploaded as is.

**Screenshots**  
image
image

## To reproduce
1. Create a new file blueprint or use default file blueprint.
2. Add the following properties to the blueprint: 
```
create:
  format: webp
```
3. Upload a PDF using that blueprint

## Your setup
**Kirby 4.0.1 up to 4.1**  

**Console output**  
image
First error while uploading. Second error while trying to get a thumbnail for the uploaded PDF that doesn't exist.

**Your system (please complete the following information)**
 - Device: Macbook
 - OS: macOS
 - Browser: Firefox
 - Version: 122.01

**Additional context**

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

If we change the extension first, `$file->isResizable()` will test for the new/target format, not the original one (e.g. PDF).

### Fixes
- File `create` `format` option is not applied to non-images anymore 
#6268

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and checks all pass

### For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
Should it be intended behavior that non-images are allowed through? TBH I would rather expect that every file uploaded with that file blueprint will have the configured target format. This would mean that any upload of a file that cannot be converted would fail.

**Comment by distantnative** [comment]
@lukasbestle I think this has been the intended behavior: https://github.com/getkirby/kirby/blob/main/src/Cms/FileActions.php#L327 - only that this failed as the extension already had been changed and thus comparing by the extension would create false results for the check. I would keep the logic as is and only fix the bug.

**Comment by lukasbestle** [comment]
That link you point to concerns resizing though, not file format conversion. I'd say that it's expected that a file that cannot be resized won't be resized. But if I say that I want format X when format Y is uploaded, isn't it unexpected to get format Z instead? TBH I never thought about that before this issue.

**Comment by distantnative** [comment]
@lukasbestle you sure? I thought the thumbs component also takes care of the format conversion

**Comment by distantnative** [comment]
It's only that the check back then was named `isResizable()` - but it's actually more a check for "is darkroom processable" as it also covers the format or alterations like b/w etc.

**Comment by lukasbestle** [comment]
Ah, right. To me that looks even more like we simply didn't consider this case before.

First we had resizing (which of course doesn't apply to PDFs or other file types). Now we have the option to convert the file to a different format entirely (which can lead to the expectation that all files will have the configured format).

Maybe let's get the author of the issue @JerikoOne involved. You wrote in the expected behavior section that other files should be uploaded as is. I'm curious: Is it really expected for you in your use case to have a single file template that can have files with completely different types?

**Comment by distantnative** [comment]
I think this is something we should leave in the hand of the developers. Kirby is best at where it allows some flexibility like that instead of being too restrictive that people have to jump around hurdles if they still want to allow that.

So I would really want to merge this PR to fix the existing bug and not dive too much into the general debate whether we should reconsider the mechanism in general.

**Comment by lukasbestle** [comment]
You are right, makes sense. If we'd block it, there would be no way for our users to change this behavior. So I agree, let's fix the bug.

I think we should document this though with an info block. If the format should be enforced, the file type needs to be restricted separately in the blueprint.

**Review by bastianallgeier — APPROVED** [review]
LGTM

**Pull request merged**
