### PR TITLE
Writer: adding link, insert text when no selected

### LINKED ISSUE #5661: [v4] Writer field: confusing link button with no selection
## Description
When you click the link button in a Writer field without selecting text it results in an empty/invisible link. Combined with there being a "Title" field it's very confusing.

link

**Expected behavior**  
A fallback text with the URL should be used.

## To reproduce

1. Add a writer field
2. Don't select any text
3. Click on the link button

## Your setup
**Kirby Version**  
4.0.0-beta.1

**Your system (please complete the following information)**
 - OS: macOs 13.5.1
 - Browser: Arc
 - Version: 1.8.1

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

For the Writer link and email dialog, insert the url/email address when dialog is applied and no text has been selected.

### Fixes
- #5661

### CODE REVIEW

**Review by afbora — COMMENTED** [review]
This PR fixes the issue but broke a behaviour that you can reproduce the issue with following steps:

1. Select a word
2. Insert a link to the word
3. Click to the linked word (not select whole linked text)
4. You'll see link mark is blue as active
5. Click to link button again
6. Update url or title
7. Save and see the issue

**Comment by distantnative** [comment]
> 7. Save and see the issue

@afbora Please always describe what's the issue. Best with screenshots or videos. Cause there is always the chance that I or others  are not aware of an issue - and then we won't just see it without being pointed directly to it. 😅

I just tried your steps and for me it looks all right:

https://github.com/getkirby/kirby/assets/3788865/5da8100f-5f9f-40ac-a94f-7801fbf57cbb

**Comment by afbora** [comment]
@distantnative Sorry Nico 🙈 You're right. Here my screencast:

https://github.com/getkirby/kirby/assets/3393422/00fd154c-6e54-44a3-8bd1-2f9e5487eeda

Btw this issue not exists for beta.1

**Review by bastianallgeier — DISMISSED** [review]
So we need to check if the cursor is already on an existing link

**Comment by bastianallgeier** [comment]
It would have been cool to add this to beta.2 but I don't find the time to check out how this could be solved today. Let's fix it in beta.3. I think the issue is pretty clear.

**Comment by afbora** [comment]
I've pushed a fix about the issue, check out: https://github.com/getkirby/kirby/pull/5684/commits/30c4859c7355118843641b83c8776f4cdb59f60b

**Comment by distantnative** [comment]
@afbora Oh I like the way/idea - need to test it in the next days!👍

**Comment by bastianallgeier** [comment]
I've just tested it and it works great!

**Pull request merged**
