### PR TITLE
Add check for opcode invalidation

### LINKED ISSUE #1595: Displayed user role does not update after change in users view
**Describe the bug**
When changing a user’s role from the users view in the panel, the list of all users only updates after reloading the view, when a role is changed.

**To Reproduce**
1. Go to `yoursite.test/panel/users`
2. Click on  the `…` symbol of a user and change his*her role and save.
3. The role is not updated in the list.

**Expected behavior**
The list should update

**Kirby Version**
3.1.0-rc.1

**Console output**
none

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Firefox 65.0.1

### PR DESCRIPTION
**Pull request by conallor**
Fixes #1595 

Env based, no unit test possible.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
@conallor thank you for the PR and sorry for the delay. 

There are two issues I have with this approach. 

1. I'm not sure if the invalidate opcache method should be in the F class 
2. The "writeCredentials" method is probably not the only place where we need this. 

I think we should consider to at this at a deeper level that will affect all writing operations at once.

**Comment by lukasbestle** [comment]
I think we should do the invalidation in the [`Data\PHP::write()`](https://github.com/getkirby/kirby/blob/3.1.2/src/Data/PHP.php#L80) method. As that's probably the only place we should be writing PHP data files, it's also the only place where we need opcache invalidation.

We would then of course need to switch to `Data\PHP` in all places that currently use their own duplicated code.

**Comment by bastianallgeier** [comment]
I now added your `F::invalidateOpcodeCache` method and added it to our `PHP::write()` method. This is now used in all places that write PHP files.

**Comment by bastianallgeier** [comment]
Thank you for your help :)

**Pull request closed without merging**
