### PR TITLE
Abstract `Models` class

### PR DESCRIPTION
**Pull request by distantnative**
### Enhancements
- New abstract `Cms\Models` class (extending `Cms\Collection`) as basis for `Cms\Pages`, `Cms\Files` and `Cms\Users`

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Comment by lukasbestle** [comment]
We also have `Cms\Languages`, which is also a collection of models, but doesn't have support for custom methods. With the single `Model` objects we define the `$methods` property directly in the respective class for this reason. TBH I feel it gets a bit inconsistent.

**Comment by distantnative** [comment]
A more consistent name would probably be `ModelsWithContent` in that way (collection of `ModelWithContent` objects).

**Comment by lukasbestle** [comment]
I like that!

BTW: The custom method-related logic is defined in the `HasMethods` trait. This is also already used by `Cms\Collection`. I believe the `$methods` prop is only set again in the individual models and collections to keep them separate arrays (avoids sharing with the parent object).

So IMO the question is: What do we need the `Models`/`ModelsWithContent` class for in UUIDs? If it's needed to detect if a collection has `$methods`, we can already check for `Cms\Collection`.

**Comment by distantnative** [comment]
To have a place for the `::findByUuid()` method.

https://github.com/getkirby/kirby/pull/4506/files

**Comment by lukasbestle** [comment]
Ah, I see. That makes sense.

What about a `trait HasUuids` instead? Then this can be imported into all model collections that have UUIDs. If we make a whole class, we would reduce our flexibility in the future.

**Comment by distantnative** [comment]
Could be a way. Though I think in general it would make sense to bind pages, files and users collections closer together through a dedicated class.

**Comment by lukasbestle** [comment]
> Though I think in general it would make sense to bind pages, files and users collections closer together through a dedicated class.

It might make sense at some point, but TBH I think it's theoretical at the moment. If we only want to define a single method, I don't see a use case for a whole additional inheritance layer. What happens if we extend that `Models` class with additional methods later but then want to add UUID functionality to collections where these added methods don't fit? That's why I think a trait would be more modular and future-proof.

**Comment by distantnative** [comment]
I'll close this for now - we can revisit it in the context of UUID PR.

**Pull request closed without merging**
