### PR TITLE
Panel page icons centered correctly for all browsers #2943

### LINKED ISSUE #2943: Panel page icons not centered in Firefox (regression?)
**Describe the bug**  
The page icons in the panel in 3.4.4 are not visually centered (they moved a little to the left) in Firefox 83. In 3.4.2 they were centered. Not sure what the reason for this change was, but it seems that this is what broke it: https://github.com/getkirby/kirby/commit/2ee6f19ad99fec39ffc4679f86560850c904e106#diff-b3660f1567ea5cae8696c50ecd3901dbdb5c8f1b13f235a9af8697c99462afa1.

**Screenshots**  
Firefox:
Screenshot 2020-11-22 at 17 29 37

Chrome:
Screenshot 2020-11-22 at 17 29 51

**Kirby Version**  
3.4.4

**Desktop (please complete the following information):**  
 - OS: macOS 10.15.7
 - Browser: Firefox 83

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

The best solution ever is to remove margins.

## Related issues

- Fixes #2943 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I don't really understand this, but with your fix the icons are off center for me. @distantnative @lukasbestle @texnixe could you test this on your machines as well? Am I the one who's having a weird setup here?

**Comment by afbora** [comment]
@bastianallgeier If you have a different solution, I can try it in Windows.

**Comment by bastianallgeier** [comment]
@afbora the problem is that I really don't. I have no idea how to fix it properly.

**Comment by distantnative** [comment]
Looks centered for me on Chrome and Safari on macOS. But is also did before this PR.

**Comment by bastianallgeier** [comment]
@distantnative how is this even possible?

**Comment by afbora** [comment]
A new question: why can't we center icons without using `margin` even though it's align center in css?

````css
  display: flex;
  align-items: center;
  justify-content: center;
  ````

**Comment by distantnative** [comment]
@bastianallgeier I din't say I understand it XD

**Comment by bastianallgeier** [comment]
> A new question: why can't we center icons without using `margin` even though it's align center in css?
> 
> ```css
>   display: flex;
>   align-items: center;
>   justify-content: center;
> ```

It's a known issue with emojis on retina screens. You can't "JUST" center them. Super super weird.

**Comment by lukasbestle** [comment]
Did we already try to layout emoji inside the icon box with SVG? Perhaps browsers render SVG differently/more correct than HTML and CSS.

**Comment by bastianallgeier** [comment]
> Did we already try to layout emoji inside the icon box with SVG? Perhaps browsers render SVG differently/more correct than HTML and CSS.

That could actually be a good idea. I never tried that.

**Comment by texnixe** [comment]
To me they also look off-centered in Firefox/Chrome with the changes, but I don't trust my eyes that much. I might be mistaken with my vision, but could it be that it depends on the icon as well?

**Comment by afbora** [comment]
### Out of the retina issue

Untitled-1

And why the icon is 38x38px? Is there a specific reason? 
Because the background does not fit well, it does not look very centered.
If it is 40x40px, it will look better.

**Comment by bastianallgeier** [comment]
38px is the general height of our inputs and the list items.

**Comment by bastianallgeier** [comment]
@afbora Could you try changing the width to 40px even if the height is still 38px. Does this improve the visual effect?

**Comment by afbora** [comment]
### Current Display (v3.5.1)

current

### New icon size 40x40px (no margin)

icon-40

### New parent size 40x40px (no margin)
Size applied icon and parent image div (.k-list-item-image)

parent-40

**Comment by bastianallgeier** [comment]
Ok, while the larger width looks indeed a bit better, thinking more about it, it would probably be a breaking change. Let's focus on the center alignment issue again. Sorry for the detour.

**Comment by afbora** [comment]
It's ready but there is a problem in GitHub actions.

**Comment by bastianallgeier** [comment]
@afbora thanks! let's wait for the action fix.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
