### PR TITLE
Fix date changes with adding new interpret formats

### LINKED ISSUE #5118: Date field with display property changes value while editing
## Description
Date fields with a display property that does not include a day e.g `display: MM-YYYY` change value while editing. In my case it always changes to 08-2024.

## To reproduce

1. Add the following field to a blueprint
```php
date:
    type: date
    display: MM YYYY
```
2. Select a date using the date picker
3. Focus the date field text input
4. Blur the date field text input

## Setup
**Kirby 3.9.2**  

**System**
 - OS: macOS
 - Browser: Chrome
 - Version: 109

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

@distantnative I've fixed the date changes with adding new interpret formats. But I'm not sure about the solution 🙈 Feel free to close the PR .

### Fixes
- Date field with display property changes value while editing #5118

### Breaking changes
None

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by distantnative** [comment]
We should for sure add unit tests before attempting to merge this

**Comment by afbora** [comment]
@distantnative was this PR risky for 3.9.3?

**Comment by distantnative** [comment]
@afbora I think it was rather missed because the status was still draft

**Comment by afbora** [comment]
Let's make it ready if you think the PR has correct solution.

**Review by lukasbestle — APPROVED** [review]
I think the consideration here needs to be whether the formats are "obvious" and unambiguous enough.

For `MMM YYYY` that's definitely the case.

For `MM YYYY` and `M YYYY`, the month number and year is certainly the most likely interpretation if one enters `02 2022` for example. It could also be the week of the year instead of the month though (so in that case the value would resolve to `2022-01-10`, the first day of the second week of 2022 – at least in Europe with Monday as the first day of the week 😅).

However we currently only support year, month and day as date tokens, right? If that's the case and will stay like that, I think we can safely merge this PR.

**Pull request merged**
