### PR TITLE
3.7.2-rc.1

### PR DESCRIPTION
**Pull request by bastianallgeier**

### CODE REVIEW

**Comment by lukasbestle** [comment]
Looks good except the translations. In some of them, the "Log In" translation got reversed to English. Can we discard those changes in the PR until the translations are fixed on Transifex as well?

**Comment by bastianallgeier** [comment]
@lukasbestle that's the default behaviour by Transifex. If we discard them manually. We have to redo this with every language update. That's going to be pretty shit and error-prone to be honest.

**Comment by lukasbestle** [comment]
I think we can assume that the translations are fixed until the next release. It's just for today because not every translator might have had the time to look into it yet.

**Comment by bastianallgeier** [comment]
Ok, I've reverted the changes on those that fell back to English.

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
