### PR TITLE
3.5.7 changes -> `develop`

### PR DESCRIPTION
**Pull request by lukasbestle**
I've manually merged the changes in. 33 files with merge conflicts and to be honest I'm not 100 % confident that everything went through smoothly. 😰

The end result of the changes looks fine, but there were some really weird merge conflicts I needed to fix manually. So it could well be that I've forgotten something in the process.

## ⚠️🏗️ Open todos

- [x] The file `panel/src/components/Forms/Field/StructureField.vue` had way too many conflicts to merge using my merge tool. The reason is that we massively refactored it both in 3.6 and 3.5.7, including a new file `panel/src/mixins/forms/structure.js` in 3.5.7 (https://github.com/getkirby/kirby/pull/3411). @afbora @distantnative Could you please take a look and merge this manually?
- [x] Fix failing frontend E2E tests
- [x] At the end right before the merge: Find out when we last merged in `3.5.*` into `develop`: f6c099e81cfeec8be6359b6e95996f2684e4a82f (which merged in 6b3cf988a6e773fd1d744045f3a0ab64b5ab129b)
- [x] Then look through the [diff between this point and `master`](https://github.com/getkirby/kirby/compare/6b3cf988a6e773fd1d744045f3a0ab64b5ab129b...master) manually to check if any change in 3.5.* was lost in this PR.

**Note:** There's no special Git magic involved here anymore after my initial merge, just check out the branch `feature/merge-3.5.7` and make any necessary changes to ensure that everything will be compatible with 3.6.

### CODE REVIEW

**Comment by afbora** [comment]
@lukasbestle I manually checked the PRs in 3.5.7 and all seems merged smoothly. Is there any other place that you see a problem/missing right now?

**Comment by lukasbestle** [comment]
@afbora Thank you very much! ❤️
Have you already verified that the structure field fully works after the merge?

> I manually checked the PRs in 3.5.7 and all seems merged smoothly.

🎉 I looked through the diff as well and agree that it seems to be fine.

---

Requesting a final review from @bastianallgeier @distantnative.

**Comment by afbora** [comment]
Ohh you are right in your suspicions. Field mixins was not working for develop branch but working for 3.5.7. I've fixed the issue and squashed with `Resolves StructureField conflicts` commit. Now ready for review.

**Comment by afbora** [comment]
Also need https://github.com/getkirby/kirby/pull/3483 merged to avoid regression.

**Review by distantnative — APPROVED** [review]
LGTM

**Pull request merged**
