### PR TITLE
Page move dialog: fix currently selected

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

Since `k-page-tree` only uses UUID now, need to switch over

### Fixes
- #5573

### CODE REVIEW

**Review by bastianallgeier — COMMENTED** [review]
But this would mean that the parent won't work when UUIDs are deactivated.

**Comment by distantnative** [comment]
@bastianallgeier True - but then I think we have to dial back you PageTree changes and add a prop again that decides whether to use id or uuid

**Comment by bastianallgeier** [comment]
I think I found a fix. The item.value is intended to store whatever is being submitted and we can control this pretty easily from the backend: https://github.com/getkirby/kirby/pull/5948

**Comment by distantnative** [comment]
Closing in favor of https://github.com/getkirby/kirby/pull/5948

**Pull request closed without merging**
