### PR TITLE
Clean up `k-pagination`

### PR DESCRIPTION
**Pull request by distantnative**
### Enhancement
- `k-pagination` always can be navigated by keys (no extra prop needed anymore)

### Refactored
- `k-pagination`: removed unused `align` and `dropdown` props

### Breaking changes
- `k-pagination` doesn't support setting custom labels/titles via `nextLabel`, `prevLabel` or `pageLabel`

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I don't think we can handle keyboard navigation like that. If we make it global and there are multiple paginated sections in a view, they will all be paginated at the same time. I guess we could do it as soon as one of the buttons is focused.

**Comment by distantnative** [comment]
@bastianallgeier I really just removed the need to set the prop, didn't realize that this was broken before already

**Comment by distantnative** [comment]
@bastianallgeier added an alternative

**Comment by bastianallgeier** [comment]
Oh, that's really nice!

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
