### PR TITLE
Add references to Vue and Vuex in panel object

### PR DESCRIPTION
**Pull request by yandodov**
Adds references to Vue and Vuex for plugin authors to utilize, especially when needing to use a Vuex store for their plugin.

If this PR relates to one or several issues in the `kirby` or `idea` repo, please reference them here:
- Fixes https://github.com/getkirby/ideas/issues/219

### CODE REVIEW

**Comment by yandodov** [comment]
With this fix, plugin authors could easily create a Vuex store for their plugin by using:

```js
new panel.Vuex.Store({
  ...
})
```

Otherwise, they would have to [hack their way around it](https://forum.getkirby.com/t/how-to-create-a-kirby-3-plugin-with-vuex/13390/5?u=hdodov).

**Comment by distantnative** [comment]
I have to close this, I just tested it:

**/site/plugins/test/index.php**
```php
<?php

Kirby::plugin('distantnative/test', []);
```

**/site/plugins/test/index.js**
```javascript
console.log(window.panel);
```

And what we get is `undefined` - as assumed and explained in the issue, the plugins run not only before `new Vue()`, but before all content of `main.js`.

I am thinking of an alternative: https://github.com/getkirby/kirby/pull/1589

```javascript
panel.plugin("distantnative/test", {
  created: {
    test: function (app) {
      console.log(app);
      console.log(app.$store);
    }
  }
});
```

**Comment by yandodov** [comment]
@distantnative hm. How do plugins access `panel.plugin()` in their index.js file then? I mean, that function has to be defined somewhere beforehand. Maybe you can add the references to Vue and Vuex where that function is created, so that plugins can access those as well?

**Comment by distantnative** [comment]
That function is defined here: https://github.com/getkirby/kirby/blob/master/panel/public/js/plugins.js
It is merely some kind of registry, storing the plugin definitions properly in `window.panel.plugins`. It also has no clue of the Vue instance or Vuex either.

The order is:
- https://github.com/getkirby/kirby/blob/master/panel/public/js/plugins.js
- all plugins' javascript
- https://github.com/getkirby/kirby/blob/master/panel/src/main.js

The `main.js` then imports https://github.com/getkirby/kirby/blob/master/panel/src/config/plugins.js which loads all plugin definitions and processes them accordingly.

So outside the `panel.plugin()` in your plugin's `index.js`, there is no way to get to the Vue instance or Vuex, they simply do not exist yet anywhere, as I tried to explain. This is why I think creating a plugin extension (`created()`) is the way to go. Why would that not work for you?

**Comment by yandodov** [comment]
@distantnative I've replied to you in [my issue](https://github.com/getkirby/ideas/issues/219#issuecomment-473792290).

**Pull request closed without merging**
