### PR TITLE
Set Panel image via blueprint

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

- Allows defining the Panel image options per blueprint (query, back, cover, icon...).
- Use case: e.g. only using solid background colors and wanting to differentiate pages based on template
- All Panel image options now also support query syntax

### To decide

- [x] Should blueprint settings overrule sections settings (implementation of this PR currently) or the other way around?

### Features
- Define the Panel preview image (for page, file or user) now also in the blueprint via the `image` option and not only per section
- All Panel preview image options (`back`, `color`, `cover`, `ratio`, `icon`) now support Query syntax
```yaml
image:
  back: "{{ page.panelBack }}"
  icon: false
```
- Panel image `back` and `color` options now support shorthands for core CSS color variables as well as HEX codes and all other native CSS color properties (e.g. even gradients)
```yaml
image:
  back: "linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 35%, rgba(0,212,255,1) 100%);"
```

## Breaking changes

_None_

## Related issues/ideas

- Implements https://kirby.nolt.io/104

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
This is super cool! Could you take care of the conflicts?

**Comment by distantnative** [comment]
Will do - @bastianallgeier what are your thoughts about the blueprint option name. And also in regard to if model or section settings should overrule the other one.

**Comment by bastianallgeier** [comment]
The blueprint option name is perfect. I'm not sure about overruling. My first thought is that the page setting should overrule the section setting. But I'm not 100% sure. I guess we need to see this in action to tell what makes more sense.

**Comment by distantnative** [comment]
@bastianallgeier solved the conflicts

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
