### PR TITLE
 Fix custom classes in docblocks

### PR DESCRIPTION
**Pull request by distantnative**
😬😬😬

### CODE REVIEW

**Comment by lukasbestle** [comment]
To be honest I‘m not so sure about killing the `else` blocks. In some places, that really hurts readability.

Also: Was it intended to remove the `@return void` comments?

**Comment by lukasbestle** [comment]
Another thing: Some docblocks have column indentation, which broke with the changes. I think we should remove the indentation all-together.

**Comment by distantnative** [comment]
Maybe we just go with the first commit haha.

- For my taste, `else` blocks often complicate readability. However, all these changes (in the 2nd commit that is) where made with a CS-fixer runthough, so some places you might be right that even I would prefer an else block that now has been removed.
- I read somewhere that it is more common practice to leave out the `@return` if nothing is returned than specifying it with `void`.

**Comment by distantnative** [comment]
And to make it clear: I'm fine if we just use the first commit with the classnames, that's the important one. The other one was just a spur of the moment :D

**Comment by distantnative** [comment]
@lukasbestle I toned down the changes

**Comment by bastianallgeier** [comment]
I think it would be great if we could be more strict with the scope of such PRs. The docblock changes are great and they'd be a no-brainer to merge, but I can't tell easily if removing "use" definitions won't lead to new issues, as well as some other minor things like the improved dirname call. 

We could either merge just the doc block changes or move the entire thing to 3.2.1

**Comment by distantnative** [comment]
Let's split them up again then...
I think it is crucial to get in the doc block changes. We shouldn't compromise on leaving our documentation in a worse state for longer time.

**Comment by distantnative** [comment]
@bastianallgeier only docblock changes now on this PR

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
