### PR TITLE
Fix some acii transforms #1903

### LINKED ISSUE #1903: URL slugs are not properly converted from Cyrillic
**Describe the bug**
If I create a page with title `Нашата история`, the suggested slug is `n-sh-t-ist-rija`. The letters `a` and `o` are not properly converted.

**Expected behavior**
The suggested slug should be `nashata-istorija`.

**Kirby Version**
3.2.0

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
Some weird UTF characters were missing, I added them so slugs get created correctly

## Related issues
- Fixes #1903

## Todos
- [x] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [x] Fix code style issues with CS fixer and `composer fix`

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
Do we need the same in the frontend implementation?
Besides that: 👍

**Comment by distantnative** [comment]
I might miss the question... but that is the Str toolkit class taking care of our ascii transforms everywhere.

**Comment by lukasbestle** [comment]
I mean, we have an identical implementation in JS for the Panel. Or does that get passed all ASCII rules via the API as well?

**Comment by distantnative** [comment]
Yes, yes. The Panel has only the refer and replace logic implemented in JS, all the rules and transforms it gets through the API from config and Str class.

**Review by lukasbestle — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
