### PR TITLE
Replace class name strings

### PR DESCRIPTION
**Pull request by distantnative**
### Refactoring
- Replaced many classname strings with `::class` notation fro better IDE support

## Ready?

- [x] ~~Unit tests for fixed bug/feature~~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

**Review by bastianallgeier — DISMISSED** [review]

**Comment by bastianallgeier** [comment]
@distantnative do you still want a second opinion on this? /cc @lukasbestle @afbora

**Review by afbora — DISMISSED** [review]
All files & changes checked. LGTM 👍 

Also I've added few changes based on this PR at #4850

**Comment by bastianallgeier** [comment]
Quick double-check. Should we merge this first and then yours @afbora, or should we review and merge yours directly? What's the better way? It's also interesting that your PR is already green without approvals. How can that happen?

**Comment by afbora** [comment]
@bastianallgeier Both ways are fine. 

> It's also interesting that your PR is already green without approvals. How can that happen?

My PR's target branch is `fix/class-references-more`, so this branch is not protected and no need approval.

**Review by afbora — APPROVED** [review]

**Pull request merged**
