### PR TITLE
Adds custom file methods, #372

### PR DESCRIPTION
**Pull request by distantnative**
Partly fulfils #372 - example for a pretty non-sense but working custom file method:

```php
file::$methods['soshiny'] = function($file) {
  return 'Everthing so shiny: <a href="' . $file->url() . '">' . $file->filename() . '</a>';
};
```

Gets called e.g. `$page->files()->first()->soshiny()`

### CODE REVIEW

**Comment by lukasbestle** [comment]
I think this implementation is great. Super simple and flexible.

**Comment by distantnative** [comment]
At the moment this PR will favor a file meta field (e.g. named `copyright`) over a custom file method (named `copyright()`).

**Comment by moritzz** [comment]
Great. Let's `git flow feature finish`. 🙃

**Comment by distantnative** [comment]
Well, let's first see what @bastianallgeier thinks about it. He has much more the broad overview if this fits into the concept, if it really doesn't break anything. And if this should trigger some more changes (e.g. renaming `extensions/methods.php` to `extensions/fieldmethods.php`).

**Comment by bastianallgeier** [comment]
I love it! And yes, it would make sense to have this for pages and files as well, if you ask me. Maybe even for page, though I'm not sure if this would create conflicts with models. Needs maybe a bit more thought.

**Comment by lukasbestle** [comment]
Adding this to the other objects is an awesome idea in my opinion. I think it can make sense to add it to Page as well to enable plugin devs to extend the page object and also as an alternative to models if a method is needed for every template anyway.

**Pull request merged**
