### PR TITLE
Query: `qr` entry function

### PR DESCRIPTION
**Pull request by distantnative**
### Enhancement
- Kirby queries now  support `qr()` entry function

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
LGTM 👍 But breaking changes didn't seem to me to be required. IMHO it would be better not to add breaking changes during the beta process unless it is required.

**Review by lukasbestle — COMMENTED** [review]
Hm, couldn't this be quite dangerous? Because there is no allowlist, one could call any built-in PHP function.

**Comment by distantnative** [comment]
@lukasbestle would it be better than to manually implement most/all Kirby helper functions as query entry functions?

**Comment by distantnative** [comment]
As a side note: Kirby queries already allow calling any kind of method they can reach from their entry points.

**Comment by distantnative** [comment]
Ok, I changed and limited it to just adding a `qr` entry function

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
