### PR TITLE
Fix `Toolkit\Dom::body()` for false query

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- `Toolkit\Dom::body()`: fixed for non-existent fallback

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
Hm, I don't really understand which case this change will protect against. The following still works for me:

```php
$var = false;
var_dump($var[0] ?? null);
```

**Comment by distantnative** [comment]
Was a result of checking more code quality with Psalm. Got flagged there as improper.

**Comment by lukasbestle** [comment]
Can you reproduce that on https://psalm.dev? If not, what is the full warning/error you get from Psalm?

**Comment by distantnative** [comment]
It's from an older branch of a lot of small changes I collected. But honestly not worth it spending the time again trying to find out what Psalm setting I changed to see the error. Probably shouldn't look at Psalm much anyways as it keeps also throwing false positives. Closing this.

**Pull request closed without merging**
