### PR TITLE
Don't pin specific psr/log version

### PR DESCRIPTION
**Pull request by neildaniels**
## This PR …

This unpins a specific version for `psr/log` but simultaneously forces Composer to operate as if it was under PHP 7.4.

`psr/log` was pinned to address an issue where building Kirby on PHP 8 wouldn't provide the necessary interfaces for `filp/whoops`. https://github.com/getkirby/kirby/pull/3895 https://github.com/getkirby/kirby/pull/3912

However, that had the unfortunate side-effect of overly constraining Composer-based Kirby installations, even though Kirby _doesn't_ use `psr/log` and Whoops is fully compatible with newer versions.

I've manually specified a PHP version of `7.4.0` to ensure the pre-built version of Kirby continues to select `psr/log` version `1.1.4` (both `2.x` and `3.x` require PHP 8).

### Refactoring

- Kirby's `composer.json` no longer pins the `psr/log` library to a specific version #4392

### Breaking changes

None

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
That's a very nice solution, thank you! 💛
Could you please run `composer update` to get the lockfile in line?

**Comment by neildaniels** [comment]
Yep, done.

**Comment by afbora** [comment]
Correct me if I'm wrong;

If the `platform` setting creates a fake platform for us, don't we need to run an extra `composer check-platform-reqs` command in the ci workflow?

**Comment by neildaniels** [comment]
Good point. I just added that check.

**Review by lukasbestle — APPROVED** [review]
`composer analyze` is not actually run by CI. I have added a step to the version-specific CI job so that the platform requirements are checked for each version Kirby supports.

**Review by afbora — APPROVED** [review]

**Pull request merged**
