### PR TITLE
Fix `Array.prototype` overwrites breaking `for...in` loops

### PR DESCRIPTION
**Pull request by johannschopplich**
## This PR …

… wishes the team a happy new year! While fixing a bug.

I'm developing a new Kirby Panel plugin, which uses a third-party JavaScript library. This library itself uses the `for...in` loop. The Panel itself adds two methods to the `Array.prototype`: `sortBy` and `split`, leading to the following error in my third-party library:

> The `Array.prototype` contains unexpected enumerable properties: sortBy, split; thus breaking e.g. `for...in` iteration of `Array`s.", name: "UnknownErrorException", details: "Error: The `Array.prototype` contains unexpected enumerable properties: sortBy, split; thus breaking e.g. `for...in` iteration of `Array`s."

Modifying `Array.prototype` or any built-in prototype is generally considered a bad practice, but who cares. 🙂 Unfortunately, I can't change the third-party library and need a fix.

When you add properties to `Array.prototype`, they become enumerable, which means they will show up in `for...in` loops that iterate over arrays. This can lead to errors and bugs, especially if other parts of the codebase are not expecting these additional properties. This isn't relevant for the Panel, but Panel plugins running in the same thread.

Since the Panel has to add methods to `Array.prototype` and we want to avoid this error, we have another option:
- Use `Object.defineProperty`: This way, they won't appear in `for...in` loops.

My plugin depends on the third-party library, so development is kinda blocked at the moment. If I may have a wish for the new year, it's the merge of this PR. Thanks in advance!

### Fixes

Any JavaScript code that uses `for...in` under the hood.

### Breaking changes

None.

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Review by bastianallgeier — DISMISSED** [review]
That's one of those decisions that we need to undo at some point. Your solution seems great to me. @distantnative what do you think?

**Comment by distantnative** [comment]
Wondering if we should already use this moment t move these to normal helper functions, then use object.defineProperty as suggested to add them in a usable way to the Array object, but mark that already as deprecated.

**Comment by johannschopplich** [comment]
I thought so as well – why not make them importable utils like all the other helpers (debounce etc.).

**Comment by distantnative** [comment]
@johannschopplich 

Do you have an idea why this doesn't seem to work?

```js
export function split() {
//...
}

Object.defineProperty(Array.prototype, "split", {
	value: split,
	enumerable: false, // This makes sure the property is not enumerable
	writable: true,
	configurable: true
});
```

**Comment by johannschopplich** [comment]
Mmh, I guess because the `this` has different context. In the standalone function, it doesn't has the properties of `Array.protoype`. 🤔

**Comment by distantnative** [comment]
Yes, the first parameter must be the array then. But somehow still didn't work for me

**Comment by distantnative** [comment]
Ok I just had a stupid typo somewhere that completely threw me off.

What do you think of https://github.com/getkirby/kirby/commit/48fe18054c3a9a1ff44c95d4cc9dc76c9018d6c1?
Is `Array.fromObject` a similar issue?

**Comment by johannschopplich** [comment]
https://github.com/getkirby/kirby/commit/48fe18054c3a9a1ff44c95d4cc9dc76c9018d6c1 looks fine. Great solution while being backwards-compatible. 👏 

Regarding `Array.fromObject`: Somehow it doesn't seem to throw a JS error, but I think migrating it as well would be a sustainable choice. Especially since it is rarely used.

Edit: Feel free to close this PR in favor of your commit.

**Comment by distantnative** [comment]
Closing in favor of https://github.com/getkirby/kirby/pull/6140

**Pull request closed without merging**
