### PR TITLE
`k-draggable` directly built on top of SortableJS 

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

Cutting out vue-draggable as it won't be compatible with Vue 3

@afbora would love to get your heavy testing skills on this one, if possible. That would be great <3

### Refactored
- `k-draggable` is directly built on top of SortableJS now

### Breaking changes
- `k-draggable`: the `move` callback function is receiving an event with an altered data structure

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and checks all pass

### For review team

- [x] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by bogdancondorachi** [comment]
There's this [vue-draggable-plus](https://github.com/Alfred-Skyblue/vue-draggable-plus) that's a replacement for the old vue-draggable with support for Vue>=v3 or Vue>=2.7 and it's actively maintained. Just wanted to mention it, sorry for interrupting :)

**Comment by distantnative** [comment]
@bogdancondorachi I've been through so many of these other libraries. They all have had their own issues.

**Review by bastianallgeier — APPROVED** [review]
From what I tested, it all works great and I really love that we get rid of the wrapper. It's great to have full access to Sortable and its options now.

**Comment by bastianallgeier** [comment]
The CI issue is weird. I cannot reproduce this locally. It might be connected to the old node environment that we still use for the action.

**Comment by distantnative** [comment]
@bastianallgeier yea, I think we can ignore the CI failure.

But I think it would be great to also get @afbora's approval for some additional testing.

**Comment by afbora** [comment]
@distantnative Sorry for couldn't test immediately. I can able to test next week due to our Ramadan holiday.

**Comment by bastianallgeier** [comment]
@afbora do you have time to look at it this week?

**Review by afbora — DISMISSED** [review]
Everything works fine. We can still test the components until v5.

**Review by afbora — APPROVED** [review]
Everything works fine. We can still test the components until v5.

**Pull request merged**
