### PR TITLE
Multilang permalinks for Writer field

### LINKED ISSUE #5551: [V4] UUID permalinks always redirect to default language page
## Description
When the languages are enabled, when you add a link to another page, the `@/page/uuid`-link is the same for every language.

**Expected behavior**  
When I'm on a page in any non-default language, for instance `site.com/es/sobre-nosotros/`, where the default page link will be `site.com/about-us/`, I want to open the page in that language and not the default language.

## To reproduce
1. Enable languages in your `config.php`

```
/*
* https://getkirby.com/docs/reference/system/options/languages
*/
'languages' => [
	'detect' => false
],
```

2. Make your own language your default language and add another non-default one, for instance Spanish
3. Create a few page, type some stuff and add on one of those pages a link to another one

In your default language it works, when you open the Spanish version of the page and you click the link, it redirects you to the linked page in the default language. Editing the link on the Spanish version of the page doesn't help either.

## Your setup
**Kirby Version**  
4.0.0-alpha.7

**Language files in `site/languages/`**
NL (for me)
```
<?php
    return [
        'code' => 'nl',
        'default' => true,
        'direction' => 'ltr',
        'locale' => 'nl_NL',
        'name' => 'Nederlands',
        'url' => '/',
        'translations' => [ *etc*
```
ES (test)
```
<?php
    return [
        'code' => 'es',
        'default' => false,
        'direction' => 'ltr',
        'locale' => 'es_ES',
        'name' => 'Español',
        'url' => '/es',
        'translations' => [ *etc*
```

### PR DESCRIPTION
**Pull request by distantnative**
## Description

It looks to me like PhpUnit again ignores a test due to the method name, `::url` does have unit tests.

### Summary of changes
- `::permalink()` now returns a localized permalink in a multilang setup
- Link dialog inserts localized permalinks when a current language is given

### Reasoning
This should resolve https://github.com/getkirby/kirby/issues/5551.
When `language.detect` setting is disabled, Kirby has no way to automatically figure out to which language to route a normal permalink. This is why the permalinks need to include the language code themselves, representing a permanent link to that page in this specific language. https://github.com/getkirby/kirby/pull/6312 added the routing support for this. But this PR adds that those language-based permalinks are exposed in the right places:
- when put out via `$page->permalink()`
- when inserting a permalink in the writer field HTML 

### Additional context
I hope I have covered all cases to now convert not just normal permalinks but language-based permalinks back and forth with UUIDs and normal IDs in the Panel code.

@afbora It would be super valuable to get your expert testing skills thrown at this to be sure.

### Fixes
- Multilang: Writer field now inserts the correct permalink for the current content language
- Multilang: `$page->permalink()` returns a language-based permalink for the current content language

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
Do you think we need language prefix for file permalinks? Is there any difference both `/@/file/tWNX7ZrzJUvS9Vad` and `/en/@/file/tWNX7ZrzJUvS9Vad`? AFAIK files are singular objects. But page contents are different according to access uri.

**Comment by distantnative** [comment]
@afbora Valid point. I'll check what's the best way to do just pages.

**Review by afbora — APPROVED** [review]
LGTM 👍

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Any chance, we can get the code coverage back up or do you think it's another coverage mistake?

**Comment by distantnative** [comment]
@bastianallgeier as I wrote above, I think the `FileUuid` and `PageUuid` classes do indeed have tests covering `::url()` - or am I reading this wrong?

**Comment by bastianallgeier** [comment]
Forget my comment. I missed your remark about the code coverage.

**Pull request merged**
