### PR TITLE
Added intersection() and intersects() methods to Collection

### PR DESCRIPTION
**Pull request by neildaniels**
## Describe the PR
- Adds an `intersection()` method to `Collection` that returns a new collection that only has elements that are in both the receiver and passed collection.
- Adds an `intersects()` method that returns `true`/`false` whether the receiver collection and passed collection have an intersection.

## Related issues
- Implements https://github.com/getkirby/ideas/issues/214

## Todos
If you feel like you can help to check off the following tasks, that'd be great. If not, don't worry - we will take care of it.
- [x] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [x] Fix code style issues with CS fixer and `composer fix`
- [x] If needed, in-code documentation (DocBlocks etc.)

### CODE REVIEW

**Review by texnixe — COMMENTED** [review]
Maybe call it `hasIntersection($other)` to be more in line with the other methods that return a boolean?

**Comment by neildaniels** [comment]
> Maybe call it `hasIntersection($other)` to be more in line with the other methods that return a boolean?

I initially went back and forth, but eventually ended up with `intersects()` because it reads more naturally (at least to me). "Collection 1 intersects Collection 2" versus "Collection 1 has an intersection with Collection 2."

I also associate the prefix `has` with properties/attributes that are more "concrete," like `hasMethod()` and `hasFiles()`. `hasIntersection()` gives me the impression that a collection intrinsically has an intersection.

Some boolean methods use the prefix `is`, but that sounds unnatural to me (e.g. `isIntersecting()`.

The existing `$page->exists()` method is probably the most similar to my proposed `intersects()` method. `exists()` returns a boolean and does not have a prefix such as `doesExist()` or `hasExistence()`.

I prefer the name `intersects()`, but `hasIntersection()` wouldn't be a dealbreaker.

As a matter of comparison, here are some examples of frameworks using `intersects()` as method names:
- https://developer.apple.com/documentation/foundation/nsset/1417472-intersects
- https://docs.oracle.com/javase/7/docs/api/java/awt/Shape.html#intersects(java.awt.geom.Rectangle2D)

I couldn't find many contemporary uses of `hasIntersection()`, but something like this [npm package](https://www.npmjs.com/package/has-intersection?activeTab=readme) uses it for line intersections. However, that function requires two parameters and calculates if there is an intersection (thus, it's not a very object-oriented approach).

**Comment by texnixe** [comment]
But if you don't use `$collection` but `$files->intersects()` or `$pages->intersects()` that sounds strange to my grammatical ear…

**Review by lukasbestle — APPROVED** [review]
I moved the methods to the `Kirby\Toolkit\Collection` class and made some smaller fixes to the code style. Looks great to me now. Thanks especially for the detailed tests! 👍

I think the naming of the `intersects` method is fine. I agree that it's not 100 % optimal that it doesn't fit with our method naming scheme, but there's probably no really better naming.

**Comment by distantnative** [comment]
I'd suggest to move this to 3.3.0 as it is a small feature and will get more attention in that release than adding it to a bug fix release.

**Comment by lukasbestle** [comment]
That's true!

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
