### PR TITLE
Update EULA to 2024-11-12

### PR DESCRIPTION
**Pull request by lukasbestle**
PR to `main` as this is independent of a release. We could also merge it to the 4.5 release branch if needed.

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]
I'm fine with merging it now.

**Comment by lukasbestle** [comment]
Ah, doesn't work because this doesn't come from a release branch, so the release CI workflows are not executed. I think we need to merge this into the 4.5 release branch first. Speaking of which, is there one? Can't find one.

**Comment by distantnative** [comment]
@lukasbestle I don't think it exists but could be created from the 4.5.0-rc.1 tag

**Comment by lukasbestle** [comment]
Now we just need to remember to use the release branch for the final 4.5.0 release :)

**Pull request merged**
