### PR TITLE
User view: always show prev-next

### LINKED ISSUE #4225: Logical inconsistency while navigating through panel users (prev/next buttons disappear on own account)
## Description
When logged in as user and navigating through the panel users, you can use the arrow buttons in the upper right corner of the header. When landing on your own user account, Kirby automatically redirects from `panel/users` to `panel/account` and the buttons disappear.

**Expected behavior**  
Since your own account can be between other users, I expect to stay inside `panel/users` to navigate through all users back and forward.

## To reproduce

1. Go to accounts
2. Click on random user (not yourself)
3. Navigate to your user account through arrow buttons
4. Page redirects, arrow buttons disappear

## Your setup
**Kirby Version** 
3.6.3.1

### PR DESCRIPTION
**Pull request by distantnative**
### Summary of changes
- Prev/next arrows are shown on any user view, also the account view
- `$user->next()`, `$user->prev()` are based on a siblings collection that now is sorted by username (not id)

### Reasoning
- Current state has been too confusing. Maybe the new solution isn't the best one can imagine, but I'd argue better and a lot less confusing.
- Prev/next arrows should move through the same list as shown on users view. That's why the sorting needs to be added to `User::siblingsCollection()` too.

### Additional context
- I think we can improve this a lot more easily once we have view UI classes. That will allow us e.g. to have specific routes for the user view but when filtered by a specific role, where the prev-next arrows could then loop only through the users with that role.

### Enhancements
- User view: show prev/next buttons also on account view

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I think the most confusing part is that we jump to the account view for the current user. We should probably separate this and have an account view and a user view for the current user.

**Comment by distantnative** [comment]
@bastianallgeier I think I found a relatively simple way that seems to work

**Comment by bastianallgeier** [comment]
The option idea is great. But unfortunately, we can't simply change the path method like that. It's needed in other places as well. I guess it's best to untangle that as well in this PR.

**Comment by distantnative** [comment]
@bastianallgeier Do you have an example? I've looked and found other places, but all would work also with the normal user path instead of account as far as I can tell.

**Comment by distantnative** [comment]
@bastianallgeier removed that part again. I still think that this PR improves the situation, even if it's not the perfect result.

**Comment by afbora** [comment]
I like this solution. It's easy and simple 👍 

If we're still not sure and it confusing, I have an another idea that remove current user from users collection only for the pagination. Maybe it's stupid idea 🙈

**Pull request merged**
