### PR TITLE
lt.json lithuanian translation

### PR DESCRIPTION
**Pull request by romanustin**
All ready. Also might imporove some parts, when will see them in context while using sites

### CODE REVIEW

**Comment by afbora** [comment]
You can contribute by joining the Kirby team on the Transifex platform. 
So you can be notified of updates in the language.

https://www.transifex.com/getkirby/panel

_Note: Translations are automatically loaded from the Transifex platform._

**Comment by romanustin** [comment]
Ok, I see, that makes sense. Tried to join the team there, but as there is no LT language yet, had to make request for it. So made request, waiting for confirmation.

**Comment by romanustin** [comment]
@bastianallgeier , can you help with this? Not sure who is responsible to approve new language and approve joining translation team.

**Comment by texnixe** [comment]
I have approved you, now trying to find out how to add a new language.

**Comment by afbora** [comment]
@romanustin You can join the language with following (three dots on right top):

https://www.transifex.com/getkirby/panel/language/lt/

**Comment by texnixe** [comment]
The language is approved as well.

**Comment by romanustin** [comment]
Thank you! Only still can't join Lithuanian translation team. I see language in the list, but when I select to join it, have to find it in this list, but it's not present there: 
Panel | Languages_2019-08-16_16-27

**Comment by afbora** [comment]
FireShot Capture 732 - Panel - Dil - https___www transifex com_getkirby_panel_language_lt_

I can request to join successfully.

**Comment by texnixe** [comment]
I tried to add you but couldn't find you anymore. What is your username or email (or the first four letters)?

**Comment by afbora** [comment]
@romanustin If it does not appear, it is because a request to join has already been received. Don't worry 👍

**Comment by romanustin** [comment]
Ah, ok, thought the same :-) will wait for confirmation than, thank you.

**Comment by texnixe** [comment]
Should work now

**Comment by texnixe** [comment]
You don't really want to translate Lithuanian, @afbora, do you?

**Comment by romanustin** [comment]
Great, thank you, and hope the last question: maybe it is possible to import .json file I created? As now would take quite a lot of time to enter all again manually.



> You don't really want to translate Lithuanian, @afbora, do you?

I guess he was only testing :-)

**Comment by afbora** [comment]
As @romanustin said, just testing 😄 I dont know Lithuanian @texnixe 😅

**Comment by texnixe** [comment]
https://docs.transifex.com/translation/importing-translations

**Comment by afbora** [comment]
@romanustin You can upload as JSON 👍

**Comment by romanustin** [comment]
All sorted out now, thank you!

**Comment by lukasbestle** [comment]
Thank *you* for contributing the translation. 👍

**Pull request closed without merging**
