### PR TITLE
Fix widont() method when last word contains dash

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Fix `widont()` method when last word contains dash `-`

### Before
_The last space is not converted._

**Input**: `Test Headline With-Dash`
**Ouput**: `Test Headline With&#8209;Dash`

### Fixed Now
**Input**: `Test Headline With-Dash`
**Ouput**: `Test Headline&nbsp;With&#8209;Dash`

## Related issues

- Fixes https://github.com/getkirby/kirby/issues/1902

## Todos

- [x] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [ ] Fix code style issues with CS fixer and `composer fix`
- [ ] If needeed, in-code documentation (DocBlocks etc.)

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
To be honest I'm not sure if that's actually intended behavior or a bug. One could argue that the last word with the dash is already two words and therefore it isn't required to group it with another word that comes before.

But on the other hand, it probably won't really be an issue to change the behavior here – both results are fine in the end.

I'm waiting for opinions from @bastianallgeier and @distantnative, but the code gets my approval.

**Comment by afbora** [comment]
My personal opinion;

This is because a user already thinks that if a hyphen is used in or between words, it should already be referred to together.

**Comment by distantnative** [comment]
I'd agree with @afbora here. I'd consider a hyphenated word still as one word. And thus it shouldn't be on its own.

**Comment by texnixe** [comment]
Me too.

**Review by lukasbestle — APPROVED** [review]

**Review by distantnative — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Me three :)

**Pull request merged**
