### PR TITLE
Update PR template

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

Mainly added the "Release notes" section as discussed on Discord.

⚠️ PR against `master`. I think it makes most sense to use it already for 3.6 PRs, which only works on `master`.

## Release notes

Not necessary (internal change)

## Breaking changes

None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~
- [x] ~Add changes to release notes draft in Notion~

### CODE REVIEW

**Comment by distantnative** [comment]
Should we maybe also add a "benchmark" section where we add some performance-related info (if it makes sense for the PR), eg. asset file size for the Panel or once we have the speed tests in those oft the backend?

**Comment by lukasbestle** [comment]
The backend performance tests will be automated and run in CI. Asset file sizes could make sense, but I wouldn't make such information a requirement for every PR. If we think it's relevant and needs to be discussed, we can still add such a section manually, but for most PRs and especially PRs from the community it would only take a lot of effort and time.

**Comment by afbora** [comment]
I agree with Lukas. Anyway, if we think there may be a performance issue in PR, we state it in PR description.

**Review by afbora — APPROVED** [review]

**Comment by distantnative** [comment]
Got me it's the same as the breaking changes. We could've listed this on all our PRs that affect size/performance... but have we? Rarely, I'd say.

**Review by distantnative — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
There's no harm merging it on master already. That's why I merged it. I agree that we should already use it right now.

**Pull request merged**
