### PR TITLE
PHP: Remove unused imports/`use`

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Did you remove them manually or did you use some sort of script? I'm worried that we break something with this PR when a namespace is removed incorrectly and the class cannot be found afterwards.

**Comment by distantnative** [comment]
I used the PHP CS fixer

**Review by bastianallgeier — CHANGES_REQUESTED** [review]
Could you run this again on the latest state of the develop branch? Weirdly my PHP CS setup doesn't remove those use statements for me :(

**Comment by distantnative** [comment]
I’ll do it soon again. It’s not in our defaults, you have to set a separate flag.

**Comment by lukasbestle** [comment]
Maybe we should include the flag in our testing setup so that we see those unused imports in the future right when we develop new features.

**Pull request closed without merging**
