### PR TITLE
Prominent register menu btn

### PR DESCRIPTION
**Pull request by distantnative**
Screenshot 2023-09-17 at 17 30 35

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I think it actually needs to be even more prominent in the end. But I think this is a good first step.

**Review by bastianallgeier — APPROVED** [review]

**Comment by nilshoerrmann** [comment]
Not sure if this is the right place for feedback but looking at the current button style, I'd think an error occured. But this should be a positive action in my eyes (you want people to buy a license, and they want to register their installs). This could be more like a blue post-it saying "You are using an unregistered version of Kirby [ Register now ]".

**Comment by bastianallgeier** [comment]
@nilshoerrmann I like the idea to turn it into something positive.

**Comment by nilshoerrmann** [comment]
> This could be more like a blue post-it saying "You are using an unregistered version of Kirby [ Register now ]".

In the style of "Try › ❤️ › Buy", you could also write something like "Ready to launch? [ Register now ]" making clear that trying things out first is fine but you are required to pay for public sites.

**Comment by nilshoerrmann** [comment]
Just to get this out of my head, could be something like this:

kirby_register-now

**Pull request merged**
