### PR TITLE
Item: improve title and info wrapping

### PR DESCRIPTION
**Pull request by distantnative**
### Enhancements
- Sections: improved title and info wrapping

### For review team

- [x] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Just a few thoughts: 

- How does it look like when the image is not cropped? 
- How does it look if one item in the list is wrapping, but the others are not? Is it weird if the height is different? 
- The info text does not seem to wrap in the cardlets component

**Comment by distantnative** [comment]
> How does it look like when the image is not cropped?

I think fine.

Screenshot 2024-05-17 at 16 52 55
Screenshot 2024-05-17 at 16 53 28

> How does it look if one item in the list is wrapping, but the others are not? Is it weird if the height is different?

Not super pretty, but I don't think there is a way that looks super pretty and still allows the same utility of being able to read all the information for long titles/info. I think it's a very good compromise that looks ok even in those extreme cases. 

Screenshot 2024-05-17 at 16 54 57

> The info text does not seem to wrap in the cardlets component

Those are still like before. The title wraps, the info not. If you think it should here as well, we can change that, sure.

**Comment by bastianallgeier** [comment]
Uhhh, I just thought that we could maybe use grid-auto-row for the list items. I'm not entirely sure if it really works, but normally it takes care of always setting all items to the same height. That could clean up the list quite nicely. 

The images look great indeed.

**Comment by distantnative** [comment]
@bastianallgeier I looked into `grid-auto-rows` but I don't understand (or could make it happen when trying) how this should work.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
