### PR TITLE
`toggle` field: fix for missing `text` prop

### LINKED ISSUE #3696: [3.6.0-beta.1] Toggle field error in the panel
The Toggle field shows an error in the panel in 3.6.0-beta.1

screenshot-localhost-2021 09 22-12_22_49

Localhost, Windows 10

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Toggle field: show on/off as defaults when no `text` prop is defined

### Fixed regression
- Toggle field without `text` prop on `site` working again

## Related issues/ideas

- Fixes #3696

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] ~~In-code documentation (wherever needed)~~
- [x] CI checks pass

## When merging

- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
This off-on is already default in frontend. Is there any other way? Text prop of toggle field should return `null` to defaults.

https://github.com/getkirby/kirby/blob/develop/panel/src/components/Forms/Input/ToggleInput.vue#L48

**Comment by distantnative** [comment]
The issue is that our `toString`/`toSafeString` will return the id when `text` value is `null`. So the original `null` is not reaching The Vue component.

**Comment by afbora** [comment]
What do you think about following return:

````php
'text' => function ($value = null) {
    $model = $this->model();

    if (is_array($value) === true) {
        ...
    }

    if (empty($value) === false) {
        return $model->toSafeString(I18n::translate($value, $value));
    }

    return $value;
},
````

**Comment by distantnative** [comment]
I like

**Review by afbora — APPROVED** [review]

**Pull request merged**
