### PR TITLE
Update composer dependencies

### LINKED ISSUE #3280: Update composer dependencies
So that we don't forget.

### PR DESCRIPTION
**Pull request by bastianallgeier**

### CODE REVIEW

**Comment by afbora** [comment]
Since we are using specific versions, it has not been upgraded to the latest versions of the repos. Will it be upgraded at 3.6?

**Comment by bastianallgeier** [comment]
Sorry, my mistake. We should upgrade at least PHP Mailer. Let me check again.

**Comment by distantnative** [comment]
@lukasbestle had pinned exact versions (for a good reason). Do indeed we need to go through the dependencies one by one and read there release notes to not run into breaking changes. And only when we are sure, manually raising the pinned version.

**Comment by bastianallgeier** [comment]
@distantnative I just did that and fixed the releases again.

Upgraded: 

- SimpleImage 
- our composer installer
- PHPMailer
- Whoops

PHPMailer has a security release, which we should definitely upgrade to. 
The others don't mention any breaking changes and the changes overview also looks good to me.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
