### PR TITLE
Fixes slug field in structure field

### LINKED ISSUE #3826: [3.6.0-rc.1] Slug field in structure field: `Cannot read properties of null (reading '$invalid')`
**Describe the bug**  

Getting following error when using new slug field in structure field:

> `Cannot read properties of null (reading '$invalid')`

````yaml
test:
  label: Test
  type: structure
  fields:
    foo:
      type: text
    bar:
      type: slug
      sync: foo
````

**To Reproduce**  
1. Use new slug field in any structure field
2. See error

**Expected behavior**  

**Screenshots**  

**Kirby Version**  

3.6.0-rc.1

**Console output**  

````
TypeError: Cannot read properties of null (reading 'trim')
    at a.sluggify (index.js:1)
    at a.data (index.js:1)
    at a.<anonymous> (vendor.js:6)
    at vendor.js:6
    at vendor.js:6
    at yn (vendor.js:6)
    at a.Cn._init (vendor.js:6)
    at new a (vendor.js:6)
    at vendor.js:6
    at init (vendor.js:6)
errorCaptured @ index.js:1
Bt @ vendor.js:6
(anonymous) @ vendor.js:6
(anonymous) @ vendor.js:6
yn @ vendor.js:6
Cn._init @ vendor.js:6
a @ vendor.js:6
(anonymous) @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn @ vendor.js:6
(anonymous) @ vendor.js:6
Cn.$mount @ vendor.js:6
Cn.$mount @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn @ vendor.js:6
(anonymous) @ vendor.js:6
Cn.$mount @ vendor.js:6
Cn.$mount @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn @ vendor.js:6
(anonymous) @ vendor.js:6
Cn.$mount @ vendor.js:6
Cn.$mount @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn @ vendor.js:6
(anonymous) @ vendor.js:6
Cn.$mount @ vendor.js:6
Cn.$mount @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn @ vendor.js:6
(anonymous) @ vendor.js:6
Cn.$mount @ vendor.js:6
Cn.$mount @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn @ vendor.js:6
(anonymous) @ vendor.js:6
Cn.$mount @ vendor.js:6
Cn.$mount @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn @ vendor.js:6
(anonymous) @ vendor.js:6
Cn.$mount @ vendor.js:6
Cn.$mount @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn @ vendor.js:6
(anonymous) @ vendor.js:6
Cn.$mount @ vendor.js:6
Cn.$mount @ vendor.js:6
init @ vendor.js:6
(anonymous) @ vendor.js:6
f @ vendor.js:6
v @ vendor.js:6
f @ vendor.js:6
(anonymous) @ vendor.js:6
_ @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn.run @ vendor.js:6
dn @ vendor.js:6
(anonymous) @ vendor.js:6
Ut @ vendor.js:6
Promise.then (async)
qt @ vendor.js:6
te @ vendor.js:6
(anonymous) @ vendor.js:6
vn.update @ vendor.js:6
ct.notify @ vendor.js:6
set @ vendor.js:6
mn.set @ vendor.js:6
add @ index.js:1
Vt @ vendor.js:6
n @ vendor.js:6
i._wrapper @ vendor.js:6
Show 97 more frames
index.js:1 TypeError: Cannot read properties of null (reading '$invalid')
    at a.onInvalid (index.js:1)
    at a.mounted (index.js:1)
    at Vt (vendor.js:6)
    at nn (vendor.js:6)
    at Object.insert (vendor.js:6)
    at O (vendor.js:6)
    at a.__patch__ (vendor.js:6)
    at a.t._update (vendor.js:6)
    at a.r (vendor.js:6)
    at vn.get (vendor.js:6)
````

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome 94.0.4606.81

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

`null` value was trimming and fixed with checking empty string.

Alternatively, we can move the empty check to slug helper if you want.

### Fixes regressions from 3.6.0-rc.1
- Fixed slug field in structure field #3826

## Breaking changes

None

## Related issues/ideas

- Fixes #3826 

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
Shouldn't it still be trimmed if the value isn't null?

**Comment by bastianallgeier** [comment]
I think it really should be trimmed. We do the same in our PHP code. I also would move the null check and the trimming to the helper.

**Comment by afbora** [comment]
Of course we should do it, because we do it 😄
https://github.com/getkirby/kirby/blob/develop/panel/src/helpers/slug.js#L6

**Comment by bastianallgeier** [comment]
Hahaha :) Ok, then we only need to make sure that null or undefined values are not creating any issues. I think I would cast them to an empty string to be honest.

**Comment by bastianallgeier** [comment]
LOL, now I just realised that I was the one who used trim outside of the helper. 🙈  I should check out the changes more closely before I write something.

**Comment by afbora** [comment]
> Hahaha :) Ok, then we only need to make sure that null or undefined values are not creating any issues. I think I would cast them to an empty string to be honest.

@bastianallgeier Should I do anything? Do you mean casting `null` or `undefined` values to empty string in slug helper?

**Comment by bastianallgeier** [comment]
@afbora yes exactly.

**Comment by afbora** [comment]
Done, ready to review 👍

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
