### PR TITLE
Register sub-components globally #1745

### LINKED ISSUE #1745: Vue: Register subcomponents globally
@lukaskleinschmidt 
> On the same note. It would also be awesome if any currently registered subcomponents would be registered globally. I had this problem in the App.vue for example with the k-search component.

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
Register all (or all those we want to be replaceable) Vue sub-components globally.

## Related issues
- Fixes #1745

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I started importing components locally because of the unit tests. This makes each component testable individually.

**Comment by distantnative** [comment]
@bastianallgeier But it prevents developers to modify these components, see  #1745

**Comment by bastianallgeier** [comment]
I don't mean that we shouldn't be having all components defined globally. Maybe we have to think about a better way to run the tests then.

**Comment by distantnative** [comment]
@bastianallgeier I'm probably still missing something: you could still import the components locally in the test, right?

**Comment by bastianallgeier** [comment]
You are right. We can fix this in the tests

**Pull request merged**
