### PR TITLE
`Str::afterStart()` and `beforeEnd()`; used to make `Environment` code simpler

### PR DESCRIPTION
**Pull request by lukasbestle**
### Features

- New `Str::afterStart()` and `Str::beforeEnd()` methods to remove a substring only from the start or end of a string

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by distantnative** [comment]
Maybe rather as variations of the existing e.g. `Str::after` method? Via a new parameter

**Comment by lukasbestle** [comment]
They already have three arguments. I feel it could become unwieldy.

Also the new methods need to behave a bit differently in these two cases:

- **Empty needle:** `after` and `before` throw an exception. But with `afterStart` and `beforeEnd` the original string is returned as they don't have to remove anything from the string.
- **Needle that's not found:** `after` and `before` return an empty string. `afterStart` and `beforeEnd` return the original string because they remove the substring only if it's found. The rest of the string needs to stay intact.

Mixing the two behaviors into the same methods doesn't feel right to me.

**Comment by distantnative** [comment]
Ok, make sense. I added the main commit on a separate PR to `develop`: https://github.com/getkirby/kirby/pull/4339
I think it makes sense to first merge this separately from the server/environment PR and not bundle it with it.

**Comment by lukasbestle** [comment]
Good point. I've merged the other PR and will rebase the Environment PR against `develop`.

**Pull request closed without merging**
