### PR TITLE
`Html::encode()`: Use `ENT_QUOTES` #3291

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

See https://github.com/getkirby/kirby/pull/3274#issuecomment-830707349

### Enhancement
- `Html::encode()` uses the  `ENT_QUOTES` constant now for `htmlentities()`, converting both double and single quotes

### Refactoring
- `$field->method()` uses `Html::encode()`

## Breaking changes

- `Html::encode()` : Single quotes now are also converted by

## Related issues/ideas

- Fixes https://github.com/getkirby/kirby/issues/3291

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Review by afbora — COMMENTED** [review]
I guess we need to use `Html::encode()` in the `html()` method of the fields too, right?

````php
$field->value = Html::encode($field->value);
````


https://github.com/getkirby/kirby/blob/fix/3291-htmlentities-ENT_QUOTES/config/methods.php#L369

**Comment by distantnative** [comment]
@lukasbestle do you know why we haven't used `HTML::encode()` in the field method so far?

**Comment by lukasbestle** [comment]
Maybe for simplicity (less method calls and because the advanced `$keepTags` feature wouldn't be used). Or maybe we added `Html::encode()` later. 👍 for switching to it now.

**Comment by distantnative** [comment]
Added the switch.

**Review by afbora — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
