### PR TITLE
CI: Update tool versions

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

I've updated all CI tools to their latest version so that we can run CI with PHP 8.1 in a next step.

Psalm has some new features and improvements that catch more issues, so I fixed them in this PR as well.

## Release notes

None

## Breaking changes

The changes to argument names are technically breaking changes as they will break PHP 8.0 named arguments. But I think the probability that anyone used named arguments for methods that have just one argument is pretty pretty low.

### CODE REVIEW

**Comment by distantnative** [comment]
Should we check if we can include some of these changes in 3.6.0? As breaking changes (though agreed, mainly on paper than reality)

**Comment by lukasbestle** [comment]
That's exactly why I created a separate PR with milestone 3.6.0. 🤔

**Review by bastianallgeier — APPROVED** [review]
LGTM

**Review by distantnative — APPROVED** [review]
Seems like I am somewhat confused today 😆 LGTM too

**Pull request merged**
