### PR TITLE
ImageMagick: remove optimization that breaks focus

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

The optimization step only loads a minimized version of the image into memory which is why cropping (esp. focus cropping) fails as it is done in reference to the original sized image.

Without an apparent fix, I think it would be good to remove this optimize step for now.

### Fixes
- https://github.com/getkirby/kirby/issues/5855

### CODE REVIEW

**Comment by lukasbestle** [comment]
I'm confused: #5946 says the issue appears in both GD and IM, but in your last comment you couldn't reproduce it. Does this instead fix #5855?

What I'm wondering though: Could it worsen the thumb performance and make issues like #5328 come up more? I don't have a good solution either, however I feel like we would need to trade one bug for another here.

**Comment by distantnative** [comment]
Sorry, yes, wrong issue linked. Corrected it.

Certainly it could. And I don't like removing this either. But as I see it we have one bug the certainly breaks the thumb generation (right now) vs. one that causes problem with system performance limits. If we don't find a fix keeping the optimize flag - and I haven't had any success, I think the latter issue is the lesser evil.

**Review by lukasbestle — APPROVED** [review]
Yes, that's right.

I'm fine with this change, let's see what the real world implications are. We can still add it back if necessary. I first thought whether to comment out the optimization code instead, but then we'll have dead code lying around for the foreseeable future. So removing it completely for now is probably best.

**Comment by bastianallgeier** [comment]
Two thoughts: 

1) is it good to add this to 4.1.0 shortly before the release? 
2) maybe we need to have a closer look at the imagick extension for a - hopefully - more stable alternative to use imagemagick. We could still keep the im driver for whenever the imagick extension isn't there though. But that's of course beyond the scope of this PR.

**Comment by distantnative** [comment]
@bastianallgeier to my understanding thumbs are mostly broken for im users right now... so that's why I thought maybe it's not the best to have it broken still until 4.2

**Comment by bastianallgeier** [comment]
@distantnative ok, that sounds like a very reasonable argument 🙈

**Comment by bastianallgeier** [comment]
Focus definitely works well for me with this PR. I would say we give it a go. Maybe we should also have a close look at the suggested threads PR soon.

**Pull request merged**
