### PR TITLE
Extending blocks and layout methods

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

It provides a more manageable and flexible structure by adding custom methods to the game changer block and layout fields that come with Kirby 3.5.

### Features
- Extends blocks and layout methods
  - layoutsMethods
  - layoutMethods
  - layoutColumnMethods
  - blocksMethods
  - blockMethods

#### Sample Usage from Plugin

````php
<?php

Kirby::plugin('my/blocksLayoutMethods', [
    'blockMethods' => [
        'test' => function () {
            return 'block method';
        }
    ],
    'blocksMethods' => [
        'test' => function () {
            return 'blocks method';
        }
    ],
    'layoutMethods' => [
        'test' => function () {
            return 'layout method';
        }
    ],
    'layoutColumnMethods' => [
        'test' => function () {
            return 'layout column method';
        }
    ],
    'layoutsMethods' => [
        'test' => function () {
            return 'layouts method';
        }
    ]
]);
````

## Breaking changes

None

## Related issues/ideas

- Implements https://kirby.nolt.io/228

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]

**Comment by Werbschaft** [comment]
@afbora sorry to ask here already, but do you have an example of how to generate the IDs? We have often had problems with the IDs sometimes having a number at the beginning which then doesn't work in the CSS. As an alternative also gladly on Discord or at a later time

**Comment by afbora** [comment]
@Werbschaft For custom id, you can take a look the example usages in following PRs: https://github.com/getkirby/kirby/pull/3747 https://github.com/getkirby/kirby/pull/3740

**Comment by Werbschaft** [comment]
> @WebMechanic For custom id, you can take a look the example usages in following PRs: #3747 #3740

Wrong user but thanks for the example, I will have a look 🙂

**Comment by afbora** [comment]
@Werbschaft If you have a question or get stuck about extending blocks, feel free to ask please 👍

**Pull request merged**
