### PR TITLE
Fix manually sorting via `changePosition` 

### LINKED ISSUE #3589: Manual files sorting via changePosition not working correctly in 3.6-alpha2
**Describe the bug**  
Changing file sorting manually via "Change position" doesn't work as expected.

**To Reproduce**  
1. In a 3.6-alpha2 Starterkit, go to an album page
2. Make sure all images are sorted
3. Use "Change position" to move the last image to first position. Everything ok.
4. Then apply "Change position" again on the last image and move to first position. The image is correctly moved to first postion, but the last first image is now moved again to last position.

**Expected behavior**  
At step 4, the formerly first image should now be on position 2.

**Kirby Version**  
3.6-alpha2

**Desktop (please complete the following information):**  
Mac OS 11.2.2 with Firefox 89.0.2 (64-bit)

**Additional context**  
Files sorting also mixed up in 3.5.7.1
https://forum.getkirby.com/t/files-gallery-change-position-doesnt-update-and-resets-manual-sorting/22984/2

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

The problem was that it was trying to sort without using the `Sort` content value of file. I fixed it and works great but I'm not sure it's the right implementation. Need your review @distantnative 

### Fixes

- Fix manually sorting via `changePosition`  `#3589`

## Breaking changes

None

## Related issues/ideas

- Fixes #3589

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I fixed it slightly differently with a new Files::sorted method. It works in my tests, but please check again.

**Comment by afbora** [comment]
Thanks for new method. Works great for me! Good to get rid of it duplicate 🎉

**Comment by bastianallgeier** [comment]
@afbora do you have any idea why codecov is not passing? I don't really understand what's missing.

**Comment by distantnative** [comment]
The lines where you removed the old `->sort...` call with the new method aren't covered. Codecov wants every line you touched to be covered

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
