### PR TITLE
Fix back button in the login challenge view

### LINKED ISSUE #4397: [panel] Password reset by code: Back button is broken
## Description
On the panel login, after the clicking "forgot your password?" the view is stuck on  the code challenge input.
Clicking 'back' does not switch back to password input.

The route `/logout` gets fetched, responds with a 302 to login and does not have an effect.

**Expected behavior**  
Clicking 'back' should return to the default email & password form.
This should happen even while the code challenge is still active.

## To reproduce

1. Go to /panel
2. Click on 'forgot your password?'
3. Click 'back'
4. Nothing changes, even after the challenge has timed out. The only workaround is to delete the `kirby_session` cookie

## My setup
**Kirby Version**  
3.6.6

**System**
 - OS: macOS, iOS 15.1 
 - Browser: Chrome 102, iOS Safari 15.4 

**Config**  
```php
return [
  'auth' => [
    'methods' => ['password', 'password-reset'],
    'challenge' => [
      'timeout' => 10 * 60, // 10 minutes
      'email' => [
        'from'     => 'me@example.com',
        'fromName' => 'Example',
        'subject'  => 'Login code'
      ]
    ]
]
```

### PR DESCRIPTION
**Pull request by lukasbestle**
### Enhancements

- During logout, the session and Kirby's internal state is now more thoroughly cleaned

### Fixes

- The "Back" button during a password reset or two-step login works again #4397

### Breaking changes

- The Panel view `account.logout` of the `account` area was replaced by the `logout` view of the new `logout` area

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Review by afbora — DISMISSED** [review]
LGTM and works great 👍

**Comment by afbora** [comment]
By the way thinking out loud, not important

`account.logout` and `login.logout` have the same function. Would it be possible to combine the two in one place and load globally for whole panel? Do you think it makes sense? Is it easy to implement?

**Comment by distantnative** [comment]
I agree with @afbora - would be neat to not repeat the code. However, here https://github.com/getkirby/kirby/blob/main/src/Panel/Panel.php#L59 we currently make sure that `login` area is only loaded when not logged in and `account` only when logged in. Maybe we need to put the code in its own `logout` area and make sure that one is always available?

**Comment by lukasbestle** [comment]
> Maybe we need to put the code in its own `logout` area and make sure that one is always available?

Could be a way, yes. But it would be overall more code than the duplicated route is right now considering that it's only two lines of actual code. I'd be fine with both solutions. What do you prefer?

**Comment by afbora** [comment]
I would prefer `panel` (`panel.logout`, `panel.*`) area instead `logout` area. So in the future we can add an area that concerns the entire panel here.

**Comment by lukasbestle** [comment]
The Panel itself is already split into areas for site, users, system and plugin areas. We introduced the areas to keep everything modular.

**Comment by lukasbestle** [comment]
Thinking about it again, having a logout route in a login area doesn't make sense semantically. I think we should go for Nico's suggestion. If you agree, I can change it when I come home.

**Comment by afbora** [comment]
As you see fit 👍

**Comment by lukasbestle** [comment]
Ready for review again :)

**Review by afbora — APPROVED** [review]
LGTM 👍 

Few notes:
1. Need to update documents (about adding to website docs release checklist) https://getkirby.com/docs/reference/plugins/extensions/panel-areas#core-views
2. I don't know if anyone is using `account.logout` area, but can we call the removal of this area a breaking change?

**Comment by lukasbestle** [comment]
You are right, technically it's a breaking change. Don't think it was overridden by anyone though, so I think 3.7.2 is fine.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
