### PR TITLE
New `access` and `list` permissions for files

### LINKED ISSUE #5219: [v4] File is missing new `access` and `list` permissions
Features only the `read` permission. I think it should be consistent to our changes to Page.

### PR DESCRIPTION
**Pull request by afbora**
### 🎉 Features
- New `access` and `list` permissions for files #5219

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
I made a [cache enhancement for files without a template](https://github.com/getkirby/kirby/pull/5315/commits/50754d07ebc44519325a28257efe8555c2d9cad3). When I run all of them, unit tests fail while a single unit test is passed in local. Do you have any idea?

**Comment by bastianallgeier** [comment]
Is it possible that the static cache will still stick around between tests?

**Comment by afbora** [comment]
That's what I'm guessing, because when I remove the cache, the tests are successful.

**Comment by bastianallgeier** [comment]
@afbora have you ever noticed performance issues without the cache? Otherwise I would vote to keep it out. We can still add performance improvements later, but I would prefer a stable solution.

**Comment by afbora** [comment]
I'm not really sure. Maybe there's something wrong with my code. 
Also it would be great if @distantnative and @lukasbestle could take a look before going on.

**Review by distantnative — APPROVED** [review]

**Pull request merged**
