### PR TITLE
Implement system.exception hook

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR
This is an idea how to implement a new hook for `system.exception`. It will register an additional Whoops callback handler to trigger the hook which makes it possible to implement plugins for custom error monitoring (eg. Sentry).

_Original by @thathoff - moved to branch in our repo to rebase._

## Related

https://kirby.nolt.io/371

### Feature

- New `system.exception` hook

## Ready?
- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Review by bastianallgeier — DISMISSED** [review]

**Comment by bastianallgeier** [comment]
@distantnative can we convert it to a "real" PR?

**Comment by bastianallgeier** [comment]
Ahh, I guess it's about the falling code coverage.

**Comment by distantnative** [comment]
Exactly, haven't figured that out yet

**Comment by bastianallgeier** [comment]
I will look into it.

**Review by bastianallgeier — APPROVED** [review]

**Comment by thathoff** [comment]
🎉

**Pull request merged**
