### PR TITLE
Show activation bubble in mobile nav

### PR DESCRIPTION
**Pull request by distantnative**
Screenshot 2023-11-04 at 18 50 42

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Thinking more about it, we should probably throw a terribly long language at it. French maybe :)

**Comment by afbora** [comment]
Translated from deepl.com 😅 

**EN**: Ready to launch your site? Buy a license & Activate it now.
**DE**: Sind Sie bereit, Ihre Website zu starten? Kaufen Sie eine Lizenz und aktivieren Sie sie jetzt.
**FR**: Prêt à lancer votre site ? Achetez une licence et activez-la maintenant.
**TR**: Sitenizi açmaya hazır mısınız? Bir lisans satın alın ve şimdi etkinleştirin.
**ES**: ¿Listo para lanzar su sitio? Compre una licencia y actívela ahora.
**IT**: Siete pronti a lanciare il vostro sito? Acquistate una licenza e attivatela subito.
**RU**: Готовы запустить свой сайт? Купите лицензию и активируйте ее прямо сейчас.

**Comment by distantnative** [comment]
How would Basti ever think that French could be longer than German :D

**Comment by bastianallgeier** [comment]
Ok, the wurst case (German) is still fine for me …
Screenshot 2023-11-08 at 11 01 55

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
