### PR TITLE
Todos on copy/paste

### PR DESCRIPTION
**Pull request by afbora**
### Todos on #3712

- [x] Paste does not work if the block field is not empty. (only through the add dialog)
- [x] Unsupported block types can be pasted
- [x] Paste doesn't respect max option
- [ ] If only one block type available, it cannot be pasted because the selection dialog will not open.
- [ ] Copy any block that is not a code block. Then try to copy the code block as single or multiple. It is not copied.

### Possible features

- [x] Copy all button

### CODE REVIEW

**Comment by afbora** [comment]
Ready to review, we'll look at the remaining two tasks in the coming days.

**Comment by MaluNoPeleke** [comment]
I was wondering why it was always hard to paste something into list blocks (in my attempts it always required 2-3 tries and I couldn't figure out the "right" way).
Should this be fixed by this PR as well?

**Comment by afbora** [comment]
@MaluNoPeleke I guess this is a different issue. Can you open a new issue about this?

**Comment by MaluNoPeleke** [comment]
> @MaluNoPeleke I guess this is a different issue. Can you open a new issue about this?

Done: #3728

**Pull request closed without merging**
