### PR TITLE
Fix cut off image in tables

### LINKED ISSUE #4374: [3.7.0-rc.1] Several UI issues with the table layout
## Description
I love the new table layout for pages sections. However I noticed a few UI issues that I try to collect here.

CleanShot 2022-06-14 at 23 06 19@2x

1. The index number is not flipped when using `flip: true` — the pages are. It should always display the actual page index number, just like the status dialog.
2. The table headers are not vertically centered. This might be related to the different system fonts and unfortunately unsolvable.
3. Thankfully the status circle should be easy to vertically align by setting `.k-button` to `display: flex` and `align-items: center; justify-content: center`.
4. The images are cut off on the right — probably because of the border.
5. The mobile version <= 1040px hides every single field including the title. The title should never be hidden because the pages become inaccessible without the title.

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Fixes

- Images get no longer cut off in tables https://github.com/getkirby/kirby/issues/4374

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
I'm really bad on CSS/UI. But anyways I've a stupid idea 🙈 What do you think about using `box-shadow (inset)` instead `border-right`?

**Comment by bastianallgeier** [comment]
The border is on the table cell. I don't know if it really helps here to convert it to a box shadow. Doesn't the PR fix the problem for you?

**Comment by afbora** [comment]
On mobile 😱 

screen-capture-1440-Photography - Mægazine-localhost

**Comment by bastianallgeier** [comment]
Yep, the mobile view is still totally crap. But that's more related to the general responsiveness of the table.

**Comment by afbora** [comment]
No,this is related with this PR 🙈

**Comment by bastianallgeier** [comment]
@afbora this one will fix the problem with a new mobile option for columns https://github.com/getkirby/kirby/pull/4405

**Review by afbora — APPROVED** [review]
Yes #4405 and this PR fixes the issue 👍

**Pull request merged**
