### PR TITLE
Inherit 'when' for fieldgroups

### PR DESCRIPTION
**Pull request by plain-solutions-gmbh**
## This PR gives the ability to set `when` props to a group of fields.

It will be inherit to his child fields. Use it like this:
```yml
fields:
  showit:
    type: toggle
  my_group:
    type: group
    when:
      showit: true
    fields:
      my_field1:
        type: text
      my_field2:
        type: text

```

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by plain-solutions-gmbh** [comment]
It seems so stable, but multiple `when` statements are **or** operated. If a child field already has an `when` prop, it will be shown anyway, as soon the `when` of the group is *true*. 🤦‍♂️
The [More extensive field conditions](https://kirby.nolt.io/13) gonna be a huge door opener for all such things...

**Review by afbora — COMMENTED** [review]
It's a clever idea and quite simple. I like it! 👍 Btw `array_merge_recursive` method will solve your nested `when` issue.

**Comment by afbora** [comment]
What do you think @getkirby/kirby-staff about the enhancement before code review?

**Review by lukasbestle — COMMENTED** [review]
I like the concept. It is really simple and useful.

Unfortunately I cannot directly commit to the PR as the PR comes from your `main` branch. Here's a suggestion for a version that matches our coding style and uses `array_merge_recursive()`. I've also swapped the arguments so that the fields can override `when` rules from the group.

```php
	public static function fieldProps($props): array
	{
		$props = static::extend($props);

		if (isset($props['name']) === false) {
			throw new InvalidArgumentException('The field name is missing');
		}

		$name = $props['name'];
		$type = $props['type'] ?? $name;

		if ($type !== 'group' && isset(Field::$types[$type]) === false) {
			throw new InvalidArgumentException('Invalid field type ("' . $type . '")');
		}

		// support for nested fields
		if (isset($props['fields']) === true) {
			$props['fields'] = static::fieldsProps($props['fields']);
		}

		// groups don't need all the crap
		if ($type === 'group') {
			$fields = $props['fields'];

			if (isset($props['when']) === true) {
				$fields = array_map(
					fn ($field) => array_merge_recursive(['when' => $props['when']], $field),
					$fields
				);
			};

			return [
				'fields' => $fields,
				'name'   => $name,
				'type'   => $type
			];
		}

		// add some useful defaults
		return array_merge($props, [
			'label' => $props['label'] ?? ucfirst($name),
			'name'  => $name,
			'type'  => $type,
			'width' => $props['width'] ?? '1/1'
		]);
	}
```

**Comment by afbora** [comment]
@youngcut Will you be able to complete this PR or should we create a separate PR to continue?

**Comment by plain-solutions-gmbh** [comment]
If you could create a separate PR will be cool.

Btw: Do you have some time to have a look at [this issue](https://github.com/youngcut/kirby-section-block/issues/1). I contacted the other Core-Team. And they're all busy. For you, it will be be a short thing.

**Comment by afbora** [comment]
I've created new PR https://github.com/getkirby/kirby/pull/5143, thanks for the contributing @youngcut

**Pull request closed without merging**
