### PR TITLE
`upload.js`: use `method parameter`

### LINKED ISSUE #3634: Request method option for update helper cannot be overwriten
**Describe the bug**  
I can't overwrite the `method` property of this helper, you set it to POST by default, but you don't use the `method` property inside of the file [update.js](https://github.com/getkirby/kirby/blob/c77ccb82944b5fa0e3a453b4e203bd697e96330d/panel/src/helpers/upload.js#L64).

**Kirby Version**  
3.5.7.1

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

- Fix using the `method` parameter
- Remove the unused `accept` parameter

### Fixes
- `this.$helper.upload` now correctly uses the `method` parameter

## Breaking changes

None

## Related issues/ideas

-Fixes #3634

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Review by afbora — DISMISSED** [review]

**Review by lukasbestle — DISMISSED** [review]

**Comment by lukasbestle** [comment]
Related PR that should be merged first: https://github.com/getkirby/kirby/pull/3637

**Comment by distantnative** [comment]
@lukasbestle shouldn't the order be the other way around? First this PR then the referenced?

**Comment by lukasbestle** [comment]
The referenced PR merges into this PR branch.

**Comment by distantnative** [comment]
Got it now. And merged it into this PR.

**Review by afbora — APPROVED** [review]

**Pull request merged**
