### PR TITLE
Remove sorting of attributes in attr()

### PR DESCRIPTION
**Pull request by simlawr**
Removed attribute sorting, attr() now respects the chosen order of attributes. Source order is more a matter of personal preference and alphabetic ordering seams kind of arbitrary.

I find this behaviour quite annoying, so I'm really hoping it changes.

### CODE REVIEW

**Comment by simlawr** [comment]
A simple example of what's happening:

```
<?= attr(['b' => 'b', 'a' => 'a']) ?>
```

This will currently output: `a="a" b="b"`
With sorting removed, the output will be: `b="b" a="a"`

**Comment by simlawr** [comment]
In a situation where manually sorting attributes alphabetically is not practical, then `ksort()` could always be applied to the attributes array before calling `attr()`, for example:

```
<?php
$attr = [
  'b' => 'b',
  'c' => 'c',
  'a' => 'a',
];

ksort($attr);

echo attr($attr); // output: a="a" b="b" c="c"
?>
```

Better to leave the decision regarding ordering to the end user, IMHO.

**Comment by bastianallgeier** [comment]
I thought about this for a long time, but I decided to close this. I'm really sorry. Sorting attributes helps us to get more reliable and testable results.

**Comment by simlawr** [comment]
Would it be possible to put the sorting into Kirby's tests, rather than into the front-end API?

**Comment by simlawr** [comment]
Perhaps add a sort argument to `Html::attr()` which could be turned on for testing purposes.

**Comment by simlawr** [comment]
It doesn't look like this is possible 🙁

**Comment by simlawr** [comment]
I agree with @bastianallgeier, Kirby's unit tests are heavily dependant on attribute ordering and removing sorting would have significant side effects, something I hadn't appreciated.

Thanks, for taking the time to consider this!

**Comment by bastianallgeier** [comment]
Thanks for understanding!

**Pull request closed without merging**
