### PR TITLE
Add `panel.route:before` hook

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by lukasbestle** [comment]
Is there a specific reason why there is no corresponding `after` hook?

**Comment by distantnative** [comment]
I just couldn't think of any use case for that

**Comment by lukasbestle** [comment]
We have `route:after` though, so I think we should also have `panel.route:after` for consistency. Our users are very creative with finding use-cases. ;)

**Comment by distantnative** [comment]
@lukasbestle I have added a suggestion - would there be more/other/less parameters you would pass to it?

**Comment by lukasbestle** [comment]
The `route:after` hook also provides `method` and `final`, I think these should be supported as well (if they make sense).

**Comment by distantnative** [comment]
Method is possible, final doesn't exists/play a role here

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
