### PR TITLE
Adding AVIF to `$isViewable`

### PR DESCRIPTION
**Pull request by S1SYPHOS**
See #2870 

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by distantnative** [comment]
@afbora I might of your PR https://github.com/getkirby/kirby/pull/2777, do you think we should make the `isViewable` check extendable as well?

**Comment by S1SYPHOS** [comment]
Quick question: With the idea behind @afbora's PR, we could also set custom formats from plugins, right? Before the `Kirby::plugin` call ofc? This should then be extended to `$isReszable`, as well (see the discussion over at #2840) ..

**Comment by distantnative** [comment]
> Before the Kirby::plugin call ofc?

No, @afbora's PR would allow to set this in the config or within the `Kirby::plugin()` call.

**Comment by S1SYPHOS** [comment]
Thanks for clarifying. Sounds wonderful! Right now I have to overwrite `file::version` to get past the `$isResizable` check. Again, I absolutely positively realise these are edge cases - but making things configurable (for the developer at least) is a plus.

**Comment by afbora** [comment]
@distantnative If the custom file extension is `isViewable` or `isResizable`, yes IMO it should be extendable to work correctly in other parts of Kirby. Also what do you think about that? @lukasbestle 

May be sample new usage for `isViewable` and `isResizable` based on #2777 PR? 

````php
return [
    'debug' => true,
    'file' => [
        'types' => [
            'image' => [
                'heic'
            ],
            'video' => [
                'm4p'
            ]
        ],
        'isViewable' => [
            'avif'
        ],
        'isResizable' => [
            'svg'
        ]
    ]
    'mime' => [
        'types' => [
            'heic' => $mime = ['image/heic, image/heif']
        ]
    ]
];
````

**Comment by lukasbestle** [comment]
@S1SYPHOS We will include `avif` in the list of viewable file types in Kirby 3.6.0. We have also added a plugin extension to register custom file types: #2777

**Pull request closed without merging**
