### PR TITLE
Color field: fix hsl parsing

### LINKED ISSUE #5580: [v4] Color field HSL `deg|rad|grad|turn` detection
## Description

https://github.com/getkirby/kirby/assets/3393422/5dd6aaad-8e3e-4d00-933d-6459d3aa02b3

## Your setup
4.0.0-beta.1

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- #5580

### CODE REVIEW

**Comment by distantnative** [comment]
Encountered a bug, fixing it

**Comment by afbora** [comment]
How can I test? All this format is correct? `hsl(deg|rad|grad|turnINT INT% INT%)`

Also I can save the `hsl(abc 78% 63%)` value. I can see `x` indicator on the field but saveable (for public status page)

**Comment by distantnative** [comment]
You can save this string?

```
hsl(abc 78% 63%)
```

I can't:
Screenshot 2023-09-09 at 16 15 17

**Comment by afbora** [comment]
@distantnative Oh, sorry. I just update dist files 🙈 Forgot to validation part.

**Comment by distantnative** [comment]
@afbora ok, no worries.

I think all should work:

```
hsl(180 30% 60%)
hsl(180deg 30% 60%)
hsl(200grad 30% 60%)
hsl(1rad 30% 60%)
hsl(0.25turn 30% 60%)
```

**Review by afbora — APPROVED** [review]

**Pull request merged**
