### PR TITLE
Switches to `window.panel.$t()` from `Vue.$t()`

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

I hope that implementation is right. Need your review @distantnative 🙂 

## Release notes

None

## Breaking changes

None

## Related issues/ideas

None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
Changes look all good to me and work locally.
What I couldn't test: where to we actually use the `label` key for mark buttons? I couldn't find it in code. Do we use it somewhere? If not, let's add it as tooltip for the button.

**Comment by afbora** [comment]
Great! You right, I've added tooltip of marks locally.

I've a question: Should we switch `TranslationString()` usages to `window.panel.$t()`?

**Comment by distantnative** [comment]
If that works, I would say yes. Would be nice to just use that and remove `TranslationString`

**Comment by afbora** [comment]
I've tested locally and works great for me 👍

**Review by distantnative — APPROVED** [review]

**Pull request merged**
